CHAMELEON: MORSE_zgesv_incpiv_Tile_Async
int MORSE_zgesv_incpiv_Tile_Async (MORSE_desc_t * A, MORSE_desc_t * L, int * IPIV, MORSE_desc_t * B, MORSE_sequence_t * sequence, MORSE_request_t * request)
MORSE_zgesv_incpiv_Tile_Async - Solves a system of linear equations using the tile LU factorization. Non-blocking equivalent of MORSE_zgesv_incpiv_Tile(). May return before the computation is finished. Allows for pipelining of operations at runtime.
Parameters
[in] sequence Identifies the sequence of function calls that this call belongs to (for completion checks and exception handling purposes).
[out] request Identifies this function call (for exception handling purposes).
See also
MORSE_zgesv_incpiv
MORSE_zgesv_incpiv_Tile
MORSE_cgesv_incpiv_Tile_Async
MORSE_dgesv_incpiv_Tile_Async
MORSE_sgesv_incpiv_Tile_Async
MORSE_zcgesv_Tile_Async
Definition at line 265 of file zgesv_incpiv.c.
References morse_pzgetrf_incpiv(), morse_pztrsm(), and morse_pztrsmpl().
Referenced by MORSE_zgesv_incpiv(), and MORSE_zgesv_incpiv_Tile().