CHAMELEON: MORSE_zgels_Tile_Async
int MORSE_zgels_Tile_Async (MORSE_enum trans, MORSE_desc_t * A, MORSE_desc_t * T, MORSE_desc_t * B, MORSE_sequence_t * sequence, MORSE_request_t * request)
MORSE_zgels_Tile_Async - Solves overdetermined or underdetermined linear system of equations using the tile QR or the tile LQ factorization. Non-blocking equivalent of MORSE_zgels_Tile(). May return before the computation is finished. Allows for pipelining of operations at runtime.
Parameters
[in] sequence Identifies the sequence of function calls that this call belongs to (for completion checks and exception handling purposes).
[out] request Identifies this function call (for exception handling purposes).
See also
MORSE_zgels
MORSE_zgels_Tile
MORSE_cgels_Tile_Async
MORSE_dgels_Tile_Async
MORSE_sgels_Tile_Async
Definition at line 324 of file zgels.c.
References morse_pzgelqf(), morse_pzgelqfrh(), morse_pzgeqrf(), morse_pzgeqrfrh(), morse_pztrsm(), morse_pzunmlq(), morse_pzunmlqrh(), morse_pzunmqr(), and morse_pzunmqrrh().
Referenced by MORSE_zgels(), and MORSE_zgels_Tile().