CHAMELEON: MORSE_zungqr_Tile_Async
int MORSE_zungqr_Tile_Async (MORSE_desc_t * A, MORSE_desc_t * T, MORSE_desc_t * Q, MORSE_sequence_t * sequence, MORSE_request_t * request)
Non-blocking equivalent of MORSE_zungqr_Tile(). May return before the computation is finished. Allows for pipelining of operations at runtime.
Parameters
[in] sequence Identifies the sequence of function calls that this call belongs to (for completion checks and exception handling purposes).
[out] request Identifies this function call (for exception handling purposes).
See also
MORSE_zungqr
MORSE_zungqr_Tile
MORSE_cungqr_Tile_Async
MORSE_dorgqr_Tile_Async
MORSE_sorgqr_Tile_Async
MORSE_zgeqrf_Tile_Async
Definition at line 252 of file zungqr.c.
References morse_pzungqr(), and morse_pzungqrrh().
Referenced by MORSE_zungqr(), and MORSE_zungqr_Tile().