CHAMELEON: MORSE_zgelqs_Tile_Async
int MORSE_zgelqs_Tile_Async (MORSE_desc_t * A, MORSE_desc_t * T, MORSE_desc_t * B, MORSE_sequence_t * sequence, MORSE_request_t * request)
MORSE_zgelqs_Tile_Async - Computes a minimum-norm solution using previously computed LQ factorization. Non-blocking equivalent of MORSE_zgelqs_Tile(). May return before the computation is finished. Allows for pipelining of operations at runtime.
Parameters
[in] sequence Identifies the sequence of function calls that this call belongs to (for completion checks and exception handling purposes).
[out] request Identifies this function call (for exception handling purposes).
See also
MORSE_zgelqs
MORSE_zgelqs_Tile
MORSE_cgelqs_Tile_Async
MORSE_dgelqs_Tile_Async
MORSE_sgelqs_Tile_Async
MORSE_zgelqf_Tile_Async
Definition at line 260 of file zgelqs.c.
References morse_pztrsm(), morse_pzunmlq(), and morse_pzunmlqrh().
Referenced by MORSE_zgelqs(), and MORSE_zgelqs_Tile().