CHAMELEON: morse_pzgeqrf
void morse_pzgeqrf (MORSE_desc_t * A, MORSE_desc_t * T, MORSE_sequence_t * sequence, MORSE_request_t * request)
Parallel tile QR factorization - dynamic scheduling
Definition at line 44 of file pzgeqrf.c.
References MORSE_TASK_zgeqrt(), MORSE_TASK_zlaset(), MORSE_TASK_ztsmqr(), MORSE_TASK_ztsqrt(), and MORSE_TASK_zunmqr().
Referenced by MORSE_zgels_Tile_Async(), and MORSE_zgeqrf_Tile_Async().