CHAMELEON: MORSE_zgetrf_incpiv_Tile_Async
int MORSE_zgetrf_incpiv_Tile_Async (MORSE_desc_t * A, MORSE_desc_t * L, int * IPIV, MORSE_sequence_t * sequence, MORSE_request_t * request)
MORSE_zgetrf_incpiv_Tile_Async - Computes the tile LU factorization of a matrix. Non-blocking equivalent of MORSE_zgetrf_incpiv_Tile(). May return before the computation is finished. Allows for pipelining of operations at runtime.
Parameters
[in] sequence Identifies the sequence of function calls that this call belongs to (for completion checks and exception handling purposes).
[out] request Identifies this function call (for exception handling purposes).
See also
MORSE_zgetrf_incpiv
MORSE_zgetrf_incpiv_Tile
MORSE_cgetrf_incpiv_Tile_Async
MORSE_dgetrf_incpiv_Tile_Async
MORSE_sgetrf_incpiv_Tile_Async
MORSE_zgetrs_incpiv_Tile_Async
Definition at line 241 of file zgetrf_incpiv.c.
References morse_pzgetrf_incpiv().
Referenced by MORSE_zgetrf_incpiv(), and MORSE_zgetrf_incpiv_Tile().