CHAMELEON: MORSE_zlauum_Tile_Async
int MORSE_zlauum_Tile_Async (MORSE_enum uplo, MORSE_desc_t * A, MORSE_sequence_t * sequence, MORSE_request_t * request)
MORSE_zlauum_Tile_Async - Computes the product U * U' or L' * L, where the triangular factor U or L is stored in the upper or lower triangular part of the array A. Non-blocking equivalent of MORSE_zlauum_Tile(). May return before the computation is finished. Allows for pipelining of operations at runtime.
Parameters
[in] sequence Identifies the sequence of function calls that this call belongs to (for completion checks and exception handling purposes).
[out] request Identifies this function call (for exception handling purposes).
See also
MORSE_zlauum
MORSE_zlauum_Tile
MORSE_clauum_Tile_Async
MORSE_dlauum_Tile_Async
MORSE_slauum_Tile_Async
MORSE_zpotri_Tile_Async
Definition at line 240 of file zlauum.c.
References morse_pzlauum().
Referenced by MORSE_zlauum(), and MORSE_zlauum_Tile().