CHAMELEON: MORSE_TASK_zunmlq
void MORSE_TASK_zunmlq (MORSE_option_t * options, MORSE_enum side, MORSE_enum trans, int m, int n, int k, int ib, int nb, MORSE_desc_t * A, int Am, int An, int lda, MORSE_desc_t * T, int Tm, int Tn, int ldt, MORSE_desc_t * C, int Cm, int Cn, int ldc)
CORE_zunmlq overwrites the general complex M-by-N tile C with
              SIDE = 'L'     SIDE = 'R'
TRANS = 'N': Q * C C * Q TRANS = 'C': Q**H * C C * Q**H
where Q is a complex unitary matrix defined as the product of k elementary reflectors
Q = H(k) . . . H(2) H(1)
as returned by CORE_zgelqt. Q is of order M if SIDE = 'L' and of order N if SIDE = 'R'.
Parameters
[in] side
MorseLeft : apply Q or Q**H from the Left;
MorseRight : apply Q or Q**H from the Right.
[in] trans
MorseNoTrans : No transpose, apply Q;
MorseConjTrans : Transpose, apply Q**H.
[in] M The number of rows of the tile C. M >= 0.
[in] N The number of columns of the tile C. N >= 0.
[in] K The number of elementary reflectors whose product defines the matrix Q. If SIDE = MorseLeft, M >= K >= 0; if SIDE = MorseRight, N >= K >= 0.
[in] IB The inner-blocking size. IB >= 0.
[in] A Dimension: (LDA,M) if SIDE = MorseLeft, (LDA,N) if SIDE = MorseRight, The i-th row must contain the vector which defines the elementary reflector H(i), for i = 1,2,...,k, as returned by CORE_zgelqt in the first k rows of its array argument A.
[in] LDA The leading dimension of the array A. LDA >= max(1,K).
[in] T The IB-by-K triangular factor T of the block reflector. T is upper triangular by block (economic storage); The rest of the array is not referenced.
[in] LDT The leading dimension of the array T. LDT >= IB.
[in,out] C On entry, the M-by-N tile C. On exit, C is overwritten by Q*C or Q**T*C or C*Q**T or C*Q.
[in] LDC The leading dimension of the array C. LDC >= max(1,M).
[in,out] WORK On exit, if INFO = 0, WORK(1) returns the optimal LDWORK.
[in] LDWORK The dimension of the array WORK. If SIDE = MorseLeft, LDWORK >= max(1,N); if SIDE = MorseRight, LDWORK >= max(1,M).
Returns
Return values
MORSE_SUCCESS successful exit
<0 if -i, the i-th argument had an illegal value
Definition at line 120 of file codelet_zunmlq.c.
Referenced by morse_pzgelqf(), morse_pzgelqfrh(), morse_pzunglq(), morse_pzunglqrh(), morse_pzunmlq(), and morse_pzunmlqrh().