/**
 *
 * @copyright (c) 2009-2014 The University of Tennessee and The University
 *                          of Tennessee Research Foundation.
 *                          All rights reserved.
 * @copyright (c) 2012-2014 Inria. All rights reserved.
 * @copyright (c) 2012-2014 Bordeaux INP, CNRS (LaBRI UMR 5800), Inria, Univ. Bordeaux. All rights reserved.
 *
 **/

/**
 *
 * @file morse_df77.c
 *
 *  MORSE computational routines
 *  MORSE is a software package provided by Univ. of Tennessee,
 *  Univ. of California Berkeley and Univ. of Colorado Denver
 *  This file is automatically generated by tools/genf77interface.pl
 *
 * @version 2.5.0
 * @comment This file has been automatically generated
 *          from Plasma 2.5.0 for MORSE 1.0.0
 * @author Bilel Hadri
 * @author Mathieu Faverge
 * @author Emmanuel Agullo
 * @author Cedric Castagnede
 * @date 2010-11-15
 * @generated d Tue Sep 26 20:42:59 2017
 *
 **/
#include <stdlib.h>
#include "control/common.h"
#undef COMPLEX
#define REAL


/***************************************************************************//**
 *  FORTRAN API - math functions (simple interface)
 **/
#define MORSE_DLAPACK_TO_TILE MORSE_FNAME(dlapack_to_tile, DLAPACK_TO_TILE)
#define MORSE_DLAPACK_TO_TILE_ASYNC MORSE_FNAME(dlapack_to_tile_async, DLAPACK_TO_TILE_ASYNC)
#define MORSE_DTILE_TO_LAPACK MORSE_FNAME(dtile_to_lapack, DTILE_TO_LAPACK)
#define MORSE_DTILE_TO_LAPACK_ASYNC MORSE_FNAME(dtile_to_lapack_async, DTILE_TO_LAPACK_ASYNC)
//#define MORSE_DGEBRD          MORSE_FNAME(dgebrd       , DGEBRD       )
//#define MORSE_DGECFI          MORSE_FNAME(dgecfi       , ZGECFI       )
//#define MORSE_DGECFI_ASYNC    MORSE_FNAME(dgecfi_async , ZGECFI_ASYNC )
#define MORSE_DGELQF          MORSE_FNAME(dgelqf       , DGELQF       )
#define MORSE_DGELQS          MORSE_FNAME(dgelqs       , DGELQS       )
#define MORSE_DGELS           MORSE_FNAME(dgels        , DGELS        )
#define MORSE_DGEMM           MORSE_FNAME(dgemm        , DGEMM        )
#define MORSE_DGEQRF          MORSE_FNAME(dgeqrf       , DGEQRF       )
#define MORSE_DGEQRS          MORSE_FNAME(dgeqrs       , DGEQRS       )
//#define MORSE_DGESV           MORSE_FNAME(dgesv        , DGESV        )
#define MORSE_DGESV_INCPIV    MORSE_FNAME(dgesv_incpiv , DGESV_INCPIV )
#define MORSE_DGESV_NOPIV     MORSE_FNAME(dgesv_nopiv  , DGESV_NOPIV )
//#define MORSE_DGESVD          MORSE_FNAME(dgesvd       , DGESVD       )
//#define MORSE_DGETMI          MORSE_FNAME(dgetmi       , ZGETMI       )
//#define MORSE_DGETMI_ASYNC    MORSE_FNAME(dgetmi_async , ZGETMI_ASYNC )
//#define MORSE_DGETRF          MORSE_FNAME(dgetrf       , DGETRF       )
#define MORSE_DGETRF_INCPIV   MORSE_FNAME(dgetrf_incpiv, DGETRF_INCPIV)
#define MORSE_DGETRF_NOPIV    MORSE_FNAME(dgetrf_nopiv , DGETRF_NOPIV)
//#define MORSE_DGETRI          MORSE_FNAME(dgetri       , DGETRI       )
//#define MORSE_DGETRS          MORSE_FNAME(dgetrs       , DGETRS       )
#define MORSE_DGETRS_INCPIV   MORSE_FNAME(dgetrs_incpiv, DGETRS_INCPIV)
#define MORSE_DGETRS_NOPIV    MORSE_FNAME(dgetrs_nopiv , DGETRS_NOPIV)
//#define MORSE_DSYEV           MORSE_FNAME(dsyev        , DSYEV        )
//#define MORSE_DSYEVD          MORSE_FNAME(dsyevd       , DSYEVD       )
//#define MORSE_DSYGST          MORSE_FNAME(dsygst       , DSYGST       )
//#define MORSE_DHEGV           MORSE_FNAME(dsygv        , ZHEGV        )
//#define MORSE_DSYGVD          MORSE_FNAME(dsygvd       , DSYGVD       )
#ifdef COMPLEX
#define MORSE_DSYMM           MORSE_FNAME(dsymm        , DSYMM        )
#endif
#ifdef COMPLEX
#define MORSE_DSYR2K          MORSE_FNAME(dsyr2k       , DSYR2K       )
#endif
#ifdef COMPLEX
#define MORSE_DSYRK           MORSE_FNAME(dsyrk        , DSYRK        )
#endif
//#define MORSE_DSYTRD          MORSE_FNAME(dsytrd       , DSYTRD       )
#define MORSE_DLACPY          MORSE_FNAME(dlacpy       , DLACPY       )
#define MORSE_DLANGE          MORSE_FNAME(dlange       , DLANGE       )
#ifdef COMPLEX
#define MORSE_DLANSY          MORSE_FNAME(dlansy       , DLANSY       )
#endif
#define MORSE_DLANSY          MORSE_FNAME(dlansy       , DLANSY       )
#define MORSE_DLANTR          MORSE_FNAME(dlantr       , DLANTR       )
#define MORSE_DLASET          MORSE_FNAME(dlaset       , DLASET       )
//#define MORSE_DLASWP          MORSE_FNAME(dlaswp       , DLASWP       )
//#define MORSE_DLASWPC         MORSE_FNAME(dlaswpc      , DLASWPC      )
#define MORSE_DLAUUM          MORSE_FNAME(dlauum       , DLAUUM       )
#ifdef COMPLEX
#define MORSE_DPLGSY          MORSE_FNAME(dplgsy       , DPLGSY       )
#endif
#define MORSE_DPLGSY          MORSE_FNAME(dplgsy       , ZPLGSY       )
#define MORSE_DPLRNT          MORSE_FNAME(dplrnt       , ZPLRNT       )
#define MORSE_DPOSV           MORSE_FNAME(dposv        , DPOSV        )
#define MORSE_DPOTRF          MORSE_FNAME(dpotrf       , DPOTRF       )
#define MORSE_DPOTRI          MORSE_FNAME(dpotri       , DPOTRI       )
#define MORSE_DPOTRS          MORSE_FNAME(dpotrs       , DPOTRS       )
#if defined (PRECISION_c) || defined(PRECISION_z)
#define MORSE_DSYSV           MORSE_FNAME(dsysv        , DSYSV        )
#define MORSE_DSYTRF          MORSE_FNAME(dsytrf       , DSYTRF       )
#define MORSE_DSYTRS          MORSE_FNAME(dsytrs       , DSYTRS       )
#endif
#define MORSE_DSYMM           MORSE_FNAME(dsymm        , DSYMM        )
#define MORSE_DSYR2K          MORSE_FNAME(dsyr2k       , DSYR2K       )
#define MORSE_DSYRK           MORSE_FNAME(dsyrk        , DSYRK        )
#define MORSE_DTRMM           MORSE_FNAME(dtrmm        , DTRMM        )
#define MORSE_DTRSM           MORSE_FNAME(dtrsm        , DTRSM        )
#define MORSE_DTRSMPL         MORSE_FNAME(dtrsmpl      , DTRSMPL      )
//#define MORSE_DTRSMRV         MORSE_FNAME(dtrsmrv      , DTRSMRV      )
#define MORSE_DTRTRI          MORSE_FNAME(dtrtri       , DTRTRI       )
#define MORSE_DORGLQ          MORSE_FNAME(dorglq       , DORGLQ       )
#define MORSE_DORGQR          MORSE_FNAME(dorgqr       , DORGQR       )
#define MORSE_DORMLQ          MORSE_FNAME(dormlq       , DORMLQ       )
#define MORSE_DORMQR          MORSE_FNAME(dormqr       , DORMQR       )

/***************************************************************************//**
 *  FORTRAN API - math functions (native interface)
 **/
//#define MORSE_DGEBRD_TILE          MORSE_TILE_FNAME(dgebrd       , DGEBRD       )
#define MORSE_DGELQF_TILE          MORSE_TILE_FNAME(dgelqf       , DGELQF       )
#define MORSE_DGELQS_TILE          MORSE_TILE_FNAME(dgelqs       , DGELQS       )
#define MORSE_DGELS_TILE           MORSE_TILE_FNAME(dgels        , DGELS        )
#define MORSE_DGEMM_TILE           MORSE_TILE_FNAME(dgemm        , DGEMM        )
#define MORSE_DGEQRF_TILE          MORSE_TILE_FNAME(dgeqrf       , DGEQRF       )
#define MORSE_DGEQRS_TILE          MORSE_TILE_FNAME(dgeqrs       , DGEQRS       )
//#define MORSE_DGESV_TILE           MORSE_TILE_FNAME(dgesv        , DGESV        )
#define MORSE_DGESV_INCPIV_TILE    MORSE_TILE_FNAME(dgesv_incpiv , DGESV_INCPIV )
#define MORSE_DGESV_NOPIV_TILE     MORSE_TILE_FNAME(dgesv_nopiv  , DGESV_NOPIV  )
//#define MORSE_DGESVD_TILE          MORSE_TILE_FNAME(dgesvd       , DGESVD       )
//#define MORSE_DGETRF_TILE          MORSE_TILE_FNAME(dgetrf       , DGETRF       )
#define MORSE_DGETRF_INCPIV_TILE   MORSE_TILE_FNAME(dgetrf_incpiv, DGETRF_INCPIV)
#define MORSE_DGETRF_NOPIV_TILE    MORSE_TILE_FNAME(dgetrf_nopiv , DGETRF_NOPIV )
//#define MORSE_DGETRI_TILE          MORSE_TILE_FNAME(dgetri       , DGETRI       )
//#define MORSE_DGETRS_TILE          MORSE_TILE_FNAME(dgetrs       , DGETRS       )
#define MORSE_DGETRS_INCPIV_TILE   MORSE_TILE_FNAME(dgetrs_incpiv, DGETRS_INCPIV)
#define MORSE_DGETRS_NOPIV_TILE    MORSE_TILE_FNAME(dgetrs_nopiv , DGETRS_NOPIV )
//#define MORSE_DSYEV_TILE           MORSE_TILE_FNAME(dsyev        , DSYEV        )
//#define MORSE_DSYEVD_TILE          MORSE_TILE_FNAME(dsyevd       , DSYEVD       )
//#define MORSE_DSYGST_TILE          MORSE_TILE_FNAME(dsygst       , DSYGST       )
//#define MORSE_DHEGV_TILE           MORSE_TILE_FNAME(dsygv        , ZHEGV        )
//#define MORSE_DSYGVD_TILE          MORSE_TILE_FNAME(dsygvd       , DSYGVD       )
#ifdef COMPLEX
#define MORSE_DSYMM_TILE           MORSE_TILE_FNAME(dsymm        , DSYMM        )
#endif
#ifdef COMPLEX
#define MORSE_DSYR2K_TILE          MORSE_TILE_FNAME(dsyr2k       , DSYR2K       )
#endif
#ifdef COMPLEX
#define MORSE_DSYRK_TILE           MORSE_TILE_FNAME(dsyrk        , DSYRK        )
#endif
//#define MORSE_DSYTRD_TILE          MORSE_TILE_FNAME(dsytrd       , DSYTRD       )
#define MORSE_DLACPY_TILE          MORSE_TILE_FNAME(dlacpy       , DLACPY       )
#define MORSE_DLANGE_TILE          MORSE_TILE_FNAME(dlange       , DLANGE       )
#ifdef COMPLEX
#define MORSE_DLANSY_TILE          MORSE_TILE_FNAME(dlansy       , DLANSY       )
#endif
#define MORSE_DLANSY_TILE          MORSE_TILE_FNAME(dlansy       , DLANSY       )
#define MORSE_DLASET_TILE          MORSE_TILE_FNAME(dlaset       , DLASET       )
//#define MORSE_DLASWP_TILE          MORSE_TILE_FNAME(dlaswp       , DLASWP       )
//#define MORSE_DLASWPC_TILE         MORSE_TILE_FNAME(dlaswpc      , DLASWPC      )
#define MORSE_DLAUUM_TILE          MORSE_TILE_FNAME(dlauum       , DLAUUM       )
#ifdef COMPLEX
#define MORSE_DPLGSY_TILE          MORSE_TILE_FNAME(dplgsy       , DPLGSY       )
#endif
#define MORSE_DPLGSY_TILE          MORSE_TILE_FNAME(dplgsy       , ZPLGSY       )
#define MORSE_DPLRNT_TILE          MORSE_TILE_FNAME(dplrnt       , ZPLRNT       )
#define MORSE_DPOSV_TILE           MORSE_TILE_FNAME(dposv        , DPOSV        )
#define MORSE_DPOTRF_TILE          MORSE_TILE_FNAME(dpotrf       , DPOTRF       )
#define MORSE_DPOTRI_TILE          MORSE_TILE_FNAME(dpotri       , DPOTRI       )
#define MORSE_DPOTRS_TILE          MORSE_TILE_FNAME(dpotrs       , DPOTRS       )
#if defined (PRECISION_c) || defined(PRECISION_z)
#define MORSE_DSYSV_TILE           MORSE_TILE_FNAME(dsysv        , DSYSV        )
#define MORSE_DSYTRF_TILE          MORSE_TILE_FNAME(dsytrf       , DSYTRF       )
#define MORSE_DSYTRS_TILE          MORSE_TILE_FNAME(dsytrs       , DSYTRS       )
#endif
#define MORSE_DSYMM_TILE           MORSE_TILE_FNAME(dsymm        , DSYMM        )
#define MORSE_DSYR2K_TILE          MORSE_TILE_FNAME(dsyr2k       , DSYR2K       )
#define MORSE_DSYRK_TILE           MORSE_TILE_FNAME(dsyrk        , DSYRK        )
#define MORSE_DTRMM_TILE           MORSE_TILE_FNAME(dtrmm        , DTRMM        )
#define MORSE_DTRSM_TILE           MORSE_TILE_FNAME(dtrsm        , DTRSM        )
#define MORSE_DTRSMPL_TILE         MORSE_TILE_FNAME(dtrsmpl      , DTRSMPL      )
//#define MORSE_DTRSMRV_TILE         MORSE_TILE_FNAME(dtrsmrv      , DTRSMRV      )
#define MORSE_DTRTRI_TILE          MORSE_TILE_FNAME(dtrtri       , DTRTRI       )
#define MORSE_DORGLQ_TILE          MORSE_TILE_FNAME(dorglq       , DORGLQ       )
#define MORSE_DORGQR_TILE          MORSE_TILE_FNAME(dorgqr       , DORGQR       )
#define MORSE_DORMLQ_TILE          MORSE_TILE_FNAME(dormlq       , DORMLQ       )
#define MORSE_DORMQR_TILE          MORSE_TILE_FNAME(dormqr       , DORMQR       )

/***************************************************************************//**
 *  FORTRAN API - math functions (asynchronous interface)
 **/
//#define MORSE_DGEBRD_TILE_ASYNC          MORSE_ASYNC_FNAME(dgebrd       , DGEBRD       )
#define MORSE_DGELQF_TILE_ASYNC          MORSE_ASYNC_FNAME(dgelqf       , DGELQF       )
#define MORSE_DGELQS_TILE_ASYNC          MORSE_ASYNC_FNAME(dgelqs       , DGELQS       )
#define MORSE_DGELS_TILE_ASYNC           MORSE_ASYNC_FNAME(dgels        , DGELS        )
#define MORSE_DGEMM_TILE_ASYNC           MORSE_ASYNC_FNAME(dgemm        , DGEMM        )
#define MORSE_DGEQRF_TILE_ASYNC          MORSE_ASYNC_FNAME(dgeqrf       , DGEQRF       )
#define MORSE_DGEQRS_TILE_ASYNC          MORSE_ASYNC_FNAME(dgeqrs       , DGEQRS       )
//#define MORSE_DGESV_TILE_ASYNC           MORSE_ASYNC_FNAME(dgesv        , DGESV        )
#define MORSE_DGESV_INCPIV_TILE_ASYNC    MORSE_ASYNC_FNAME(dgesv_incpiv , DGESV_INCPIV )
#define MORSE_DGESV_NOPIV_TILE_ASYNC     MORSE_ASYNC_FNAME(dgesv_nopiv  , DGESV_NOPIV  )
//#define MORSE_DGESVD_TILE_ASYNC          MORSE_ASYNC_FNAME(dgesvd       , DGESVD       )
//#define MORSE_DGETRF_TILE_ASYNC          MORSE_ASYNC_FNAME(dgetrf       , DGETRF       )
#define MORSE_DGETRF_INCPIV_TILE_ASYNC   MORSE_ASYNC_FNAME(dgetrf_incpiv, DGETRF_INCPIV)
#define MORSE_DGETRF_NOPIV_TILE_ASYNC    MORSE_ASYNC_FNAME(dgetrf_nopiv , DGETRF_NOPIV )
//#define MORSE_DGETRI_TILE_ASYNC          MORSE_ASYNC_FNAME(dgetri       , DGETRI       )
//#define MORSE_DGETRS_TILE_ASYNC          MORSE_ASYNC_FNAME(dgetrs       , DGETRS       )
#define MORSE_DGETRS_INCPIV_TILE_ASYNC   MORSE_ASYNC_FNAME(dgetrs_incpiv, DGETRS_INCPIV)
#define MORSE_DGETRS_NOPIV_TILE_ASYNC    MORSE_ASYNC_FNAME(dgetrs_nopiv , DGETRS_NOPIV )
//#define MORSE_DSYEV_TILE_ASYNC           MORSE_ASYNC_FNAME(dsyev        , DSYEV        )
//#define MORSE_DSYEVD_TILE_ASYNC          MORSE_ASYNC_FNAME(dsyevd       , DSYEVD       )
//#define MORSE_DSYGST_TILE_ASYNC          MORSE_ASYNC_FNAME(dsygst       , DSYGST       )
//#define MORSE_DHEGV_TILE_ASYNC           MORSE_ASYNC_FNAME(dsygv        , ZHEGV        )
//#define MORSE_DSYGVD_TILE_ASYNC          MORSE_ASYNC_FNAME(dsygvd       , DSYGVD       )
#ifdef COMPLEX
#define MORSE_DSYMM_TILE_ASYNC           MORSE_ASYNC_FNAME(dsymm        , DSYMM        )
#define MORSE_DSYR2K_TILE_ASYNC          MORSE_ASYNC_FNAME(dsyr2k       , DSYR2K       )
#define MORSE_DSYRK_TILE_ASYNC           MORSE_ASYNC_FNAME(dsyrk        , DSYRK        )
#endif
//#define MORSE_DSYTRD_TILE_ASYNC          MORSE_ASYNC_FNAME(dsytrd       , DSYTRD       )
#define MORSE_DLACPY_TILE_ASYNC          MORSE_ASYNC_FNAME(dlacpy       , DLACPY       )
#define MORSE_DLANGE_TILE_ASYNC          MORSE_ASYNC_FNAME(dlange       , DLANGE       )
#ifdef COMPLEX
#define MORSE_DLANSY_TILE_ASYNC          MORSE_ASYNC_FNAME(dlansy       , DLANSY       )
#endif
#define MORSE_DLANSY_TILE_ASYNC          MORSE_ASYNC_FNAME(dlansy       , DLANSY       )
#define MORSE_DLANTR_TILE_ASYNC          MORSE_ASYNC_FNAME(dlantr       , DLANTR       )
#define MORSE_DLASET_TILE_ASYNC          MORSE_ASYNC_FNAME(dlaset       , DLASET       )
//#define MORSE_DLASWP_TILE_ASYNC          MORSE_ASYNC_FNAME(dlaswp       , DLASWP       )
//#define MORSE_DLASWPC_TILE_ASYNC         MORSE_ASYNC_FNAME(dlaswpc      , DLASWPC      )
#define MORSE_DLAUUM_TILE_ASYNC          MORSE_ASYNC_FNAME(dlauum       , DLAUUM       )
#ifdef COMPLEX
#define MORSE_DPLGSY_TILE_ASYNC          MORSE_ASYNC_FNAME(dplgsy       , DPLGSY       )
#endif
#define MORSE_DPLGSY_TILE_ASYNC          MORSE_ASYNC_FNAME(dplgsy       , ZPLGSY       )
#define MORSE_DPLRNT_TILE_ASYNC          MORSE_ASYNC_FNAME(dplrnt       , ZPLRNT       )
#define MORSE_DPOSV_TILE_ASYNC           MORSE_ASYNC_FNAME(dposv        , DPOSV        )
#define MORSE_DPOTRF_TILE_ASYNC          MORSE_ASYNC_FNAME(dpotrf       , DPOTRF       )
#define MORSE_DPOTRI_TILE_ASYNC          MORSE_ASYNC_FNAME(dpotri       , DPOTRI       )
#define MORSE_DPOTRS_TILE_ASYNC          MORSE_ASYNC_FNAME(dpotrs       , DPOTRS       )
#if defined (PRECISION_c) || defined(PRECISION_z)
#define MORSE_DSYSV_TILE_ASYNC           MORSE_ASYNC_FNAME(dsysv        , DSYSV        )
#define MORSE_DSYTRF_TILE_ASYNC          MORSE_ASYNC_FNAME(dsytrf       , DSYTRF       )
#define MORSE_DSYTRS_TILE_ASYNC          MORSE_ASYNC_FNAME(dsytrs       , DSYTRS       )
#endif
#define MORSE_DSYMM_TILE_ASYNC           MORSE_ASYNC_FNAME(dsymm        , DSYMM        )
#define MORSE_DSYR2K_TILE_ASYNC          MORSE_ASYNC_FNAME(dsyr2k       , DSYR2K       )
#define MORSE_DSYRK_TILE_ASYNC           MORSE_ASYNC_FNAME(dsyrk        , DSYRK        )
#define MORSE_DTRMM_TILE_ASYNC           MORSE_ASYNC_FNAME(dtrmm        , DTRMM        )
#define MORSE_DTRSM_TILE_ASYNC           MORSE_ASYNC_FNAME(dtrsm        , DTRSM        )
#define MORSE_DTRSMPL_TILE_ASYNC         MORSE_ASYNC_FNAME(dtrsmpl      , DTRSMPL      )
//#define MORSE_DTRSMRV_TILE_ASYNC         MORSE_ASYNC_FNAME(dtrsmrv      , DTRSMRV      )
#define MORSE_DTRTRI_TILE_ASYNC          MORSE_ASYNC_FNAME(dtrtri       , DTRTRI       )
#define MORSE_DORGLQ_TILE_ASYNC          MORSE_ASYNC_FNAME(dorglq       , DORGLQ       )
#define MORSE_DORGQR_TILE_ASYNC          MORSE_ASYNC_FNAME(dorgqr       , DORGQR       )
#define MORSE_DORMLQ_TILE_ASYNC          MORSE_ASYNC_FNAME(dormlq       , DORMLQ       )
#define MORSE_DORMQR_TILE_ASYNC          MORSE_ASYNC_FNAME(dormqr       , DORMQR       )

/***************************************************************************//**
 *  FORTRAN API - workspace allocation
 **/
//#define MORSE_ALLOC_WORKSPACE_DGEBRD              MORSE_WS_FNAME(dgebrd            , DGEBRD            )
//#define MORSE_ALLOC_WORKSPACE_DGEEV               MORSE_WS_FNAME(dgeev             , DGEEV             )
//#define MORSE_ALLOC_WORKSPACE_DGEHRD              MORSE_WS_FNAME(dgehrd            , DGEHRD            )
#define MORSE_ALLOC_WORKSPACE_DGELQF              MORSE_WS_FNAME(dgelqf            , DGELQF            )
#define MORSE_ALLOC_WORKSPACE_DGELQF_TILE         MORSE_WS_FNAME(dgelqf_tile       , DGELQF_TILE       )
#define MORSE_ALLOC_WORKSPACE_DGELS               MORSE_WS_FNAME(dgels             , DGELS             )
#define MORSE_ALLOC_WORKSPACE_DGELS_TILE          MORSE_WS_FNAME(dgels_tile        , DGELS_TILE        )
#define MORSE_ALLOC_WORKSPACE_DGEQRF              MORSE_WS_FNAME(dgeqrf            , DGEQRF            )
#define MORSE_ALLOC_WORKSPACE_DGEQRF_TILE         MORSE_WS_FNAME(dgeqrf_tile       , DGEQRF_TILE       )
#define MORSE_ALLOC_WORKSPACE_DGESV_INCPIV        MORSE_WS_FNAME(dgesv_incpiv      , DGESV_INCPIV      )
#define MORSE_ALLOC_WORKSPACE_DGESV_INCPIV_TILE   MORSE_WS_FNAME(dgesv_incpiv_tile , DGESV_INCPIV_TILE )
//#define MORSE_ALLOC_WORKSPACE_DGESVD              MORSE_WS_FNAME(dgesvd            , DGESVD            )
#define MORSE_ALLOC_WORKSPACE_DGETRF_INCPIV       MORSE_WS_FNAME(dgetrf_incpiv     , DGETRF_INCPIV     )
#define MORSE_ALLOC_WORKSPACE_DGETRF_INCPIV_TILE  MORSE_WS_FNAME(dgetrf_incpiv_tile, DGETRF_INCPIV_TILE)
//#define MORSE_ALLOC_WORKSPACE_DGETRI_TILE_ASYNC   MORSE_WS_FNAME(dgetri_tile_async , DGETRI_TILE_ASYNC )
//#define MORSE_ALLOC_WORKSPACE_DSYEV               MORSE_WS_FNAME(dsyev             , DSYEV             )
//#define MORSE_ALLOC_WORKSPACE_DSYEVD              MORSE_WS_FNAME(dsyevd            , DSYEVD            )
//#define MORSE_ALLOC_WORKSPACE_ZHEGV               MORSE_WS_FNAME(dsygv             , ZHEGV             )
//#define MORSE_ALLOC_WORKSPACE_DSYGVD              MORSE_WS_FNAME(dsygvd            , DSYGVD            )
//#define MORSE_ALLOC_WORKSPACE_DSYTRD              MORSE_WS_FNAME(dsytrd            , DSYTRD            )



/***************************************************************************//**
 *  FORTRAN API - math functions (simple interface)
 **/
void MORSE_DLAPACK_TO_TILE(double *Af77, int *LDA, MORSE_desc_t *A, int *info)
{ *info = MORSE_dLapack_to_Tile(Af77, *LDA, A); }

void MORSE_DLAPACK_TO_TILE_ASYNC(double *Af77, int *LDA, MORSE_desc_t *A, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_dLapack_to_Tile_Async(Af77, *LDA, A, sequence, request); }

void MORSE_DTILE_TO_LAPACK(MORSE_desc_t *A, double *Af77, int *LDA, int *info)
{ *info = MORSE_dTile_to_Lapack(A, Af77, *LDA); }

void MORSE_DTILE_TO_LAPACK_ASYNC(MORSE_desc_t *A, double *Af77, int *LDA, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_dTile_to_Lapack_Async(A, Af77, *LDA, sequence, request); }

//void MORSE_DGEBRD(int *M, int *N, double *A, int *LDA, double *D, double *E, MORSE_desc_t **descT, int *info)
//{ *info = MORSE_dgebrd(*M, *N, A, *LDA, D, E, *descT); }
//
//void MORSE_DGECFI(int *m, int *n, double *A, MORSE_enum *fin, int *imb, int *inb, MORSE_enum *fout, int *omb, int *onb, int *info)
//{ *info = MORSE_dgecfi(*m, *n, A, *fin, *imb, *inb, *fout, *omb, *onb); }
//
//void MORSE_DGECFI_ASYNC(int *m, int *n, double *A, MORSE_enum *f_in, int *imb, int *inb, MORSE_enum *f_out, int *omb, int *onb, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
//{ *info = MORSE_dgecfi_Async(*m, *n, A, *f_in, *imb, *inb, *f_out, *omb, *onb, sequence, request); }

void MORSE_DGELQF(int *M, int *N, double *A, int *LDA, MORSE_desc_t **descT, int *info)
{ *info = MORSE_dgelqf(*M, *N, A, *LDA, *descT); }

void MORSE_DGELQS(int *M, int *N, int *NRHS, double *A, int *LDA, MORSE_desc_t **descT, double *B, int *LDB, int *info)
{ *info = MORSE_dgelqs(*M, *N, *NRHS, A, *LDA, *descT, B, *LDB); }

void MORSE_DGELS(MORSE_enum *trans, int *M, int *N, int *NRHS, double *A, int *LDA, MORSE_desc_t **descT, double *B, int *LDB, int *info)
{ *info = MORSE_dgels(*trans, *M, *N, *NRHS, A, *LDA, *descT, B, *LDB); }

void MORSE_DGEMM(MORSE_enum *transA, MORSE_enum *transB, int *M, int *N, int *K, double *alpha, double *A, int *LDA, double *B, int *LDB, double *beta, double *C, int *LDC, int *info)
{ *info = MORSE_dgemm(*transA, *transB, *M, *N, *K, *alpha, A, *LDA, B, *LDB, *beta, C, *LDC); }

void MORSE_DGEQRF(int *M, int *N, double *A, int *LDA, MORSE_desc_t **descT, int *info)
{ *info = MORSE_dgeqrf(*M, *N, A, *LDA, *descT); }

void MORSE_DGEQRS(int *M, int *N, int *NRHS, double *A, int *LDA, MORSE_desc_t **descT, double *B, int *LDB, int *info)
{ *info = MORSE_dgeqrs(*M, *N, *NRHS, A, *LDA, *descT, B, *LDB); }

//void MORSE_DGESV(int *N, int *NRHS, double *A, int *LDA, int *IPIV, double *B, int *LDB, int *info)
//{ *info = MORSE_dgesv(*N, *NRHS, A, *LDA, IPIV, B, *LDB); }

void MORSE_DGESV_INCPIV(int *N, int *NRHS, double *A, int *LDA, MORSE_desc_t **descL, int *IPIV, double *B, int *LDB, int *info)
{ *info = MORSE_dgesv_incpiv(*N, *NRHS, A, *LDA, *descL, IPIV, B, *LDB); }

void MORSE_DGESV_NOPIV(int *N, int *NRHS, double *A, int *LDA, double *B, int *LDB, int *info)
{ *info = MORSE_dgesv_nopiv(*N, *NRHS, A, *LDA, B, *LDB); }

//void MORSE_DGESVD(MORSE_enum *jobu, MORSE_enum *jobvt, int *M, int *N, double *A, int *LDA, double *S, double *U, int *LDU, double *VT, int *LDVT, MORSE_desc_t **descT, int *info)
//{ *info = MORSE_dgesvd(*jobu, *jobvt, *M, *N, A, *LDA, S, U, *LDU, VT, *LDVT, *descT); }

//void MORSE_DGETMI(int *m, int *n, double *A, MORSE_enum *fin, int *mb, int *nb, int *info)
//{ *info = MORSE_dgetmi(*m, *n, A, *fin, *mb, *nb); }
//
//void MORSE_DGETMI_ASYNC(int *m, int *n, double *A, MORSE_enum *f_in, int *mb, int *inb, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
//{ *info = MORSE_dgetmi_Async(*m, *n, A, *f_in, *mb, *inb, sequence, request); }
//
//void MORSE_DGETRF(int *M, int *N, double *A, int *LDA, int *IPIV, int *info)
//{ *info = MORSE_dgetrf(*M, *N, A, *LDA, IPIV); }

void MORSE_DGETRF_INCPIV(int *M, int *N, double *A, int *LDA, MORSE_desc_t **descL, int *IPIV, int *info)
{ *info = MORSE_dgetrf_incpiv(*M, *N, A, *LDA, *descL, IPIV); }

void MORSE_DGETRF_NOPIV(int *M, int *N, double *A, int *LDA, int *info)
{ *info = MORSE_dgetrf_nopiv(*M, *N, A, *LDA); }

//void MORSE_DGETRI(int *N, double *A, int *LDA, int *IPIV, int *info)
//{ *info = MORSE_dgetri(*N, A, *LDA, IPIV); }
//
//void MORSE_DGETRS(MORSE_enum *trans, int *N, int *NRHS, double *A, int *LDA, int *IPIV, double *B, int *LDB, int *info)
//{ *info = MORSE_dgetrs(*trans, *N, *NRHS, A, *LDA, IPIV, B, *LDB); }

void MORSE_DGETRS_INCPIV(MORSE_enum *trans, int *N, int *NRHS, double *A, int *LDA, MORSE_desc_t **descL, int *IPIV, double *B, int *LDB, int *info)
{ *info = MORSE_dgetrs_incpiv(*trans, *N, *NRHS, A, *LDA, *descL, IPIV, B, *LDB); }

void MORSE_DGETRS_NOPIV(MORSE_enum *trans, int *N, int *NRHS, double *A, int *LDA, double *B, int *LDB, int *info)
{ *info = MORSE_dgetrs_nopiv(*trans, *N, *NRHS, A, *LDA, B, *LDB); }

//void MORSE_DSYEV(MORSE_enum *jobz, MORSE_enum *uplo, int *N, double *A, int *LDA, double *W, MORSE_desc_t **descT, double *Q, int *LDQ, int *info)
//{ *info = MORSE_dsyev(*jobz, *uplo, *N, A, *LDA, W, *descT, Q, *LDQ); }
//
//void MORSE_DSYEVD(MORSE_enum *jobz, MORSE_enum *uplo, int *N, double *A, int *LDA, double *W, MORSE_desc_t **descT, double *Q, int *LDQ, int *info)
//{ *info = MORSE_dsyevd(*jobz, *uplo, *N, A, *LDA, W, *descT, Q, *LDQ); }
//
//void MORSE_DSYGST(MORSE_enum *itype, MORSE_enum *uplo, int *N, double *A, int *LDA, double *B, int *LDB, int *info)
//{ *info = MORSE_dsygst(*itype, *uplo, *N, A, *LDA, B, *LDB); }
//
//void MORSE_DHEGV(MORSE_enum *itype, MORSE_enum *jobz, MORSE_enum *uplo, int *N, double *A, int *LDA, double *B, int *LDB, double *W, MORSE_desc_t **descT, double *Q, int *LDQ, int *info)
//{ *info = MORSE_dhegv(*itype, *jobz, *uplo, *N, A, *LDA, B, *LDB, W, *descT, Q, *LDQ); }
//
//void MORSE_DSYGVD(MORSE_enum *itype, MORSE_enum *jobz, MORSE_enum *uplo, int *N, double *A, int *LDA, double *B, int *LDB, double *W, MORSE_desc_t **descT, double *Q, int *LDQ, int *info)
//{ *info = MORSE_dsygvd(*itype, *jobz, *uplo, *N, A, *LDA, B, *LDB, W, *descT, Q, *LDQ); }

#ifdef COMPLEX
void MORSE_DSYMM(MORSE_enum *side, MORSE_enum *uplo, int *M, int *N, double *alpha, double *A, int *LDA, double *B, int *LDB, double *beta, double *C, int *LDC, int *info)
{ *info = MORSE_dsymm(*side, *uplo, *M, *N, *alpha, A, *LDA, B, *LDB, *beta, C, *LDC); }
#endif

#ifdef COMPLEX
void MORSE_DSYR2K(MORSE_enum *uplo, MORSE_enum *trans, int *N, int *K, double *alpha, double *A, int *LDA, double *B, int *LDB, double *beta, double *C, int *LDC, int *info)
{ *info = MORSE_dsyr2k(*uplo, *trans, *N, *K, *alpha, A, *LDA, B, *LDB, *beta, C, *LDC); }
#endif

#ifdef COMPLEX
void MORSE_DSYRK(MORSE_enum *uplo, MORSE_enum *trans, int *N, int *K, double *alpha, double *A, int *LDA, double *beta, double *C, int *LDC, int *info)
{ *info = MORSE_dsyrk(*uplo, *trans, *N, *K, *alpha, A, *LDA, *beta, C, *LDC); }
#endif

//void MORSE_DSYTRD(MORSE_enum *jobz, MORSE_enum *uplo, int *N, double *A, int *LDA, double *D, double *E, MORSE_desc_t **descT, double *Q, int *LDQ, int *info)
//{ *info = MORSE_dsytrd(*jobz, *uplo, *N, A, *LDA, D, E, *descT, Q, *LDQ); }

void MORSE_DLACPY(MORSE_enum *uplo, int *M, int *N, double *A, int *LDA, double *B, int *LDB, int *info)
{ *info = MORSE_dlacpy(*uplo, *M, *N, A, *LDA, B, *LDB); }

void MORSE_DLANGE(MORSE_enum *norm, int *M, int *N, double *A, int *LDA, double *result)
{ *result = MORSE_dlange(*norm, *M, *N, A, *LDA); }

#ifdef COMPLEX
void MORSE_DLANSY(MORSE_enum *norm, MORSE_enum *uplo, int *N, double *A, int *LDA, double *result)
{ *result = MORSE_dlansy(*norm, *uplo, *N, A, *LDA); }
#endif

void MORSE_DLANSY(MORSE_enum *norm, MORSE_enum *uplo, int *N, double *A, int *LDA, double *result)
{ *result = MORSE_dlansy(*norm, *uplo, *N, A, *LDA); }

void MORSE_DLANTR(MORSE_enum *norm, MORSE_enum *uplo, MORSE_enum *diag, int *M, int *N, double *A, int *LDA, double *result)
{ *result = MORSE_dlantr(*norm, *uplo, *diag, *M, *N, A, *LDA); }

void MORSE_DLASET(MORSE_enum *uplo, int *M, int *N, double *alpha, double *beta, double *A, int *LDA, int *info)
{ *info = MORSE_dlaset(*uplo, *M, *N, *alpha, *beta, A, *LDA); }

//void MORSE_DLASWP(int *N, double *A, int *LDA, int *K1, int *K2, int *IPIV, int *INCX, int *info)
//{ *info = MORSE_dlaswp(*N, A, *LDA, *K1, *K2, IPIV, *INCX); }
//
//void MORSE_DLASWPC(int *N, double *A, int *LDA, int *K1, int *K2, int *IPIV, int *INCX, int *info)
//{ *info = MORSE_dlaswpc(*N, A, *LDA, *K1, *K2, IPIV, *INCX); }

void MORSE_DLAUUM(MORSE_enum *uplo, int *N, double *A, int *LDA, int *info)
{ *info = MORSE_dlauum(*uplo, *N, A, *LDA); }

#ifdef COMPLEX
void MORSE_DPLGSY(double *bump, int *N, double *A, int *LDA, unsigned long long int  *seed, int *info)
{ *info = MORSE_dplgsy(*bump, *N, A, *LDA, *seed); }
#endif

void MORSE_DPLGSY(double *bump, int *N, double *A, int *LDA, unsigned long long int  *seed, int *info)
{ *info = MORSE_dplgsy(*bump, *N, A, *LDA, *seed); }

void MORSE_DPLRNT(int *M, int *N, double *A, int *LDA, unsigned long long int  *seed, int *info)
{ *info = MORSE_dplrnt(*M, *N, A, *LDA, *seed); }

void MORSE_DPOSV(MORSE_enum *uplo, int *N, int *NRHS, double *A, int *LDA, double *B, int *LDB, int *info)
{ *info = MORSE_dposv(*uplo, *N, *NRHS, A, *LDA, B, *LDB); }

void MORSE_DPOTRF(MORSE_enum *uplo, int *N, double *A, int *LDA, int *info)
{ *info = MORSE_dpotrf(*uplo, *N, A, *LDA); }

void MORSE_DPOTRI(MORSE_enum *uplo, int *N, double *A, int *LDA, int *info)
{ *info = MORSE_dpotri(*uplo, *N, A, *LDA); }

void MORSE_DPOTRS(MORSE_enum *uplo, int *N, int *NRHS, double *A, int *LDA, double *B, int *LDB, int *info)
{ *info = MORSE_dpotrs(*uplo, *N, *NRHS, A, *LDA, B, *LDB); }

#if defined (PRECISION_c) || defined(PRECISION_z)
void MORSE_DSYSV(MORSE_enum *uplo, int *N, int *NRHS, double *A, int *LDA, double *B, int *LDB, int *info)
{ *info = MORSE_dsysv(*uplo, *N, *NRHS, A, *LDA, B, *LDB); }

void MORSE_DSYTRF(MORSE_enum *uplo, int *N, double *A, int *LDA, int *info)
{ *info = MORSE_dsytrf(*uplo, *N, A, *LDA); }

void MORSE_DSYTRS(MORSE_enum *uplo, int *N, int *NRHS, double *A, int *LDA, double *B, int *LDB, int *info)
{ *info = MORSE_dsytrs(*uplo, *N, *NRHS, A, *LDA, B, *LDB); }
#endif

void MORSE_DSYMM(MORSE_enum *side, MORSE_enum *uplo, int *M, int *N, double *alpha, double *A, int *LDA, double *B, int *LDB, double *beta, double *C, int *LDC, int *info)
{ *info = MORSE_dsymm(*side, *uplo, *M, *N, *alpha, A, *LDA, B, *LDB, *beta, C, *LDC); }

void MORSE_DSYR2K(MORSE_enum *uplo, MORSE_enum *trans, int *N, int *K, double *alpha, double *A, int *LDA, double *B, int *LDB, double *beta, double *C, int *LDC, int *info)
{ *info = MORSE_dsyr2k(*uplo, *trans, *N, *K, *alpha, A, *LDA, B, *LDB, *beta, C, *LDC); }

void MORSE_DSYRK(MORSE_enum *uplo, MORSE_enum *trans, int *N, int *K, double *alpha, double *A, int *LDA, double *beta, double *C, int *LDC, int *info)
{ *info = MORSE_dsyrk(*uplo, *trans, *N, *K, *alpha, A, *LDA, *beta, C, *LDC); }

void MORSE_DTRMM(MORSE_enum *side, MORSE_enum *uplo, MORSE_enum *transA, MORSE_enum *diag, int *N, int *NRHS, double *alpha, double *A, int *LDA, double *B, int *LDB, int *info)
{ *info = MORSE_dtrmm(*side, *uplo, *transA, *diag, *N, *NRHS, *alpha, A, *LDA, B, *LDB); }

void MORSE_DTRSM(MORSE_enum *side, MORSE_enum *uplo, MORSE_enum *transA, MORSE_enum *diag, int *N, int *NRHS, double *alpha, double *A, int *LDA, double *B, int *LDB, int *info)
{ *info = MORSE_dtrsm(*side, *uplo, *transA, *diag, *N, *NRHS, *alpha, A, *LDA, B, *LDB); }

void MORSE_DTRSMPL(int *N, int *NRHS, double *A, int *LDA, MORSE_desc_t **descL, int *IPIV, double *B, int *LDB, int *info)
{ *info = MORSE_dtrsmpl(*N, *NRHS, A, *LDA, *descL, IPIV, B, *LDB); }

//void MORSE_DTRSMRV(MORSE_enum *side, MORSE_enum *uplo, MORSE_enum *transA, MORSE_enum *diag, int *N, int *NRHS, double *alpha, double *A, int *LDA, double *B, int *LDB, int *info)
//{ *info = MORSE_dtrsmrv(*side, *uplo, *transA, *diag, *N, *NRHS, *alpha, A, *LDA, B, *LDB); }

void MORSE_DTRTRI(MORSE_enum *uplo, MORSE_enum *diag, int *N, double *A, int *LDA, int *info)
{ *info = MORSE_dtrtri(*uplo, *diag, *N, A, *LDA); }

void MORSE_DORGLQ(int *M, int *N, int *K, double *A, int *LDA, MORSE_desc_t **descT, double *B, int *LDB, int *info)
{ *info = MORSE_dorglq(*M, *N, *K, A, *LDA, *descT, B, *LDB); }

void MORSE_DORGQR(int *M, int *N, int *K, double *A, int *LDA, MORSE_desc_t **descT, double *B, int *LDB, int *info)
{ *info = MORSE_dorgqr(*M, *N, *K, A, *LDA, *descT, B, *LDB); }

void MORSE_DORMLQ(MORSE_enum *side, MORSE_enum *trans, int *M, int *N, int *K, double *A, int *LDA, MORSE_desc_t **descT, double *B, int *LDB, int *info)
{ *info = MORSE_dormlq(*side, *trans, *M, *N, *K, A, *LDA, *descT, B, *LDB); }

void MORSE_DORMQR(MORSE_enum *side, MORSE_enum *trans, int *M, int *N, int *K, double *A, int *LDA, MORSE_desc_t **descT, double *B, int *LDB, int *info)
{ *info = MORSE_dormqr(*side, *trans, *M, *N, *K, A, *LDA, *descT, B, *LDB); }


/***************************************************************************//**
 *  FORTRAN API - math functions (native interface)
 **/
//void MORSE_DGEBRD_TILE(MORSE_desc_t *A, double *D, double *E, MORSE_desc_t *T, int *info)
//{ *info = MORSE_dgebrd_Tile(A, D, E, T); }

void MORSE_DGELQF_TILE(MORSE_desc_t *A, MORSE_desc_t *T, int *info)
{ *info = MORSE_dgelqf_Tile(A, T); }

void MORSE_DGELQS_TILE(MORSE_desc_t *A, MORSE_desc_t *T, MORSE_desc_t *B, int *info)
{ *info = MORSE_dgelqs_Tile(A, T, B); }

void MORSE_DGELS_TILE(MORSE_enum *trans, MORSE_desc_t *A, MORSE_desc_t *T, MORSE_desc_t *B, int *info)
{ *info = MORSE_dgels_Tile(*trans, A, T, B); }

void MORSE_DGEMM_TILE(MORSE_enum *transA, MORSE_enum *transB, double *alpha, MORSE_desc_t *A, MORSE_desc_t *B, double *beta, MORSE_desc_t *C, int *info)
{ *info = MORSE_dgemm_Tile(*transA, *transB, *alpha, A, B, *beta, C); }

void MORSE_DGEQRF_TILE(MORSE_desc_t *A, MORSE_desc_t *T, int *info)
{ *info = MORSE_dgeqrf_Tile(A, T); }

void MORSE_DGEQRS_TILE(MORSE_desc_t *A, MORSE_desc_t *T, MORSE_desc_t *B, int *info)
{ *info = MORSE_dgeqrs_Tile(A, T, B); }

//void MORSE_DGESV_TILE(MORSE_desc_t *A, int *IPIV, MORSE_desc_t *B, int *info)
//{ *info = MORSE_dgesv_Tile(A, IPIV, B); }

void MORSE_DGESV_INCPIV_TILE(MORSE_desc_t *A, MORSE_desc_t *L, int *IPIV, MORSE_desc_t *B, int *info)
{ *info = MORSE_dgesv_incpiv_Tile(A, L, IPIV, B); }

void MORSE_DGESV_NOPIV_TILE(MORSE_desc_t *A, MORSE_desc_t *B, int *info)
{ *info = MORSE_dgesv_nopiv_Tile(A, B); }

//void MORSE_DGESVD_TILE(MORSE_enum *jobu, MORSE_enum *jobvt, MORSE_desc_t *A, double *S, MORSE_desc_t *U, MORSE_desc_t *VT, MORSE_desc_t *T, int *info)
//{ *info = MORSE_dgesvd_Tile(*jobu, *jobvt, A, S, U, VT, T); }

//void MORSE_DGETRF_TILE(MORSE_desc_t *A, int *IPIV, int *info)
//{ *info = MORSE_dgetrf_Tile(A, IPIV); }

void MORSE_DGETRF_INCPIV_TILE(MORSE_desc_t *A, MORSE_desc_t *L, int *IPIV, int *info)
{ *info = MORSE_dgetrf_incpiv_Tile(A, L, IPIV); }

void MORSE_DGETRF_NOPIV_TILE(MORSE_desc_t *A, int *info)
{ *info = MORSE_dgetrf_nopiv_Tile(A); }

//void MORSE_DGETRI_TILE(MORSE_desc_t *A, int *IPIV, int *info)
//{ *info = MORSE_dgetri_Tile(A, IPIV); }
//
//void MORSE_DGETRS_TILE(MORSE_enum *trans, MORSE_desc_t *A, int *IPIV, MORSE_desc_t *B, int *info)
//{ *info = MORSE_dgetrs_Tile(*trans, A, IPIV, B); }

void MORSE_DGETRS_INCPIV_TILE(MORSE_desc_t *A, MORSE_desc_t *L, int *IPIV, MORSE_desc_t *B, int *info)
{ *info = MORSE_dgetrs_incpiv_Tile(A, L, IPIV, B); }

void MORSE_DGETRS_NOPIV_TILE(MORSE_desc_t *A, MORSE_desc_t *B, int *info)
{ *info = MORSE_dgetrs_nopiv_Tile(A, B); }

//void MORSE_DSYEV_TILE(MORSE_enum *jobz, MORSE_enum *uplo, MORSE_desc_t *A, double *W, MORSE_desc_t *T, double *Q, int *LDQ, int *info)
//{ *info = MORSE_dsyev_Tile(*jobz, *uplo, A, W, T, Q, *LDQ); }
//
//void MORSE_DSYEVD_TILE(MORSE_enum *jobz, MORSE_enum *uplo, MORSE_desc_t *A, double *W, MORSE_desc_t *T, double *Q, int *LDQ, int *info)
//{ *info = MORSE_dsyevd_Tile(*jobz, *uplo, A, W, T, Q, *LDQ); }
//
//void MORSE_DSYGST_TILE(MORSE_enum *itype, MORSE_enum *uplo, MORSE_desc_t *A, MORSE_desc_t *B, int *info)
//{ *info = MORSE_dsygst_Tile(*itype, *uplo, A, B); }
//
//void MORSE_DHEGV_TILE(MORSE_enum *itype, MORSE_enum *jobz, MORSE_enum *uplo, MORSE_desc_t *A, MORSE_desc_t *B, double *W, MORSE_desc_t *T, MORSE_desc_t *Q, int *info)
//{ *info = MORSE_dhegv_Tile(*itype, *jobz, *uplo, A, B, W, T, Q); }
//
//void MORSE_DSYGVD_TILE(MORSE_enum *itype, MORSE_enum *jobz, MORSE_enum *uplo, MORSE_desc_t *A, MORSE_desc_t *B, double *W, MORSE_desc_t *T, MORSE_desc_t *Q, int *info)
//{ *info = MORSE_dsygvd_Tile(*itype, *jobz, *uplo, A, B, W, T, Q); }

#ifdef COMPLEX
void MORSE_DSYMM_TILE(MORSE_enum *side, MORSE_enum *uplo, double *alpha, MORSE_desc_t *A, MORSE_desc_t *B, double *beta, MORSE_desc_t *C, int *info)
{ *info = MORSE_dsymm_Tile(*side, *uplo, *alpha, A, B, *beta, C); }
#endif

#ifdef COMPLEX
void MORSE_DSYR2K_TILE(MORSE_enum *uplo, MORSE_enum *trans, double *alpha, MORSE_desc_t *A, MORSE_desc_t *B, double *beta, MORSE_desc_t *C, int *info)
{ *info = MORSE_dsyr2k_Tile(*uplo, *trans, *alpha, A, B, *beta, C); }
#endif

#ifdef COMPLEX
void MORSE_DSYRK_TILE(MORSE_enum *uplo, MORSE_enum *trans, double *alpha, MORSE_desc_t *A, double *beta, MORSE_desc_t *C, int *info)
{ *info = MORSE_dsyrk_Tile(*uplo, *trans, *alpha, A, *beta, C); }
#endif

//void MORSE_DSYTRD_TILE(MORSE_enum *jobz, MORSE_enum *uplo, MORSE_desc_t *A, double *D, double *E, MORSE_desc_t *T, double *Q, int *LDQ, int *info)
//{ *info = MORSE_dsytrd_Tile(*jobz, *uplo, A, D, E, T, Q, *LDQ); }

void MORSE_DLACPY_TILE(MORSE_enum *uplo, MORSE_desc_t *A, MORSE_desc_t *B, int *info)
{ *info = MORSE_dlacpy_Tile(*uplo, A, B); }

void MORSE_DLANGE_TILE(MORSE_enum *norm, MORSE_desc_t *A, double *result)
{ *result = MORSE_dlange_Tile(*norm, A); }

#ifdef COMPLEX
void MORSE_DLANSY_TILE(MORSE_enum *norm, MORSE_enum *uplo, MORSE_desc_t *A, double *result)
{ *result = MORSE_dlansy_Tile(*norm, *uplo, A); }
#endif

void MORSE_DLANSY_TILE(MORSE_enum *norm, MORSE_enum *uplo, MORSE_desc_t *A, double *result)
{ *result = MORSE_dlansy_Tile(*norm, *uplo, A); }

void MORSE_DLANTR_TILE(MORSE_enum *norm, MORSE_enum *uplo, MORSE_enum *diag, MORSE_desc_t *A, double *result)
{ *result = MORSE_dlantr_Tile(*norm, *uplo, *diag, A); }

void MORSE_DLASET_TILE(MORSE_enum *uplo, double *alpha, double *beta, MORSE_desc_t *A, int *info)
{ *info = MORSE_dlaset_Tile(*uplo, *alpha, *beta, A); }

//void MORSE_DLASWP_TILE(MORSE_desc_t *A, int *K1, int *K2, int *IPIV, int *INCX, int *info)
//{ *info = MORSE_dlaswp_Tile(A, *K1, *K2, IPIV, *INCX); }
//
//void MORSE_DLASWPC_TILE(MORSE_desc_t *A, int *K1, int *K2, int *IPIV, int *INCX, int *info)
//{ *info = MORSE_dlaswpc_Tile(A, *K1, *K2, IPIV, *INCX); }

void MORSE_DLAUUM_TILE(MORSE_enum *uplo, MORSE_desc_t *A, int *info)
{ *info = MORSE_dlauum_Tile(*uplo, A); }

#ifdef COMPLEX
void MORSE_DPLGSY_TILE(double *bump, MORSE_desc_t *A, unsigned long long int  *seed, int *info)
{ *info = MORSE_dplgsy_Tile(*bump, A, *seed); }
#endif

void MORSE_DPLGSY_TILE(double *bump, MORSE_desc_t *A, unsigned long long int  *seed, int *info)
{ *info = MORSE_dplgsy_Tile(*bump, A, *seed); }

void MORSE_DPLRNT_TILE(MORSE_desc_t *A, unsigned long long int  *seed, int *info)
{ *info = MORSE_dplrnt_Tile(A, *seed); }

void MORSE_DPOSV_TILE(MORSE_enum *uplo, MORSE_desc_t *A, MORSE_desc_t *B, int *info)
{ *info = MORSE_dposv_Tile(*uplo, A, B); }

void MORSE_DPOTRF_TILE(MORSE_enum *uplo, MORSE_desc_t *A, int *info)
{ *info = MORSE_dpotrf_Tile(*uplo, A); }

void MORSE_DPOTRI_TILE(MORSE_enum *uplo, MORSE_desc_t *A, int *info)
{ *info = MORSE_dpotri_Tile(*uplo, A); }

void MORSE_DPOTRS_TILE(MORSE_enum *uplo, MORSE_desc_t *A, MORSE_desc_t *B, int *info)
{ *info = MORSE_dpotrs_Tile(*uplo, A, B); }

#if defined (PRECISION_c) || defined(PRECISION_z)
void MORSE_DSYSV_TILE(MORSE_enum *uplo, MORSE_desc_t *A, MORSE_desc_t *B, int *info)
{ *info = MORSE_dsysv_Tile(*uplo, A, B); }

void MORSE_DSYTRF_TILE(MORSE_enum *uplo, MORSE_desc_t *A, int *info)
{ *info = MORSE_dsytrf_Tile(*uplo, A); }

void MORSE_DSYTRS_TILE(MORSE_enum *uplo, MORSE_desc_t *A, MORSE_desc_t *B, int *info)
{ *info = MORSE_dsytrs_Tile(*uplo, A, B); }
#endif

void MORSE_DSYMM_TILE(MORSE_enum *side, MORSE_enum *uplo, double *alpha, MORSE_desc_t *A, MORSE_desc_t *B, double *beta, MORSE_desc_t *C, int *info)
{ *info = MORSE_dsymm_Tile(*side, *uplo, *alpha, A, B, *beta, C); }

void MORSE_DSYR2K_TILE(MORSE_enum *uplo, MORSE_enum *trans, double *alpha, MORSE_desc_t *A, MORSE_desc_t *B, double *beta, MORSE_desc_t *C, int *info)
{ *info = MORSE_dsyr2k_Tile(*uplo, *trans, *alpha, A, B, *beta, C); }

void MORSE_DSYRK_TILE(MORSE_enum *uplo, MORSE_enum *trans, double *alpha, MORSE_desc_t *A, double *beta, MORSE_desc_t *C, int *info)
{ *info = MORSE_dsyrk_Tile(*uplo, *trans, *alpha, A, *beta, C); }

void MORSE_DTRMM_TILE(MORSE_enum *side, MORSE_enum *uplo, MORSE_enum *transA, MORSE_enum *diag, double *alpha, MORSE_desc_t *A, MORSE_desc_t *B, int *info)
{ *info = MORSE_dtrmm_Tile(*side, *uplo, *transA, *diag, *alpha, A, B); }

void MORSE_DTRSM_TILE(MORSE_enum *side, MORSE_enum *uplo, MORSE_enum *transA, MORSE_enum *diag, double *alpha, MORSE_desc_t *A, MORSE_desc_t *B, int *info)
{ *info = MORSE_dtrsm_Tile(*side, *uplo, *transA, *diag, *alpha, A, B); }

void MORSE_DTRSMPL_TILE(MORSE_desc_t *A, MORSE_desc_t *L, int *IPIV, MORSE_desc_t *B, int *info)
{ *info = MORSE_dtrsmpl_Tile(A, L, IPIV, B); }

//void MORSE_DTRSMRV_TILE(MORSE_enum *side, MORSE_enum *uplo, MORSE_enum *transA, MORSE_enum *diag, double *alpha, MORSE_desc_t *A, MORSE_desc_t *B, int *info)
//{ *info = MORSE_dtrsmrv_Tile(*side, *uplo, *transA, *diag, *alpha, A, B); }

void MORSE_DTRTRI_TILE(MORSE_enum *uplo, MORSE_enum *diag, MORSE_desc_t *A, int *info)
{ *info = MORSE_dtrtri_Tile(*uplo, *diag, A); }

void MORSE_DORGLQ_TILE(MORSE_desc_t *A, MORSE_desc_t *T, MORSE_desc_t *B, int *info)
{ *info = MORSE_dorglq_Tile(A, T, B); }

void MORSE_DORGQR_TILE(MORSE_desc_t *A, MORSE_desc_t *T, MORSE_desc_t *B, int *info)
{ *info = MORSE_dorgqr_Tile(A, T, B); }

void MORSE_DORMLQ_TILE(MORSE_enum *side, MORSE_enum *trans, MORSE_desc_t *A, MORSE_desc_t *T, MORSE_desc_t *B, int *info)
{ *info = MORSE_dormlq_Tile(*side, *trans, A, T, B); }

void MORSE_DORMQR_TILE(MORSE_enum *side, MORSE_enum *trans, MORSE_desc_t *A, MORSE_desc_t *T, MORSE_desc_t *B, int *info)
{ *info = MORSE_dormqr_Tile(*side, *trans, A, T, B); }


/***************************************************************************//**
 *  FORTRAN API - math functions (asynchronous interface)
 **/
//void MORSE_DGEBRD_TILE_ASYNC(MORSE_desc_t *A, double *D, double *E, MORSE_desc_t *T, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
//{ *info = MORSE_dgebrd_Tile_Async(A, D, E, T, sequence, request); }

void MORSE_DGELQF_TILE_ASYNC(MORSE_desc_t *A, MORSE_desc_t *T, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_dgelqf_Tile_Async(A, T, sequence, request); }

void MORSE_DGELQS_TILE_ASYNC(MORSE_desc_t *A, MORSE_desc_t *T, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_dgelqs_Tile_Async(A, T, B, sequence, request); }

void MORSE_DGELS_TILE_ASYNC(MORSE_enum *trans, MORSE_desc_t *A, MORSE_desc_t *T, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_dgels_Tile_Async(*trans, A, T, B, sequence, request); }

void MORSE_DGEMM_TILE_ASYNC(MORSE_enum *transA, MORSE_enum *transB, double *alpha, MORSE_desc_t *A, MORSE_desc_t *B, double *beta, MORSE_desc_t *C, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_dgemm_Tile_Async(*transA, *transB, *alpha, A, B, *beta, C, sequence, request); }

void MORSE_DGEQRF_TILE_ASYNC(MORSE_desc_t *A, MORSE_desc_t *T, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_dgeqrf_Tile_Async(A, T, sequence, request); }

void MORSE_DGEQRS_TILE_ASYNC(MORSE_desc_t *A, MORSE_desc_t *T, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_dgeqrs_Tile_Async(A, T, B, sequence, request); }

//void MORSE_DGESV_TILE_ASYNC(MORSE_desc_t *A, int *IPIV, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
//{ *info = MORSE_dgesv_Tile_Async(A, IPIV, B, sequence, request); }

void MORSE_DGESV_INCPIV_TILE_ASYNC(MORSE_desc_t *A, MORSE_desc_t *L, int *IPIV, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_dgesv_incpiv_Tile_Async(A, L, IPIV, B, sequence, request); }

//void MORSE_DGESV_NOPIV_TILE_ASYNC(MORSE_desc_t *A, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
//{ *info = MORSE_dgesv_nopiv_Tile_Async(A, B, sequence, request); }
//
//void MORSE_DGESVD_TILE_ASYNC(MORSE_enum *jobu, MORSE_enum *jobvt, MORSE_desc_t *A, double *S, MORSE_desc_t *U, MORSE_desc_t *VT, MORSE_desc_t *T, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
//{ *info = MORSE_dgesvd_Tile_Async(*jobu, *jobvt, A, S, U, VT, T, sequence, request); }

//void MORSE_DGETRF_TILE_ASYNC(MORSE_desc_t *A, int *IPIV, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
//{ *info = MORSE_dgetrf_Tile_Async(A, IPIV, sequence, request); }

void MORSE_DGETRF_INCPIV_TILE_ASYNC(MORSE_desc_t *A, MORSE_desc_t *L, int *IPIV, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_dgetrf_incpiv_Tile_Async(A, L, IPIV, sequence, request); }

void MORSE_DGETRF_NOPIV_TILE_ASYNC(MORSE_desc_t *A, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_dgetrf_nopiv_Tile_Async(A, sequence, request); }

//void MORSE_DGETRI_TILE_ASYNC(MORSE_desc_t *A, int *IPIV, MORSE_desc_t *W, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
//{ *info = MORSE_dgetri_Tile_Async(A, IPIV, W, sequence, request); }
//
//void MORSE_DGETRS_TILE_ASYNC(MORSE_enum *trans, MORSE_desc_t *A, int *IPIV, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
//{ *info = MORSE_dgetrs_Tile_Async(*trans, A, IPIV, B, sequence, request); }

void MORSE_DGETRS_INCPIV_TILE_ASYNC(MORSE_desc_t *A, MORSE_desc_t *L, int *IPIV, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_dgetrs_incpiv_Tile_Async(A, L, IPIV, B, sequence, request); }

void MORSE_DGETRS_NOPIV_TILE_ASYNC(MORSE_desc_t *A, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_dgetrs_nopiv_Tile_Async(A, B, sequence, request); }

//void MORSE_DSYEV_TILE_ASYNC(MORSE_enum *jobz, MORSE_enum *uplo, MORSE_desc_t *A, double *W, MORSE_desc_t *T, double *Q, int *LDQ, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
//{ *info = MORSE_dsyev_Tile_Async(*jobz, *uplo, A, W, T, Q, *LDQ, sequence, request); }
//
//void MORSE_DSYEVD_TILE_ASYNC(MORSE_enum *jobz, MORSE_enum *uplo, MORSE_desc_t *A, double *W, MORSE_desc_t *T, double *Q, int *LDQ, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
//{ *info = MORSE_dsyevd_Tile_Async(*jobz, *uplo, A, W, T, Q, *LDQ, sequence, request); }
//
//void MORSE_DSYGST_TILE_ASYNC(MORSE_enum *itype, MORSE_enum *uplo, MORSE_desc_t *A, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
//{ *info = MORSE_dsygst_Tile_Async(*itype, *uplo, A, B, sequence, request); }
//
//void MORSE_DHEGV_TILE_ASYNC(MORSE_enum *itype, MORSE_enum *jobz, MORSE_enum *uplo, MORSE_desc_t *A, MORSE_desc_t *B, double *W, MORSE_desc_t *T, MORSE_desc_t *Q, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
//{ *info = MORSE_dhegv_Tile_Async(*itype, *jobz, *uplo, A, B, W, T, Q, sequence, request); }
//
//void MORSE_DSYGVD_TILE_ASYNC(MORSE_enum *itype, MORSE_enum *jobz, MORSE_enum *uplo, MORSE_desc_t *A, MORSE_desc_t *B, double *W, MORSE_desc_t *T, MORSE_desc_t *Q, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
//{ *info = MORSE_dsygvd_Tile_Async(*itype, *jobz, *uplo, A, B, W, T, Q, sequence, request); }

#ifdef COMPLEX
void MORSE_DSYMM_TILE_ASYNC(MORSE_enum *side, MORSE_enum *uplo, double *alpha, MORSE_desc_t *A, MORSE_desc_t *B, double *beta, MORSE_desc_t *C, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_dsymm_Tile_Async(*side, *uplo, *alpha, A, B, *beta, C, sequence, request); }
#endif

#ifdef COMPLEX
void MORSE_DSYR2K_TILE_ASYNC(MORSE_enum *uplo, MORSE_enum *trans, double *alpha, MORSE_desc_t *A, MORSE_desc_t *B, double *beta, MORSE_desc_t *C, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_dsyr2k_Tile_Async(*uplo, *trans, *alpha, A, B, *beta, C, sequence, request); }
#endif

#ifdef COMPLEX
void MORSE_DSYRK_TILE_ASYNC(MORSE_enum *uplo, MORSE_enum *trans, double *alpha, MORSE_desc_t *A, double *beta, MORSE_desc_t *C, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_dsyrk_Tile_Async(*uplo, *trans, *alpha, A, *beta, C, sequence, request); }
#endif

//void MORSE_DSYTRD_TILE_ASYNC(MORSE_enum *jobz, MORSE_enum *uplo, MORSE_desc_t *A, double *D, double *E, MORSE_desc_t *T, double *Q, int *LDQ, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
//{ *info = MORSE_dsytrd_Tile_Async(*jobz, *uplo, A, D, E, T, Q, *LDQ, sequence, request); }

void MORSE_DLACPY_TILE_ASYNC(MORSE_enum *uplo, MORSE_desc_t *A, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_dlacpy_Tile_Async(*uplo, A, B, sequence, request); }

void MORSE_DLANGE_TILE_ASYNC(MORSE_enum *norm, MORSE_desc_t *A, double *value, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_dlange_Tile_Async(*norm, A, value, sequence, request); }

#ifdef COMPLEX
void MORSE_DLANSY_TILE_ASYNC(MORSE_enum *norm, MORSE_enum *uplo, MORSE_desc_t *A, double *value, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_dlansy_Tile_Async(*norm, *uplo, A, value, sequence, request); }
#endif

void MORSE_DLANSY_TILE_ASYNC(MORSE_enum *norm, MORSE_enum *uplo, MORSE_desc_t *A, double *value, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_dlansy_Tile_Async(*norm, *uplo, A, value, sequence, request); }

void MORSE_DLANTR_TILE_ASYNC(MORSE_enum *norm, MORSE_enum *uplo, MORSE_enum *diag, MORSE_desc_t *A, double *value, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_dlantr_Tile_Async(*norm, *uplo, *diag, A, value, sequence, request); }

void MORSE_DLASET_TILE_ASYNC(MORSE_enum *uplo, double *alpha, double *beta, MORSE_desc_t *A, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_dlaset_Tile_Async(*uplo, *alpha, *beta, A, sequence, request); }

//void MORSE_DLASWP_TILE_ASYNC(MORSE_desc_t *A, int *K1, int *K2, int *IPIV, int *INCX, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
//{ *info = MORSE_dlaswp_Tile_Async(A, *K1, *K2, IPIV, *INCX, sequence, request); }
//
//void MORSE_DLASWPC_TILE_ASYNC(MORSE_desc_t *A, int *K1, int *K2, int *IPIV, int *INCX, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
//{ *info = MORSE_dlaswpc_Tile_Async(A, *K1, *K2, IPIV, *INCX, sequence, request); }

void MORSE_DLAUUM_TILE_ASYNC(MORSE_enum *uplo, MORSE_desc_t *A, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_dlauum_Tile_Async(*uplo, A, sequence, request); }

#ifdef COMPLEX
void MORSE_DPLGSY_TILE_ASYNC(double *bump, MORSE_desc_t *A, unsigned long long int *seed, MORSE_sequence_t *sequence, MORSE_request_t * *request, int *info)
{ *info = MORSE_dplgsy_Tile_Async(*bump, A, *seed, sequence, *request); }
#endif

void MORSE_DPLGSY_TILE_ASYNC(double *bump, MORSE_desc_t *A, unsigned long long int *seed, MORSE_sequence_t *sequence, MORSE_request_t * *request, int *info)
{ *info = MORSE_dplgsy_Tile_Async(*bump, A, *seed, sequence, *request); }

void MORSE_DPLRNT_TILE_ASYNC(MORSE_desc_t *A, unsigned long long int *seed, MORSE_sequence_t *sequence, MORSE_request_t * *request, int *info)
{ *info = MORSE_dplrnt_Tile_Async(A, *seed, sequence, *request); }

void MORSE_DPOSV_TILE_ASYNC(MORSE_enum *uplo, MORSE_desc_t *A, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_dposv_Tile_Async(*uplo, A, B, sequence, request); }

void MORSE_DPOTRF_TILE_ASYNC(MORSE_enum *uplo, MORSE_desc_t *A, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_dpotrf_Tile_Async(*uplo, A, sequence, request); }

void MORSE_DPOTRI_TILE_ASYNC(MORSE_enum *uplo, MORSE_desc_t *A, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_dpotri_Tile_Async(*uplo, A, sequence, request); }

void MORSE_DPOTRS_TILE_ASYNC(MORSE_enum *uplo, MORSE_desc_t *A, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_dpotrs_Tile_Async(*uplo, A, B, sequence, request); }

#if defined (PRECISION_c) || defined(PRECISION_z)
void MORSE_DSYSV_TILE_ASYNC(MORSE_enum *uplo, MORSE_desc_t *A, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_dsysv_Tile_Async(*uplo, A, B, sequence, request); }

void MORSE_DSYTRF_TILE_ASYNC(MORSE_enum *uplo, MORSE_desc_t *A, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_dsytrf_Tile_Async(*uplo, A, sequence, request); }

void MORSE_DSYTRS_TILE_ASYNC(MORSE_enum *uplo, MORSE_desc_t *A, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_dsytrs_Tile_Async(*uplo, A, B, sequence, request); }
#endif

void MORSE_DSYMM_TILE_ASYNC(MORSE_enum *side, MORSE_enum *uplo, double *alpha, MORSE_desc_t *A, MORSE_desc_t *B, double *beta, MORSE_desc_t *C, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_dsymm_Tile_Async(*side, *uplo, *alpha, A, B, *beta, C, sequence, request); }

void MORSE_DSYR2K_TILE_ASYNC(MORSE_enum *uplo, MORSE_enum *trans, double *alpha, MORSE_desc_t *A, MORSE_desc_t *B, double *beta, MORSE_desc_t *C, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_dsyr2k_Tile_Async(*uplo, *trans, *alpha, A, B, *beta, C, sequence, request); }

void MORSE_DSYRK_TILE_ASYNC(MORSE_enum *uplo, MORSE_enum *trans, double *alpha, MORSE_desc_t *A, double *beta, MORSE_desc_t *C, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_dsyrk_Tile_Async(*uplo, *trans, *alpha, A, *beta, C, sequence, request); }

void MORSE_DTRMM_TILE_ASYNC(MORSE_enum *side, MORSE_enum *uplo, MORSE_enum *transA, MORSE_enum *diag, double *alpha, MORSE_desc_t *A, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_dtrmm_Tile_Async(*side, *uplo, *transA, *diag, *alpha, A, B, sequence, request); }

void MORSE_DTRSM_TILE_ASYNC(MORSE_enum *side, MORSE_enum *uplo, MORSE_enum *transA, MORSE_enum *diag, double *alpha, MORSE_desc_t *A, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_dtrsm_Tile_Async(*side, *uplo, *transA, *diag, *alpha, A, B, sequence, request); }

void MORSE_DTRSMPL_TILE_ASYNC(MORSE_desc_t *A, MORSE_desc_t *L, int *IPIV, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_dtrsmpl_Tile_Async(A, L, IPIV, B, sequence, request); }

//void MORSE_DTRSMRV_TILE_ASYNC(MORSE_enum *side, MORSE_enum *uplo, MORSE_enum *transA, MORSE_enum *diag, double *alpha, MORSE_desc_t *A, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
//{ *info = MORSE_dtrsmrv_Tile_Async(*side, *uplo, *transA, *diag, *alpha, A, B, sequence, request); }

void MORSE_DTRTRI_TILE_ASYNC(MORSE_enum *uplo, MORSE_enum *diag, MORSE_desc_t *A, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_dtrtri_Tile_Async(*uplo, *diag, A, sequence, request); }

void MORSE_DORGLQ_TILE_ASYNC(MORSE_desc_t *A, MORSE_desc_t *T, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_dorglq_Tile_Async(A, T, B, sequence, request); }

void MORSE_DORGQR_TILE_ASYNC(MORSE_desc_t *A, MORSE_desc_t *T, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_dorgqr_Tile_Async(A, T, B, sequence, request); }

void MORSE_DORMLQ_TILE_ASYNC(MORSE_enum *side, MORSE_enum *trans, MORSE_desc_t *A, MORSE_desc_t *T, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_dormlq_Tile_Async(*side, *trans, A, T, B, sequence, request); }

void MORSE_DORMQR_TILE_ASYNC(MORSE_enum *side, MORSE_enum *trans, MORSE_desc_t *A, MORSE_desc_t *T, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_dormqr_Tile_Async(*side, *trans, A, T, B, sequence, request); }


/***************************************************************************//**
 *  FORTRAN API - workspace allocation
 **/
//void MORSE_ALLOC_WORKSPACE_DGEBRD(int *M, int *N, MORSE_desc_t **descT, int *info)
//{ *info = MORSE_Alloc_Workspace_dgebrd(*M, *N, descT); }
//
//void MORSE_ALLOC_WORKSPACE_DGEEV(int *N, MORSE_desc_t **descT, int *info)
//{ *info = MORSE_Alloc_Workspace_dgeev(*N, descT); }
//
//void MORSE_ALLOC_WORKSPACE_DGEHRD(int *N, MORSE_desc_t **descT, int *info)
//{ *info = MORSE_Alloc_Workspace_dgehrd(*N, descT); }

void MORSE_ALLOC_WORKSPACE_DGELQF(int *M, int *N, MORSE_desc_t **T, int *info)
{ *info = MORSE_Alloc_Workspace_dgelqf(*M, *N, T); }

void MORSE_ALLOC_WORKSPACE_DGELQF_TILE(int *M, int *N, MORSE_desc_t **descT, int *info)
{ *info = MORSE_Alloc_Workspace_dgelqf_Tile(*M, *N, descT); }

void MORSE_ALLOC_WORKSPACE_DGELS(int *M, int *N, MORSE_desc_t **T, int *info)
{ *info = MORSE_Alloc_Workspace_dgels(*M, *N, T); }

void MORSE_ALLOC_WORKSPACE_DGELS_TILE(int *M, int *N, MORSE_desc_t **descT, int *info)
{ *info = MORSE_Alloc_Workspace_dgels_Tile(*M, *N, descT); }

void MORSE_ALLOC_WORKSPACE_DGEQRF(int *M, int *N, MORSE_desc_t **T, int *info)
{ *info = MORSE_Alloc_Workspace_dgeqrf(*M, *N, T); }

void MORSE_ALLOC_WORKSPACE_DGEQRF_TILE(int *M, int *N, MORSE_desc_t **descT, int *info)
{ *info = MORSE_Alloc_Workspace_dgeqrf_Tile(*M, *N, descT); }

void MORSE_ALLOC_WORKSPACE_DGESV_INCPIV(int *N, MORSE_desc_t **descL, int **IPIV, int *info)
{ *info = MORSE_Alloc_Workspace_dgesv_incpiv(*N, descL, IPIV); }

void MORSE_ALLOC_WORKSPACE_DGESV_INCPIV_TILE (int *N, MORSE_desc_t **descL, int **IPIV, int *info)
{ *info = MORSE_Alloc_Workspace_dgesv_incpiv_Tile (*N, descL, IPIV); }

//void MORSE_ALLOC_WORKSPACE_DGESVD(int *M, int *N, MORSE_desc_t **descT, int *info)
//{ *info = MORSE_Alloc_Workspace_dgesvd(*M, *N, descT); }

void MORSE_ALLOC_WORKSPACE_DGETRF_INCPIV(int *M, int *N, MORSE_desc_t **descL, int **IPIV, int *info)
{ *info = MORSE_Alloc_Workspace_dgetrf_incpiv(*M, *N, descL, IPIV); }

void MORSE_ALLOC_WORKSPACE_DGETRF_INCPIV_TILE(int *N, MORSE_desc_t **descL, int **IPIV, int *info)
{ *info = MORSE_Alloc_Workspace_dgetrf_incpiv_Tile(*N, descL, IPIV); }

//void MORSE_ALLOC_WORKSPACE_DGETRI_TILE_ASYNC(MORSE_desc_t *A, MORSE_desc_t *W, int *info)
//{ *info = MORSE_Alloc_Workspace_dgetri_Tile_Async(A, W); }

//void MORSE_ALLOC_WORKSPACE_DSYEV(int *M, int *N, MORSE_desc_t **descT, int *info)
//{ *info = MORSE_Alloc_Workspace_dsyev(*M, *N, descT); }
//
//void MORSE_ALLOC_WORKSPACE_DSYEVD(int *M, int *N, MORSE_desc_t **descT, int *info)
//{ *info = MORSE_Alloc_Workspace_dsyevd(*M, *N, descT); }
//
//void MORSE_ALLOC_WORKSPACE_ZHEGV(int *M, int *N, MORSE_desc_t **descT, int *info)
//{ *info = MORSE_Alloc_Workspace_dhegv(*M, *N, descT); }
//
//void MORSE_ALLOC_WORKSPACE_DSYGVD(int *M, int *N, MORSE_desc_t **descT, int *info)
//{ *info = MORSE_Alloc_Workspace_dsygvd(*M, *N, descT); }
//
//void MORSE_ALLOC_WORKSPACE_DSYTRD(int *M, int *N, MORSE_desc_t **descT, int *info)
//{ *info = MORSE_Alloc_Workspace_dsytrd(*M, *N, descT); }



