/**
 *
 * @copyright (c) 2009-2014 The University of Tennessee and The University
 *                          of Tennessee Research Foundation.
 *                          All rights reserved.
 * @copyright (c) 2012-2014 Inria. All rights reserved.
 * @copyright (c) 2012-2014 Bordeaux INP, CNRS (LaBRI UMR 5800), Inria, Univ. Bordeaux. All rights reserved.
 *
 **/

/**
 *
 * @file morse_sf77.c
 *
 *  MORSE computational routines
 *  MORSE is a software package provided by Univ. of Tennessee,
 *  Univ. of California Berkeley and Univ. of Colorado Denver
 *  This file is automatically generated by tools/genf77interface.pl
 *
 * @version 2.5.0
 * @comment This file has been automatically generated
 *          from Plasma 2.5.0 for MORSE 1.0.0
 * @author Bilel Hadri
 * @author Mathieu Faverge
 * @author Emmanuel Agullo
 * @author Cedric Castagnede
 * @date 2010-11-15
 * @generated s Tue Sep 26 20:43:09 2017
 *
 **/
#include <stdlib.h>
#include "control/common.h"
#undef COMPLEX
#define REAL


/***************************************************************************//**
 *  FORTRAN API - math functions (simple interface)
 **/
#define MORSE_SLAPACK_TO_TILE MORSE_FNAME(slapack_to_tile, SLAPACK_TO_TILE)
#define MORSE_SLAPACK_TO_TILE_ASYNC MORSE_FNAME(slapack_to_tile_async, SLAPACK_TO_TILE_ASYNC)
#define MORSE_STILE_TO_LAPACK MORSE_FNAME(stile_to_lapack, STILE_TO_LAPACK)
#define MORSE_STILE_TO_LAPACK_ASYNC MORSE_FNAME(stile_to_lapack_async, STILE_TO_LAPACK_ASYNC)
//#define MORSE_SGEBRD          MORSE_FNAME(sgebrd       , SGEBRD       )
//#define MORSE_SGECFI          MORSE_FNAME(sgecfi       , ZGECFI       )
//#define MORSE_SGECFI_ASYNC    MORSE_FNAME(sgecfi_async , ZGECFI_ASYNC )
#define MORSE_SGELQF          MORSE_FNAME(sgelqf       , SGELQF       )
#define MORSE_SGELQS          MORSE_FNAME(sgelqs       , SGELQS       )
#define MORSE_SGELS           MORSE_FNAME(sgels        , SGELS        )
#define MORSE_SGEMM           MORSE_FNAME(sgemm        , SGEMM        )
#define MORSE_SGEQRF          MORSE_FNAME(sgeqrf       , SGEQRF       )
#define MORSE_SGEQRS          MORSE_FNAME(sgeqrs       , SGEQRS       )
//#define MORSE_SGESV           MORSE_FNAME(sgesv        , SGESV        )
#define MORSE_SGESV_INCPIV    MORSE_FNAME(sgesv_incpiv , SGESV_INCPIV )
#define MORSE_SGESV_NOPIV     MORSE_FNAME(sgesv_nopiv  , SGESV_NOPIV )
//#define MORSE_SGESVD          MORSE_FNAME(sgesvd       , SGESVD       )
//#define MORSE_SGETMI          MORSE_FNAME(sgetmi       , ZGETMI       )
//#define MORSE_SGETMI_ASYNC    MORSE_FNAME(sgetmi_async , ZGETMI_ASYNC )
//#define MORSE_SGETRF          MORSE_FNAME(sgetrf       , SGETRF       )
#define MORSE_SGETRF_INCPIV   MORSE_FNAME(sgetrf_incpiv, SGETRF_INCPIV)
#define MORSE_SGETRF_NOPIV    MORSE_FNAME(sgetrf_nopiv , SGETRF_NOPIV)
//#define MORSE_SGETRI          MORSE_FNAME(sgetri       , SGETRI       )
//#define MORSE_SGETRS          MORSE_FNAME(sgetrs       , SGETRS       )
#define MORSE_SGETRS_INCPIV   MORSE_FNAME(sgetrs_incpiv, SGETRS_INCPIV)
#define MORSE_SGETRS_NOPIV    MORSE_FNAME(sgetrs_nopiv , SGETRS_NOPIV)
//#define MORSE_SSYEV           MORSE_FNAME(ssyev        , SSYEV        )
//#define MORSE_SSYEVD          MORSE_FNAME(ssyevd       , SSYEVD       )
//#define MORSE_SSYGST          MORSE_FNAME(ssygst       , SSYGST       )
//#define MORSE_SHEGV           MORSE_FNAME(ssygv        , ZHEGV        )
//#define MORSE_SSYGVD          MORSE_FNAME(ssygvd       , SSYGVD       )
#ifdef COMPLEX
#define MORSE_SSYMM           MORSE_FNAME(ssymm        , SSYMM        )
#endif
#ifdef COMPLEX
#define MORSE_SSYR2K          MORSE_FNAME(ssyr2k       , SSYR2K       )
#endif
#ifdef COMPLEX
#define MORSE_SSYRK           MORSE_FNAME(ssyrk        , SSYRK        )
#endif
//#define MORSE_SSYTRD          MORSE_FNAME(ssytrd       , SSYTRD       )
#define MORSE_SLACPY          MORSE_FNAME(slacpy       , SLACPY       )
#define MORSE_SLANGE          MORSE_FNAME(slange       , SLANGE       )
#ifdef COMPLEX
#define MORSE_SLANSY          MORSE_FNAME(slansy       , SLANSY       )
#endif
#define MORSE_SLANSY          MORSE_FNAME(slansy       , SLANSY       )
#define MORSE_SLANTR          MORSE_FNAME(slantr       , SLANTR       )
#define MORSE_SLASET          MORSE_FNAME(slaset       , SLASET       )
//#define MORSE_SLASWP          MORSE_FNAME(slaswp       , SLASWP       )
//#define MORSE_SLASWPC         MORSE_FNAME(slaswpc      , SLASWPC      )
#define MORSE_SLAUUM          MORSE_FNAME(slauum       , SLAUUM       )
#ifdef COMPLEX
#define MORSE_SPLGSY          MORSE_FNAME(splgsy       , SPLGSY       )
#endif
#define MORSE_SPLGSY          MORSE_FNAME(splgsy       , ZPLGSY       )
#define MORSE_SPLRNT          MORSE_FNAME(splrnt       , ZPLRNT       )
#define MORSE_SPOSV           MORSE_FNAME(sposv        , SPOSV        )
#define MORSE_SPOTRF          MORSE_FNAME(spotrf       , SPOTRF       )
#define MORSE_SPOTRI          MORSE_FNAME(spotri       , SPOTRI       )
#define MORSE_SPOTRS          MORSE_FNAME(spotrs       , SPOTRS       )
#if defined (PRECISION_c) || defined(PRECISION_z)
#define MORSE_SSYSV           MORSE_FNAME(ssysv        , SSYSV        )
#define MORSE_SSYTRF          MORSE_FNAME(ssytrf       , SSYTRF       )
#define MORSE_SSYTRS          MORSE_FNAME(ssytrs       , SSYTRS       )
#endif
#define MORSE_SSYMM           MORSE_FNAME(ssymm        , SSYMM        )
#define MORSE_SSYR2K          MORSE_FNAME(ssyr2k       , SSYR2K       )
#define MORSE_SSYRK           MORSE_FNAME(ssyrk        , SSYRK        )
#define MORSE_STRMM           MORSE_FNAME(strmm        , STRMM        )
#define MORSE_STRSM           MORSE_FNAME(strsm        , STRSM        )
#define MORSE_STRSMPL         MORSE_FNAME(strsmpl      , STRSMPL      )
//#define MORSE_STRSMRV         MORSE_FNAME(strsmrv      , STRSMRV      )
#define MORSE_STRTRI          MORSE_FNAME(strtri       , STRTRI       )
#define MORSE_SORGLQ          MORSE_FNAME(sorglq       , SORGLQ       )
#define MORSE_SORGQR          MORSE_FNAME(sorgqr       , SORGQR       )
#define MORSE_SORMLQ          MORSE_FNAME(sormlq       , SORMLQ       )
#define MORSE_SORMQR          MORSE_FNAME(sormqr       , SORMQR       )

/***************************************************************************//**
 *  FORTRAN API - math functions (native interface)
 **/
//#define MORSE_SGEBRD_TILE          MORSE_TILE_FNAME(sgebrd       , SGEBRD       )
#define MORSE_SGELQF_TILE          MORSE_TILE_FNAME(sgelqf       , SGELQF       )
#define MORSE_SGELQS_TILE          MORSE_TILE_FNAME(sgelqs       , SGELQS       )
#define MORSE_SGELS_TILE           MORSE_TILE_FNAME(sgels        , SGELS        )
#define MORSE_SGEMM_TILE           MORSE_TILE_FNAME(sgemm        , SGEMM        )
#define MORSE_SGEQRF_TILE          MORSE_TILE_FNAME(sgeqrf       , SGEQRF       )
#define MORSE_SGEQRS_TILE          MORSE_TILE_FNAME(sgeqrs       , SGEQRS       )
//#define MORSE_SGESV_TILE           MORSE_TILE_FNAME(sgesv        , SGESV        )
#define MORSE_SGESV_INCPIV_TILE    MORSE_TILE_FNAME(sgesv_incpiv , SGESV_INCPIV )
#define MORSE_SGESV_NOPIV_TILE     MORSE_TILE_FNAME(sgesv_nopiv  , SGESV_NOPIV  )
//#define MORSE_SGESVD_TILE          MORSE_TILE_FNAME(sgesvd       , SGESVD       )
//#define MORSE_SGETRF_TILE          MORSE_TILE_FNAME(sgetrf       , SGETRF       )
#define MORSE_SGETRF_INCPIV_TILE   MORSE_TILE_FNAME(sgetrf_incpiv, SGETRF_INCPIV)
#define MORSE_SGETRF_NOPIV_TILE    MORSE_TILE_FNAME(sgetrf_nopiv , SGETRF_NOPIV )
//#define MORSE_SGETRI_TILE          MORSE_TILE_FNAME(sgetri       , SGETRI       )
//#define MORSE_SGETRS_TILE          MORSE_TILE_FNAME(sgetrs       , SGETRS       )
#define MORSE_SGETRS_INCPIV_TILE   MORSE_TILE_FNAME(sgetrs_incpiv, SGETRS_INCPIV)
#define MORSE_SGETRS_NOPIV_TILE    MORSE_TILE_FNAME(sgetrs_nopiv , SGETRS_NOPIV )
//#define MORSE_SSYEV_TILE           MORSE_TILE_FNAME(ssyev        , SSYEV        )
//#define MORSE_SSYEVD_TILE          MORSE_TILE_FNAME(ssyevd       , SSYEVD       )
//#define MORSE_SSYGST_TILE          MORSE_TILE_FNAME(ssygst       , SSYGST       )
//#define MORSE_SHEGV_TILE           MORSE_TILE_FNAME(ssygv        , ZHEGV        )
//#define MORSE_SSYGVD_TILE          MORSE_TILE_FNAME(ssygvd       , SSYGVD       )
#ifdef COMPLEX
#define MORSE_SSYMM_TILE           MORSE_TILE_FNAME(ssymm        , SSYMM        )
#endif
#ifdef COMPLEX
#define MORSE_SSYR2K_TILE          MORSE_TILE_FNAME(ssyr2k       , SSYR2K       )
#endif
#ifdef COMPLEX
#define MORSE_SSYRK_TILE           MORSE_TILE_FNAME(ssyrk        , SSYRK        )
#endif
//#define MORSE_SSYTRD_TILE          MORSE_TILE_FNAME(ssytrd       , SSYTRD       )
#define MORSE_SLACPY_TILE          MORSE_TILE_FNAME(slacpy       , SLACPY       )
#define MORSE_SLANGE_TILE          MORSE_TILE_FNAME(slange       , SLANGE       )
#ifdef COMPLEX
#define MORSE_SLANSY_TILE          MORSE_TILE_FNAME(slansy       , SLANSY       )
#endif
#define MORSE_SLANSY_TILE          MORSE_TILE_FNAME(slansy       , SLANSY       )
#define MORSE_SLASET_TILE          MORSE_TILE_FNAME(slaset       , SLASET       )
//#define MORSE_SLASWP_TILE          MORSE_TILE_FNAME(slaswp       , SLASWP       )
//#define MORSE_SLASWPC_TILE         MORSE_TILE_FNAME(slaswpc      , SLASWPC      )
#define MORSE_SLAUUM_TILE          MORSE_TILE_FNAME(slauum       , SLAUUM       )
#ifdef COMPLEX
#define MORSE_SPLGSY_TILE          MORSE_TILE_FNAME(splgsy       , SPLGSY       )
#endif
#define MORSE_SPLGSY_TILE          MORSE_TILE_FNAME(splgsy       , ZPLGSY       )
#define MORSE_SPLRNT_TILE          MORSE_TILE_FNAME(splrnt       , ZPLRNT       )
#define MORSE_SPOSV_TILE           MORSE_TILE_FNAME(sposv        , SPOSV        )
#define MORSE_SPOTRF_TILE          MORSE_TILE_FNAME(spotrf       , SPOTRF       )
#define MORSE_SPOTRI_TILE          MORSE_TILE_FNAME(spotri       , SPOTRI       )
#define MORSE_SPOTRS_TILE          MORSE_TILE_FNAME(spotrs       , SPOTRS       )
#if defined (PRECISION_c) || defined(PRECISION_z)
#define MORSE_SSYSV_TILE           MORSE_TILE_FNAME(ssysv        , SSYSV        )
#define MORSE_SSYTRF_TILE          MORSE_TILE_FNAME(ssytrf       , SSYTRF       )
#define MORSE_SSYTRS_TILE          MORSE_TILE_FNAME(ssytrs       , SSYTRS       )
#endif
#define MORSE_SSYMM_TILE           MORSE_TILE_FNAME(ssymm        , SSYMM        )
#define MORSE_SSYR2K_TILE          MORSE_TILE_FNAME(ssyr2k       , SSYR2K       )
#define MORSE_SSYRK_TILE           MORSE_TILE_FNAME(ssyrk        , SSYRK        )
#define MORSE_STRMM_TILE           MORSE_TILE_FNAME(strmm        , STRMM        )
#define MORSE_STRSM_TILE           MORSE_TILE_FNAME(strsm        , STRSM        )
#define MORSE_STRSMPL_TILE         MORSE_TILE_FNAME(strsmpl      , STRSMPL      )
//#define MORSE_STRSMRV_TILE         MORSE_TILE_FNAME(strsmrv      , STRSMRV      )
#define MORSE_STRTRI_TILE          MORSE_TILE_FNAME(strtri       , STRTRI       )
#define MORSE_SORGLQ_TILE          MORSE_TILE_FNAME(sorglq       , SORGLQ       )
#define MORSE_SORGQR_TILE          MORSE_TILE_FNAME(sorgqr       , SORGQR       )
#define MORSE_SORMLQ_TILE          MORSE_TILE_FNAME(sormlq       , SORMLQ       )
#define MORSE_SORMQR_TILE          MORSE_TILE_FNAME(sormqr       , SORMQR       )

/***************************************************************************//**
 *  FORTRAN API - math functions (asynchronous interface)
 **/
//#define MORSE_SGEBRD_TILE_ASYNC          MORSE_ASYNC_FNAME(sgebrd       , SGEBRD       )
#define MORSE_SGELQF_TILE_ASYNC          MORSE_ASYNC_FNAME(sgelqf       , SGELQF       )
#define MORSE_SGELQS_TILE_ASYNC          MORSE_ASYNC_FNAME(sgelqs       , SGELQS       )
#define MORSE_SGELS_TILE_ASYNC           MORSE_ASYNC_FNAME(sgels        , SGELS        )
#define MORSE_SGEMM_TILE_ASYNC           MORSE_ASYNC_FNAME(sgemm        , SGEMM        )
#define MORSE_SGEQRF_TILE_ASYNC          MORSE_ASYNC_FNAME(sgeqrf       , SGEQRF       )
#define MORSE_SGEQRS_TILE_ASYNC          MORSE_ASYNC_FNAME(sgeqrs       , SGEQRS       )
//#define MORSE_SGESV_TILE_ASYNC           MORSE_ASYNC_FNAME(sgesv        , SGESV        )
#define MORSE_SGESV_INCPIV_TILE_ASYNC    MORSE_ASYNC_FNAME(sgesv_incpiv , SGESV_INCPIV )
#define MORSE_SGESV_NOPIV_TILE_ASYNC     MORSE_ASYNC_FNAME(sgesv_nopiv  , SGESV_NOPIV  )
//#define MORSE_SGESVD_TILE_ASYNC          MORSE_ASYNC_FNAME(sgesvd       , SGESVD       )
//#define MORSE_SGETRF_TILE_ASYNC          MORSE_ASYNC_FNAME(sgetrf       , SGETRF       )
#define MORSE_SGETRF_INCPIV_TILE_ASYNC   MORSE_ASYNC_FNAME(sgetrf_incpiv, SGETRF_INCPIV)
#define MORSE_SGETRF_NOPIV_TILE_ASYNC    MORSE_ASYNC_FNAME(sgetrf_nopiv , SGETRF_NOPIV )
//#define MORSE_SGETRI_TILE_ASYNC          MORSE_ASYNC_FNAME(sgetri       , SGETRI       )
//#define MORSE_SGETRS_TILE_ASYNC          MORSE_ASYNC_FNAME(sgetrs       , SGETRS       )
#define MORSE_SGETRS_INCPIV_TILE_ASYNC   MORSE_ASYNC_FNAME(sgetrs_incpiv, SGETRS_INCPIV)
#define MORSE_SGETRS_NOPIV_TILE_ASYNC    MORSE_ASYNC_FNAME(sgetrs_nopiv , SGETRS_NOPIV )
//#define MORSE_SSYEV_TILE_ASYNC           MORSE_ASYNC_FNAME(ssyev        , SSYEV        )
//#define MORSE_SSYEVD_TILE_ASYNC          MORSE_ASYNC_FNAME(ssyevd       , SSYEVD       )
//#define MORSE_SSYGST_TILE_ASYNC          MORSE_ASYNC_FNAME(ssygst       , SSYGST       )
//#define MORSE_SHEGV_TILE_ASYNC           MORSE_ASYNC_FNAME(ssygv        , ZHEGV        )
//#define MORSE_SSYGVD_TILE_ASYNC          MORSE_ASYNC_FNAME(ssygvd       , SSYGVD       )
#ifdef COMPLEX
#define MORSE_SSYMM_TILE_ASYNC           MORSE_ASYNC_FNAME(ssymm        , SSYMM        )
#define MORSE_SSYR2K_TILE_ASYNC          MORSE_ASYNC_FNAME(ssyr2k       , SSYR2K       )
#define MORSE_SSYRK_TILE_ASYNC           MORSE_ASYNC_FNAME(ssyrk        , SSYRK        )
#endif
//#define MORSE_SSYTRD_TILE_ASYNC          MORSE_ASYNC_FNAME(ssytrd       , SSYTRD       )
#define MORSE_SLACPY_TILE_ASYNC          MORSE_ASYNC_FNAME(slacpy       , SLACPY       )
#define MORSE_SLANGE_TILE_ASYNC          MORSE_ASYNC_FNAME(slange       , SLANGE       )
#ifdef COMPLEX
#define MORSE_SLANSY_TILE_ASYNC          MORSE_ASYNC_FNAME(slansy       , SLANSY       )
#endif
#define MORSE_SLANSY_TILE_ASYNC          MORSE_ASYNC_FNAME(slansy       , SLANSY       )
#define MORSE_SLANTR_TILE_ASYNC          MORSE_ASYNC_FNAME(slantr       , SLANTR       )
#define MORSE_SLASET_TILE_ASYNC          MORSE_ASYNC_FNAME(slaset       , SLASET       )
//#define MORSE_SLASWP_TILE_ASYNC          MORSE_ASYNC_FNAME(slaswp       , SLASWP       )
//#define MORSE_SLASWPC_TILE_ASYNC         MORSE_ASYNC_FNAME(slaswpc      , SLASWPC      )
#define MORSE_SLAUUM_TILE_ASYNC          MORSE_ASYNC_FNAME(slauum       , SLAUUM       )
#ifdef COMPLEX
#define MORSE_SPLGSY_TILE_ASYNC          MORSE_ASYNC_FNAME(splgsy       , SPLGSY       )
#endif
#define MORSE_SPLGSY_TILE_ASYNC          MORSE_ASYNC_FNAME(splgsy       , ZPLGSY       )
#define MORSE_SPLRNT_TILE_ASYNC          MORSE_ASYNC_FNAME(splrnt       , ZPLRNT       )
#define MORSE_SPOSV_TILE_ASYNC           MORSE_ASYNC_FNAME(sposv        , SPOSV        )
#define MORSE_SPOTRF_TILE_ASYNC          MORSE_ASYNC_FNAME(spotrf       , SPOTRF       )
#define MORSE_SPOTRI_TILE_ASYNC          MORSE_ASYNC_FNAME(spotri       , SPOTRI       )
#define MORSE_SPOTRS_TILE_ASYNC          MORSE_ASYNC_FNAME(spotrs       , SPOTRS       )
#if defined (PRECISION_c) || defined(PRECISION_z)
#define MORSE_SSYSV_TILE_ASYNC           MORSE_ASYNC_FNAME(ssysv        , SSYSV        )
#define MORSE_SSYTRF_TILE_ASYNC          MORSE_ASYNC_FNAME(ssytrf       , SSYTRF       )
#define MORSE_SSYTRS_TILE_ASYNC          MORSE_ASYNC_FNAME(ssytrs       , SSYTRS       )
#endif
#define MORSE_SSYMM_TILE_ASYNC           MORSE_ASYNC_FNAME(ssymm        , SSYMM        )
#define MORSE_SSYR2K_TILE_ASYNC          MORSE_ASYNC_FNAME(ssyr2k       , SSYR2K       )
#define MORSE_SSYRK_TILE_ASYNC           MORSE_ASYNC_FNAME(ssyrk        , SSYRK        )
#define MORSE_STRMM_TILE_ASYNC           MORSE_ASYNC_FNAME(strmm        , STRMM        )
#define MORSE_STRSM_TILE_ASYNC           MORSE_ASYNC_FNAME(strsm        , STRSM        )
#define MORSE_STRSMPL_TILE_ASYNC         MORSE_ASYNC_FNAME(strsmpl      , STRSMPL      )
//#define MORSE_STRSMRV_TILE_ASYNC         MORSE_ASYNC_FNAME(strsmrv      , STRSMRV      )
#define MORSE_STRTRI_TILE_ASYNC          MORSE_ASYNC_FNAME(strtri       , STRTRI       )
#define MORSE_SORGLQ_TILE_ASYNC          MORSE_ASYNC_FNAME(sorglq       , SORGLQ       )
#define MORSE_SORGQR_TILE_ASYNC          MORSE_ASYNC_FNAME(sorgqr       , SORGQR       )
#define MORSE_SORMLQ_TILE_ASYNC          MORSE_ASYNC_FNAME(sormlq       , SORMLQ       )
#define MORSE_SORMQR_TILE_ASYNC          MORSE_ASYNC_FNAME(sormqr       , SORMQR       )

/***************************************************************************//**
 *  FORTRAN API - workspace allocation
 **/
//#define MORSE_ALLOC_WORKSPACE_SGEBRD              MORSE_WS_FNAME(sgebrd            , SGEBRD            )
//#define MORSE_ALLOC_WORKSPACE_SGEEV               MORSE_WS_FNAME(sgeev             , SGEEV             )
//#define MORSE_ALLOC_WORKSPACE_SGEHRD              MORSE_WS_FNAME(sgehrd            , SGEHRD            )
#define MORSE_ALLOC_WORKSPACE_SGELQF              MORSE_WS_FNAME(sgelqf            , SGELQF            )
#define MORSE_ALLOC_WORKSPACE_SGELQF_TILE         MORSE_WS_FNAME(sgelqf_tile       , SGELQF_TILE       )
#define MORSE_ALLOC_WORKSPACE_SGELS               MORSE_WS_FNAME(sgels             , SGELS             )
#define MORSE_ALLOC_WORKSPACE_SGELS_TILE          MORSE_WS_FNAME(sgels_tile        , SGELS_TILE        )
#define MORSE_ALLOC_WORKSPACE_SGEQRF              MORSE_WS_FNAME(sgeqrf            , SGEQRF            )
#define MORSE_ALLOC_WORKSPACE_SGEQRF_TILE         MORSE_WS_FNAME(sgeqrf_tile       , SGEQRF_TILE       )
#define MORSE_ALLOC_WORKSPACE_SGESV_INCPIV        MORSE_WS_FNAME(sgesv_incpiv      , SGESV_INCPIV      )
#define MORSE_ALLOC_WORKSPACE_SGESV_INCPIV_TILE   MORSE_WS_FNAME(sgesv_incpiv_tile , SGESV_INCPIV_TILE )
//#define MORSE_ALLOC_WORKSPACE_SGESVD              MORSE_WS_FNAME(sgesvd            , SGESVD            )
#define MORSE_ALLOC_WORKSPACE_SGETRF_INCPIV       MORSE_WS_FNAME(sgetrf_incpiv     , SGETRF_INCPIV     )
#define MORSE_ALLOC_WORKSPACE_SGETRF_INCPIV_TILE  MORSE_WS_FNAME(sgetrf_incpiv_tile, SGETRF_INCPIV_TILE)
//#define MORSE_ALLOC_WORKSPACE_SGETRI_TILE_ASYNC   MORSE_WS_FNAME(sgetri_tile_async , SGETRI_TILE_ASYNC )
//#define MORSE_ALLOC_WORKSPACE_SSYEV               MORSE_WS_FNAME(ssyev             , SSYEV             )
//#define MORSE_ALLOC_WORKSPACE_SSYEVD              MORSE_WS_FNAME(ssyevd            , SSYEVD            )
//#define MORSE_ALLOC_WORKSPACE_ZHEGV               MORSE_WS_FNAME(ssygv             , ZHEGV             )
//#define MORSE_ALLOC_WORKSPACE_SSYGVD              MORSE_WS_FNAME(ssygvd            , SSYGVD            )
//#define MORSE_ALLOC_WORKSPACE_SSYTRD              MORSE_WS_FNAME(ssytrd            , SSYTRD            )



/***************************************************************************//**
 *  FORTRAN API - math functions (simple interface)
 **/
void MORSE_SLAPACK_TO_TILE(float *Af77, int *LDA, MORSE_desc_t *A, int *info)
{ *info = MORSE_sLapack_to_Tile(Af77, *LDA, A); }

void MORSE_SLAPACK_TO_TILE_ASYNC(float *Af77, int *LDA, MORSE_desc_t *A, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_sLapack_to_Tile_Async(Af77, *LDA, A, sequence, request); }

void MORSE_STILE_TO_LAPACK(MORSE_desc_t *A, float *Af77, int *LDA, int *info)
{ *info = MORSE_sTile_to_Lapack(A, Af77, *LDA); }

void MORSE_STILE_TO_LAPACK_ASYNC(MORSE_desc_t *A, float *Af77, int *LDA, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_sTile_to_Lapack_Async(A, Af77, *LDA, sequence, request); }

//void MORSE_SGEBRD(int *M, int *N, float *A, int *LDA, float *D, float *E, MORSE_desc_t **descT, int *info)
//{ *info = MORSE_sgebrd(*M, *N, A, *LDA, D, E, *descT); }
//
//void MORSE_SGECFI(int *m, int *n, float *A, MORSE_enum *fin, int *imb, int *inb, MORSE_enum *fout, int *omb, int *onb, int *info)
//{ *info = MORSE_sgecfi(*m, *n, A, *fin, *imb, *inb, *fout, *omb, *onb); }
//
//void MORSE_SGECFI_ASYNC(int *m, int *n, float *A, MORSE_enum *f_in, int *imb, int *inb, MORSE_enum *f_out, int *omb, int *onb, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
//{ *info = MORSE_sgecfi_Async(*m, *n, A, *f_in, *imb, *inb, *f_out, *omb, *onb, sequence, request); }

void MORSE_SGELQF(int *M, int *N, float *A, int *LDA, MORSE_desc_t **descT, int *info)
{ *info = MORSE_sgelqf(*M, *N, A, *LDA, *descT); }

void MORSE_SGELQS(int *M, int *N, int *NRHS, float *A, int *LDA, MORSE_desc_t **descT, float *B, int *LDB, int *info)
{ *info = MORSE_sgelqs(*M, *N, *NRHS, A, *LDA, *descT, B, *LDB); }

void MORSE_SGELS(MORSE_enum *trans, int *M, int *N, int *NRHS, float *A, int *LDA, MORSE_desc_t **descT, float *B, int *LDB, int *info)
{ *info = MORSE_sgels(*trans, *M, *N, *NRHS, A, *LDA, *descT, B, *LDB); }

void MORSE_SGEMM(MORSE_enum *transA, MORSE_enum *transB, int *M, int *N, int *K, float *alpha, float *A, int *LDA, float *B, int *LDB, float *beta, float *C, int *LDC, int *info)
{ *info = MORSE_sgemm(*transA, *transB, *M, *N, *K, *alpha, A, *LDA, B, *LDB, *beta, C, *LDC); }

void MORSE_SGEQRF(int *M, int *N, float *A, int *LDA, MORSE_desc_t **descT, int *info)
{ *info = MORSE_sgeqrf(*M, *N, A, *LDA, *descT); }

void MORSE_SGEQRS(int *M, int *N, int *NRHS, float *A, int *LDA, MORSE_desc_t **descT, float *B, int *LDB, int *info)
{ *info = MORSE_sgeqrs(*M, *N, *NRHS, A, *LDA, *descT, B, *LDB); }

//void MORSE_SGESV(int *N, int *NRHS, float *A, int *LDA, int *IPIV, float *B, int *LDB, int *info)
//{ *info = MORSE_sgesv(*N, *NRHS, A, *LDA, IPIV, B, *LDB); }

void MORSE_SGESV_INCPIV(int *N, int *NRHS, float *A, int *LDA, MORSE_desc_t **descL, int *IPIV, float *B, int *LDB, int *info)
{ *info = MORSE_sgesv_incpiv(*N, *NRHS, A, *LDA, *descL, IPIV, B, *LDB); }

void MORSE_SGESV_NOPIV(int *N, int *NRHS, float *A, int *LDA, float *B, int *LDB, int *info)
{ *info = MORSE_sgesv_nopiv(*N, *NRHS, A, *LDA, B, *LDB); }

//void MORSE_SGESVD(MORSE_enum *jobu, MORSE_enum *jobvt, int *M, int *N, float *A, int *LDA, float *S, float *U, int *LDU, float *VT, int *LDVT, MORSE_desc_t **descT, int *info)
//{ *info = MORSE_sgesvd(*jobu, *jobvt, *M, *N, A, *LDA, S, U, *LDU, VT, *LDVT, *descT); }

//void MORSE_SGETMI(int *m, int *n, float *A, MORSE_enum *fin, int *mb, int *nb, int *info)
//{ *info = MORSE_sgetmi(*m, *n, A, *fin, *mb, *nb); }
//
//void MORSE_SGETMI_ASYNC(int *m, int *n, float *A, MORSE_enum *f_in, int *mb, int *inb, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
//{ *info = MORSE_sgetmi_Async(*m, *n, A, *f_in, *mb, *inb, sequence, request); }
//
//void MORSE_SGETRF(int *M, int *N, float *A, int *LDA, int *IPIV, int *info)
//{ *info = MORSE_sgetrf(*M, *N, A, *LDA, IPIV); }

void MORSE_SGETRF_INCPIV(int *M, int *N, float *A, int *LDA, MORSE_desc_t **descL, int *IPIV, int *info)
{ *info = MORSE_sgetrf_incpiv(*M, *N, A, *LDA, *descL, IPIV); }

void MORSE_SGETRF_NOPIV(int *M, int *N, float *A, int *LDA, int *info)
{ *info = MORSE_sgetrf_nopiv(*M, *N, A, *LDA); }

//void MORSE_SGETRI(int *N, float *A, int *LDA, int *IPIV, int *info)
//{ *info = MORSE_sgetri(*N, A, *LDA, IPIV); }
//
//void MORSE_SGETRS(MORSE_enum *trans, int *N, int *NRHS, float *A, int *LDA, int *IPIV, float *B, int *LDB, int *info)
//{ *info = MORSE_sgetrs(*trans, *N, *NRHS, A, *LDA, IPIV, B, *LDB); }

void MORSE_SGETRS_INCPIV(MORSE_enum *trans, int *N, int *NRHS, float *A, int *LDA, MORSE_desc_t **descL, int *IPIV, float *B, int *LDB, int *info)
{ *info = MORSE_sgetrs_incpiv(*trans, *N, *NRHS, A, *LDA, *descL, IPIV, B, *LDB); }

void MORSE_SGETRS_NOPIV(MORSE_enum *trans, int *N, int *NRHS, float *A, int *LDA, float *B, int *LDB, int *info)
{ *info = MORSE_sgetrs_nopiv(*trans, *N, *NRHS, A, *LDA, B, *LDB); }

//void MORSE_SSYEV(MORSE_enum *jobz, MORSE_enum *uplo, int *N, float *A, int *LDA, float *W, MORSE_desc_t **descT, float *Q, int *LDQ, int *info)
//{ *info = MORSE_ssyev(*jobz, *uplo, *N, A, *LDA, W, *descT, Q, *LDQ); }
//
//void MORSE_SSYEVD(MORSE_enum *jobz, MORSE_enum *uplo, int *N, float *A, int *LDA, float *W, MORSE_desc_t **descT, float *Q, int *LDQ, int *info)
//{ *info = MORSE_ssyevd(*jobz, *uplo, *N, A, *LDA, W, *descT, Q, *LDQ); }
//
//void MORSE_SSYGST(MORSE_enum *itype, MORSE_enum *uplo, int *N, float *A, int *LDA, float *B, int *LDB, int *info)
//{ *info = MORSE_ssygst(*itype, *uplo, *N, A, *LDA, B, *LDB); }
//
//void MORSE_SHEGV(MORSE_enum *itype, MORSE_enum *jobz, MORSE_enum *uplo, int *N, float *A, int *LDA, float *B, int *LDB, float *W, MORSE_desc_t **descT, float *Q, int *LDQ, int *info)
//{ *info = MORSE_shegv(*itype, *jobz, *uplo, *N, A, *LDA, B, *LDB, W, *descT, Q, *LDQ); }
//
//void MORSE_SSYGVD(MORSE_enum *itype, MORSE_enum *jobz, MORSE_enum *uplo, int *N, float *A, int *LDA, float *B, int *LDB, float *W, MORSE_desc_t **descT, float *Q, int *LDQ, int *info)
//{ *info = MORSE_ssygvd(*itype, *jobz, *uplo, *N, A, *LDA, B, *LDB, W, *descT, Q, *LDQ); }

#ifdef COMPLEX
void MORSE_SSYMM(MORSE_enum *side, MORSE_enum *uplo, int *M, int *N, float *alpha, float *A, int *LDA, float *B, int *LDB, float *beta, float *C, int *LDC, int *info)
{ *info = MORSE_ssymm(*side, *uplo, *M, *N, *alpha, A, *LDA, B, *LDB, *beta, C, *LDC); }
#endif

#ifdef COMPLEX
void MORSE_SSYR2K(MORSE_enum *uplo, MORSE_enum *trans, int *N, int *K, float *alpha, float *A, int *LDA, float *B, int *LDB, float *beta, float *C, int *LDC, int *info)
{ *info = MORSE_ssyr2k(*uplo, *trans, *N, *K, *alpha, A, *LDA, B, *LDB, *beta, C, *LDC); }
#endif

#ifdef COMPLEX
void MORSE_SSYRK(MORSE_enum *uplo, MORSE_enum *trans, int *N, int *K, float *alpha, float *A, int *LDA, float *beta, float *C, int *LDC, int *info)
{ *info = MORSE_ssyrk(*uplo, *trans, *N, *K, *alpha, A, *LDA, *beta, C, *LDC); }
#endif

//void MORSE_SSYTRD(MORSE_enum *jobz, MORSE_enum *uplo, int *N, float *A, int *LDA, float *D, float *E, MORSE_desc_t **descT, float *Q, int *LDQ, int *info)
//{ *info = MORSE_ssytrd(*jobz, *uplo, *N, A, *LDA, D, E, *descT, Q, *LDQ); }

void MORSE_SLACPY(MORSE_enum *uplo, int *M, int *N, float *A, int *LDA, float *B, int *LDB, int *info)
{ *info = MORSE_slacpy(*uplo, *M, *N, A, *LDA, B, *LDB); }

void MORSE_SLANGE(MORSE_enum *norm, int *M, int *N, float *A, int *LDA, float *result)
{ *result = MORSE_slange(*norm, *M, *N, A, *LDA); }

#ifdef COMPLEX
void MORSE_SLANSY(MORSE_enum *norm, MORSE_enum *uplo, int *N, float *A, int *LDA, float *result)
{ *result = MORSE_slansy(*norm, *uplo, *N, A, *LDA); }
#endif

void MORSE_SLANSY(MORSE_enum *norm, MORSE_enum *uplo, int *N, float *A, int *LDA, float *result)
{ *result = MORSE_slansy(*norm, *uplo, *N, A, *LDA); }

void MORSE_SLANTR(MORSE_enum *norm, MORSE_enum *uplo, MORSE_enum *diag, int *M, int *N, float *A, int *LDA, float *result)
{ *result = MORSE_slantr(*norm, *uplo, *diag, *M, *N, A, *LDA); }

void MORSE_SLASET(MORSE_enum *uplo, int *M, int *N, float *alpha, float *beta, float *A, int *LDA, int *info)
{ *info = MORSE_slaset(*uplo, *M, *N, *alpha, *beta, A, *LDA); }

//void MORSE_SLASWP(int *N, float *A, int *LDA, int *K1, int *K2, int *IPIV, int *INCX, int *info)
//{ *info = MORSE_slaswp(*N, A, *LDA, *K1, *K2, IPIV, *INCX); }
//
//void MORSE_SLASWPC(int *N, float *A, int *LDA, int *K1, int *K2, int *IPIV, int *INCX, int *info)
//{ *info = MORSE_slaswpc(*N, A, *LDA, *K1, *K2, IPIV, *INCX); }

void MORSE_SLAUUM(MORSE_enum *uplo, int *N, float *A, int *LDA, int *info)
{ *info = MORSE_slauum(*uplo, *N, A, *LDA); }

#ifdef COMPLEX
void MORSE_SPLGSY(float *bump, int *N, float *A, int *LDA, unsigned long long int  *seed, int *info)
{ *info = MORSE_splgsy(*bump, *N, A, *LDA, *seed); }
#endif

void MORSE_SPLGSY(float *bump, int *N, float *A, int *LDA, unsigned long long int  *seed, int *info)
{ *info = MORSE_splgsy(*bump, *N, A, *LDA, *seed); }

void MORSE_SPLRNT(int *M, int *N, float *A, int *LDA, unsigned long long int  *seed, int *info)
{ *info = MORSE_splrnt(*M, *N, A, *LDA, *seed); }

void MORSE_SPOSV(MORSE_enum *uplo, int *N, int *NRHS, float *A, int *LDA, float *B, int *LDB, int *info)
{ *info = MORSE_sposv(*uplo, *N, *NRHS, A, *LDA, B, *LDB); }

void MORSE_SPOTRF(MORSE_enum *uplo, int *N, float *A, int *LDA, int *info)
{ *info = MORSE_spotrf(*uplo, *N, A, *LDA); }

void MORSE_SPOTRI(MORSE_enum *uplo, int *N, float *A, int *LDA, int *info)
{ *info = MORSE_spotri(*uplo, *N, A, *LDA); }

void MORSE_SPOTRS(MORSE_enum *uplo, int *N, int *NRHS, float *A, int *LDA, float *B, int *LDB, int *info)
{ *info = MORSE_spotrs(*uplo, *N, *NRHS, A, *LDA, B, *LDB); }

#if defined (PRECISION_c) || defined(PRECISION_z)
void MORSE_SSYSV(MORSE_enum *uplo, int *N, int *NRHS, float *A, int *LDA, float *B, int *LDB, int *info)
{ *info = MORSE_ssysv(*uplo, *N, *NRHS, A, *LDA, B, *LDB); }

void MORSE_SSYTRF(MORSE_enum *uplo, int *N, float *A, int *LDA, int *info)
{ *info = MORSE_ssytrf(*uplo, *N, A, *LDA); }

void MORSE_SSYTRS(MORSE_enum *uplo, int *N, int *NRHS, float *A, int *LDA, float *B, int *LDB, int *info)
{ *info = MORSE_ssytrs(*uplo, *N, *NRHS, A, *LDA, B, *LDB); }
#endif

void MORSE_SSYMM(MORSE_enum *side, MORSE_enum *uplo, int *M, int *N, float *alpha, float *A, int *LDA, float *B, int *LDB, float *beta, float *C, int *LDC, int *info)
{ *info = MORSE_ssymm(*side, *uplo, *M, *N, *alpha, A, *LDA, B, *LDB, *beta, C, *LDC); }

void MORSE_SSYR2K(MORSE_enum *uplo, MORSE_enum *trans, int *N, int *K, float *alpha, float *A, int *LDA, float *B, int *LDB, float *beta, float *C, int *LDC, int *info)
{ *info = MORSE_ssyr2k(*uplo, *trans, *N, *K, *alpha, A, *LDA, B, *LDB, *beta, C, *LDC); }

void MORSE_SSYRK(MORSE_enum *uplo, MORSE_enum *trans, int *N, int *K, float *alpha, float *A, int *LDA, float *beta, float *C, int *LDC, int *info)
{ *info = MORSE_ssyrk(*uplo, *trans, *N, *K, *alpha, A, *LDA, *beta, C, *LDC); }

void MORSE_STRMM(MORSE_enum *side, MORSE_enum *uplo, MORSE_enum *transA, MORSE_enum *diag, int *N, int *NRHS, float *alpha, float *A, int *LDA, float *B, int *LDB, int *info)
{ *info = MORSE_strmm(*side, *uplo, *transA, *diag, *N, *NRHS, *alpha, A, *LDA, B, *LDB); }

void MORSE_STRSM(MORSE_enum *side, MORSE_enum *uplo, MORSE_enum *transA, MORSE_enum *diag, int *N, int *NRHS, float *alpha, float *A, int *LDA, float *B, int *LDB, int *info)
{ *info = MORSE_strsm(*side, *uplo, *transA, *diag, *N, *NRHS, *alpha, A, *LDA, B, *LDB); }

void MORSE_STRSMPL(int *N, int *NRHS, float *A, int *LDA, MORSE_desc_t **descL, int *IPIV, float *B, int *LDB, int *info)
{ *info = MORSE_strsmpl(*N, *NRHS, A, *LDA, *descL, IPIV, B, *LDB); }

//void MORSE_STRSMRV(MORSE_enum *side, MORSE_enum *uplo, MORSE_enum *transA, MORSE_enum *diag, int *N, int *NRHS, float *alpha, float *A, int *LDA, float *B, int *LDB, int *info)
//{ *info = MORSE_strsmrv(*side, *uplo, *transA, *diag, *N, *NRHS, *alpha, A, *LDA, B, *LDB); }

void MORSE_STRTRI(MORSE_enum *uplo, MORSE_enum *diag, int *N, float *A, int *LDA, int *info)
{ *info = MORSE_strtri(*uplo, *diag, *N, A, *LDA); }

void MORSE_SORGLQ(int *M, int *N, int *K, float *A, int *LDA, MORSE_desc_t **descT, float *B, int *LDB, int *info)
{ *info = MORSE_sorglq(*M, *N, *K, A, *LDA, *descT, B, *LDB); }

void MORSE_SORGQR(int *M, int *N, int *K, float *A, int *LDA, MORSE_desc_t **descT, float *B, int *LDB, int *info)
{ *info = MORSE_sorgqr(*M, *N, *K, A, *LDA, *descT, B, *LDB); }

void MORSE_SORMLQ(MORSE_enum *side, MORSE_enum *trans, int *M, int *N, int *K, float *A, int *LDA, MORSE_desc_t **descT, float *B, int *LDB, int *info)
{ *info = MORSE_sormlq(*side, *trans, *M, *N, *K, A, *LDA, *descT, B, *LDB); }

void MORSE_SORMQR(MORSE_enum *side, MORSE_enum *trans, int *M, int *N, int *K, float *A, int *LDA, MORSE_desc_t **descT, float *B, int *LDB, int *info)
{ *info = MORSE_sormqr(*side, *trans, *M, *N, *K, A, *LDA, *descT, B, *LDB); }


/***************************************************************************//**
 *  FORTRAN API - math functions (native interface)
 **/
//void MORSE_SGEBRD_TILE(MORSE_desc_t *A, float *D, float *E, MORSE_desc_t *T, int *info)
//{ *info = MORSE_sgebrd_Tile(A, D, E, T); }

void MORSE_SGELQF_TILE(MORSE_desc_t *A, MORSE_desc_t *T, int *info)
{ *info = MORSE_sgelqf_Tile(A, T); }

void MORSE_SGELQS_TILE(MORSE_desc_t *A, MORSE_desc_t *T, MORSE_desc_t *B, int *info)
{ *info = MORSE_sgelqs_Tile(A, T, B); }

void MORSE_SGELS_TILE(MORSE_enum *trans, MORSE_desc_t *A, MORSE_desc_t *T, MORSE_desc_t *B, int *info)
{ *info = MORSE_sgels_Tile(*trans, A, T, B); }

void MORSE_SGEMM_TILE(MORSE_enum *transA, MORSE_enum *transB, float *alpha, MORSE_desc_t *A, MORSE_desc_t *B, float *beta, MORSE_desc_t *C, int *info)
{ *info = MORSE_sgemm_Tile(*transA, *transB, *alpha, A, B, *beta, C); }

void MORSE_SGEQRF_TILE(MORSE_desc_t *A, MORSE_desc_t *T, int *info)
{ *info = MORSE_sgeqrf_Tile(A, T); }

void MORSE_SGEQRS_TILE(MORSE_desc_t *A, MORSE_desc_t *T, MORSE_desc_t *B, int *info)
{ *info = MORSE_sgeqrs_Tile(A, T, B); }

//void MORSE_SGESV_TILE(MORSE_desc_t *A, int *IPIV, MORSE_desc_t *B, int *info)
//{ *info = MORSE_sgesv_Tile(A, IPIV, B); }

void MORSE_SGESV_INCPIV_TILE(MORSE_desc_t *A, MORSE_desc_t *L, int *IPIV, MORSE_desc_t *B, int *info)
{ *info = MORSE_sgesv_incpiv_Tile(A, L, IPIV, B); }

void MORSE_SGESV_NOPIV_TILE(MORSE_desc_t *A, MORSE_desc_t *B, int *info)
{ *info = MORSE_sgesv_nopiv_Tile(A, B); }

//void MORSE_SGESVD_TILE(MORSE_enum *jobu, MORSE_enum *jobvt, MORSE_desc_t *A, float *S, MORSE_desc_t *U, MORSE_desc_t *VT, MORSE_desc_t *T, int *info)
//{ *info = MORSE_sgesvd_Tile(*jobu, *jobvt, A, S, U, VT, T); }

//void MORSE_SGETRF_TILE(MORSE_desc_t *A, int *IPIV, int *info)
//{ *info = MORSE_sgetrf_Tile(A, IPIV); }

void MORSE_SGETRF_INCPIV_TILE(MORSE_desc_t *A, MORSE_desc_t *L, int *IPIV, int *info)
{ *info = MORSE_sgetrf_incpiv_Tile(A, L, IPIV); }

void MORSE_SGETRF_NOPIV_TILE(MORSE_desc_t *A, int *info)
{ *info = MORSE_sgetrf_nopiv_Tile(A); }

//void MORSE_SGETRI_TILE(MORSE_desc_t *A, int *IPIV, int *info)
//{ *info = MORSE_sgetri_Tile(A, IPIV); }
//
//void MORSE_SGETRS_TILE(MORSE_enum *trans, MORSE_desc_t *A, int *IPIV, MORSE_desc_t *B, int *info)
//{ *info = MORSE_sgetrs_Tile(*trans, A, IPIV, B); }

void MORSE_SGETRS_INCPIV_TILE(MORSE_desc_t *A, MORSE_desc_t *L, int *IPIV, MORSE_desc_t *B, int *info)
{ *info = MORSE_sgetrs_incpiv_Tile(A, L, IPIV, B); }

void MORSE_SGETRS_NOPIV_TILE(MORSE_desc_t *A, MORSE_desc_t *B, int *info)
{ *info = MORSE_sgetrs_nopiv_Tile(A, B); }

//void MORSE_SSYEV_TILE(MORSE_enum *jobz, MORSE_enum *uplo, MORSE_desc_t *A, float *W, MORSE_desc_t *T, float *Q, int *LDQ, int *info)
//{ *info = MORSE_ssyev_Tile(*jobz, *uplo, A, W, T, Q, *LDQ); }
//
//void MORSE_SSYEVD_TILE(MORSE_enum *jobz, MORSE_enum *uplo, MORSE_desc_t *A, float *W, MORSE_desc_t *T, float *Q, int *LDQ, int *info)
//{ *info = MORSE_ssyevd_Tile(*jobz, *uplo, A, W, T, Q, *LDQ); }
//
//void MORSE_SSYGST_TILE(MORSE_enum *itype, MORSE_enum *uplo, MORSE_desc_t *A, MORSE_desc_t *B, int *info)
//{ *info = MORSE_ssygst_Tile(*itype, *uplo, A, B); }
//
//void MORSE_SHEGV_TILE(MORSE_enum *itype, MORSE_enum *jobz, MORSE_enum *uplo, MORSE_desc_t *A, MORSE_desc_t *B, float *W, MORSE_desc_t *T, MORSE_desc_t *Q, int *info)
//{ *info = MORSE_shegv_Tile(*itype, *jobz, *uplo, A, B, W, T, Q); }
//
//void MORSE_SSYGVD_TILE(MORSE_enum *itype, MORSE_enum *jobz, MORSE_enum *uplo, MORSE_desc_t *A, MORSE_desc_t *B, float *W, MORSE_desc_t *T, MORSE_desc_t *Q, int *info)
//{ *info = MORSE_ssygvd_Tile(*itype, *jobz, *uplo, A, B, W, T, Q); }

#ifdef COMPLEX
void MORSE_SSYMM_TILE(MORSE_enum *side, MORSE_enum *uplo, float *alpha, MORSE_desc_t *A, MORSE_desc_t *B, float *beta, MORSE_desc_t *C, int *info)
{ *info = MORSE_ssymm_Tile(*side, *uplo, *alpha, A, B, *beta, C); }
#endif

#ifdef COMPLEX
void MORSE_SSYR2K_TILE(MORSE_enum *uplo, MORSE_enum *trans, float *alpha, MORSE_desc_t *A, MORSE_desc_t *B, float *beta, MORSE_desc_t *C, int *info)
{ *info = MORSE_ssyr2k_Tile(*uplo, *trans, *alpha, A, B, *beta, C); }
#endif

#ifdef COMPLEX
void MORSE_SSYRK_TILE(MORSE_enum *uplo, MORSE_enum *trans, float *alpha, MORSE_desc_t *A, float *beta, MORSE_desc_t *C, int *info)
{ *info = MORSE_ssyrk_Tile(*uplo, *trans, *alpha, A, *beta, C); }
#endif

//void MORSE_SSYTRD_TILE(MORSE_enum *jobz, MORSE_enum *uplo, MORSE_desc_t *A, float *D, float *E, MORSE_desc_t *T, float *Q, int *LDQ, int *info)
//{ *info = MORSE_ssytrd_Tile(*jobz, *uplo, A, D, E, T, Q, *LDQ); }

void MORSE_SLACPY_TILE(MORSE_enum *uplo, MORSE_desc_t *A, MORSE_desc_t *B, int *info)
{ *info = MORSE_slacpy_Tile(*uplo, A, B); }

void MORSE_SLANGE_TILE(MORSE_enum *norm, MORSE_desc_t *A, float *result)
{ *result = MORSE_slange_Tile(*norm, A); }

#ifdef COMPLEX
void MORSE_SLANSY_TILE(MORSE_enum *norm, MORSE_enum *uplo, MORSE_desc_t *A, float *result)
{ *result = MORSE_slansy_Tile(*norm, *uplo, A); }
#endif

void MORSE_SLANSY_TILE(MORSE_enum *norm, MORSE_enum *uplo, MORSE_desc_t *A, float *result)
{ *result = MORSE_slansy_Tile(*norm, *uplo, A); }

void MORSE_SLANTR_TILE(MORSE_enum *norm, MORSE_enum *uplo, MORSE_enum *diag, MORSE_desc_t *A, float *result)
{ *result = MORSE_slantr_Tile(*norm, *uplo, *diag, A); }

void MORSE_SLASET_TILE(MORSE_enum *uplo, float *alpha, float *beta, MORSE_desc_t *A, int *info)
{ *info = MORSE_slaset_Tile(*uplo, *alpha, *beta, A); }

//void MORSE_SLASWP_TILE(MORSE_desc_t *A, int *K1, int *K2, int *IPIV, int *INCX, int *info)
//{ *info = MORSE_slaswp_Tile(A, *K1, *K2, IPIV, *INCX); }
//
//void MORSE_SLASWPC_TILE(MORSE_desc_t *A, int *K1, int *K2, int *IPIV, int *INCX, int *info)
//{ *info = MORSE_slaswpc_Tile(A, *K1, *K2, IPIV, *INCX); }

void MORSE_SLAUUM_TILE(MORSE_enum *uplo, MORSE_desc_t *A, int *info)
{ *info = MORSE_slauum_Tile(*uplo, A); }

#ifdef COMPLEX
void MORSE_SPLGSY_TILE(float *bump, MORSE_desc_t *A, unsigned long long int  *seed, int *info)
{ *info = MORSE_splgsy_Tile(*bump, A, *seed); }
#endif

void MORSE_SPLGSY_TILE(float *bump, MORSE_desc_t *A, unsigned long long int  *seed, int *info)
{ *info = MORSE_splgsy_Tile(*bump, A, *seed); }

void MORSE_SPLRNT_TILE(MORSE_desc_t *A, unsigned long long int  *seed, int *info)
{ *info = MORSE_splrnt_Tile(A, *seed); }

void MORSE_SPOSV_TILE(MORSE_enum *uplo, MORSE_desc_t *A, MORSE_desc_t *B, int *info)
{ *info = MORSE_sposv_Tile(*uplo, A, B); }

void MORSE_SPOTRF_TILE(MORSE_enum *uplo, MORSE_desc_t *A, int *info)
{ *info = MORSE_spotrf_Tile(*uplo, A); }

void MORSE_SPOTRI_TILE(MORSE_enum *uplo, MORSE_desc_t *A, int *info)
{ *info = MORSE_spotri_Tile(*uplo, A); }

void MORSE_SPOTRS_TILE(MORSE_enum *uplo, MORSE_desc_t *A, MORSE_desc_t *B, int *info)
{ *info = MORSE_spotrs_Tile(*uplo, A, B); }

#if defined (PRECISION_c) || defined(PRECISION_z)
void MORSE_SSYSV_TILE(MORSE_enum *uplo, MORSE_desc_t *A, MORSE_desc_t *B, int *info)
{ *info = MORSE_ssysv_Tile(*uplo, A, B); }

void MORSE_SSYTRF_TILE(MORSE_enum *uplo, MORSE_desc_t *A, int *info)
{ *info = MORSE_ssytrf_Tile(*uplo, A); }

void MORSE_SSYTRS_TILE(MORSE_enum *uplo, MORSE_desc_t *A, MORSE_desc_t *B, int *info)
{ *info = MORSE_ssytrs_Tile(*uplo, A, B); }
#endif

void MORSE_SSYMM_TILE(MORSE_enum *side, MORSE_enum *uplo, float *alpha, MORSE_desc_t *A, MORSE_desc_t *B, float *beta, MORSE_desc_t *C, int *info)
{ *info = MORSE_ssymm_Tile(*side, *uplo, *alpha, A, B, *beta, C); }

void MORSE_SSYR2K_TILE(MORSE_enum *uplo, MORSE_enum *trans, float *alpha, MORSE_desc_t *A, MORSE_desc_t *B, float *beta, MORSE_desc_t *C, int *info)
{ *info = MORSE_ssyr2k_Tile(*uplo, *trans, *alpha, A, B, *beta, C); }

void MORSE_SSYRK_TILE(MORSE_enum *uplo, MORSE_enum *trans, float *alpha, MORSE_desc_t *A, float *beta, MORSE_desc_t *C, int *info)
{ *info = MORSE_ssyrk_Tile(*uplo, *trans, *alpha, A, *beta, C); }

void MORSE_STRMM_TILE(MORSE_enum *side, MORSE_enum *uplo, MORSE_enum *transA, MORSE_enum *diag, float *alpha, MORSE_desc_t *A, MORSE_desc_t *B, int *info)
{ *info = MORSE_strmm_Tile(*side, *uplo, *transA, *diag, *alpha, A, B); }

void MORSE_STRSM_TILE(MORSE_enum *side, MORSE_enum *uplo, MORSE_enum *transA, MORSE_enum *diag, float *alpha, MORSE_desc_t *A, MORSE_desc_t *B, int *info)
{ *info = MORSE_strsm_Tile(*side, *uplo, *transA, *diag, *alpha, A, B); }

void MORSE_STRSMPL_TILE(MORSE_desc_t *A, MORSE_desc_t *L, int *IPIV, MORSE_desc_t *B, int *info)
{ *info = MORSE_strsmpl_Tile(A, L, IPIV, B); }

//void MORSE_STRSMRV_TILE(MORSE_enum *side, MORSE_enum *uplo, MORSE_enum *transA, MORSE_enum *diag, float *alpha, MORSE_desc_t *A, MORSE_desc_t *B, int *info)
//{ *info = MORSE_strsmrv_Tile(*side, *uplo, *transA, *diag, *alpha, A, B); }

void MORSE_STRTRI_TILE(MORSE_enum *uplo, MORSE_enum *diag, MORSE_desc_t *A, int *info)
{ *info = MORSE_strtri_Tile(*uplo, *diag, A); }

void MORSE_SORGLQ_TILE(MORSE_desc_t *A, MORSE_desc_t *T, MORSE_desc_t *B, int *info)
{ *info = MORSE_sorglq_Tile(A, T, B); }

void MORSE_SORGQR_TILE(MORSE_desc_t *A, MORSE_desc_t *T, MORSE_desc_t *B, int *info)
{ *info = MORSE_sorgqr_Tile(A, T, B); }

void MORSE_SORMLQ_TILE(MORSE_enum *side, MORSE_enum *trans, MORSE_desc_t *A, MORSE_desc_t *T, MORSE_desc_t *B, int *info)
{ *info = MORSE_sormlq_Tile(*side, *trans, A, T, B); }

void MORSE_SORMQR_TILE(MORSE_enum *side, MORSE_enum *trans, MORSE_desc_t *A, MORSE_desc_t *T, MORSE_desc_t *B, int *info)
{ *info = MORSE_sormqr_Tile(*side, *trans, A, T, B); }


/***************************************************************************//**
 *  FORTRAN API - math functions (asynchronous interface)
 **/
//void MORSE_SGEBRD_TILE_ASYNC(MORSE_desc_t *A, float *D, float *E, MORSE_desc_t *T, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
//{ *info = MORSE_sgebrd_Tile_Async(A, D, E, T, sequence, request); }

void MORSE_SGELQF_TILE_ASYNC(MORSE_desc_t *A, MORSE_desc_t *T, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_sgelqf_Tile_Async(A, T, sequence, request); }

void MORSE_SGELQS_TILE_ASYNC(MORSE_desc_t *A, MORSE_desc_t *T, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_sgelqs_Tile_Async(A, T, B, sequence, request); }

void MORSE_SGELS_TILE_ASYNC(MORSE_enum *trans, MORSE_desc_t *A, MORSE_desc_t *T, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_sgels_Tile_Async(*trans, A, T, B, sequence, request); }

void MORSE_SGEMM_TILE_ASYNC(MORSE_enum *transA, MORSE_enum *transB, float *alpha, MORSE_desc_t *A, MORSE_desc_t *B, float *beta, MORSE_desc_t *C, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_sgemm_Tile_Async(*transA, *transB, *alpha, A, B, *beta, C, sequence, request); }

void MORSE_SGEQRF_TILE_ASYNC(MORSE_desc_t *A, MORSE_desc_t *T, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_sgeqrf_Tile_Async(A, T, sequence, request); }

void MORSE_SGEQRS_TILE_ASYNC(MORSE_desc_t *A, MORSE_desc_t *T, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_sgeqrs_Tile_Async(A, T, B, sequence, request); }

//void MORSE_SGESV_TILE_ASYNC(MORSE_desc_t *A, int *IPIV, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
//{ *info = MORSE_sgesv_Tile_Async(A, IPIV, B, sequence, request); }

void MORSE_SGESV_INCPIV_TILE_ASYNC(MORSE_desc_t *A, MORSE_desc_t *L, int *IPIV, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_sgesv_incpiv_Tile_Async(A, L, IPIV, B, sequence, request); }

//void MORSE_SGESV_NOPIV_TILE_ASYNC(MORSE_desc_t *A, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
//{ *info = MORSE_sgesv_nopiv_Tile_Async(A, B, sequence, request); }
//
//void MORSE_SGESVD_TILE_ASYNC(MORSE_enum *jobu, MORSE_enum *jobvt, MORSE_desc_t *A, float *S, MORSE_desc_t *U, MORSE_desc_t *VT, MORSE_desc_t *T, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
//{ *info = MORSE_sgesvd_Tile_Async(*jobu, *jobvt, A, S, U, VT, T, sequence, request); }

//void MORSE_SGETRF_TILE_ASYNC(MORSE_desc_t *A, int *IPIV, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
//{ *info = MORSE_sgetrf_Tile_Async(A, IPIV, sequence, request); }

void MORSE_SGETRF_INCPIV_TILE_ASYNC(MORSE_desc_t *A, MORSE_desc_t *L, int *IPIV, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_sgetrf_incpiv_Tile_Async(A, L, IPIV, sequence, request); }

void MORSE_SGETRF_NOPIV_TILE_ASYNC(MORSE_desc_t *A, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_sgetrf_nopiv_Tile_Async(A, sequence, request); }

//void MORSE_SGETRI_TILE_ASYNC(MORSE_desc_t *A, int *IPIV, MORSE_desc_t *W, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
//{ *info = MORSE_sgetri_Tile_Async(A, IPIV, W, sequence, request); }
//
//void MORSE_SGETRS_TILE_ASYNC(MORSE_enum *trans, MORSE_desc_t *A, int *IPIV, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
//{ *info = MORSE_sgetrs_Tile_Async(*trans, A, IPIV, B, sequence, request); }

void MORSE_SGETRS_INCPIV_TILE_ASYNC(MORSE_desc_t *A, MORSE_desc_t *L, int *IPIV, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_sgetrs_incpiv_Tile_Async(A, L, IPIV, B, sequence, request); }

void MORSE_SGETRS_NOPIV_TILE_ASYNC(MORSE_desc_t *A, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_sgetrs_nopiv_Tile_Async(A, B, sequence, request); }

//void MORSE_SSYEV_TILE_ASYNC(MORSE_enum *jobz, MORSE_enum *uplo, MORSE_desc_t *A, float *W, MORSE_desc_t *T, float *Q, int *LDQ, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
//{ *info = MORSE_ssyev_Tile_Async(*jobz, *uplo, A, W, T, Q, *LDQ, sequence, request); }
//
//void MORSE_SSYEVD_TILE_ASYNC(MORSE_enum *jobz, MORSE_enum *uplo, MORSE_desc_t *A, float *W, MORSE_desc_t *T, float *Q, int *LDQ, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
//{ *info = MORSE_ssyevd_Tile_Async(*jobz, *uplo, A, W, T, Q, *LDQ, sequence, request); }
//
//void MORSE_SSYGST_TILE_ASYNC(MORSE_enum *itype, MORSE_enum *uplo, MORSE_desc_t *A, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
//{ *info = MORSE_ssygst_Tile_Async(*itype, *uplo, A, B, sequence, request); }
//
//void MORSE_SHEGV_TILE_ASYNC(MORSE_enum *itype, MORSE_enum *jobz, MORSE_enum *uplo, MORSE_desc_t *A, MORSE_desc_t *B, float *W, MORSE_desc_t *T, MORSE_desc_t *Q, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
//{ *info = MORSE_shegv_Tile_Async(*itype, *jobz, *uplo, A, B, W, T, Q, sequence, request); }
//
//void MORSE_SSYGVD_TILE_ASYNC(MORSE_enum *itype, MORSE_enum *jobz, MORSE_enum *uplo, MORSE_desc_t *A, MORSE_desc_t *B, float *W, MORSE_desc_t *T, MORSE_desc_t *Q, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
//{ *info = MORSE_ssygvd_Tile_Async(*itype, *jobz, *uplo, A, B, W, T, Q, sequence, request); }

#ifdef COMPLEX
void MORSE_SSYMM_TILE_ASYNC(MORSE_enum *side, MORSE_enum *uplo, float *alpha, MORSE_desc_t *A, MORSE_desc_t *B, float *beta, MORSE_desc_t *C, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_ssymm_Tile_Async(*side, *uplo, *alpha, A, B, *beta, C, sequence, request); }
#endif

#ifdef COMPLEX
void MORSE_SSYR2K_TILE_ASYNC(MORSE_enum *uplo, MORSE_enum *trans, float *alpha, MORSE_desc_t *A, MORSE_desc_t *B, float *beta, MORSE_desc_t *C, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_ssyr2k_Tile_Async(*uplo, *trans, *alpha, A, B, *beta, C, sequence, request); }
#endif

#ifdef COMPLEX
void MORSE_SSYRK_TILE_ASYNC(MORSE_enum *uplo, MORSE_enum *trans, float *alpha, MORSE_desc_t *A, float *beta, MORSE_desc_t *C, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_ssyrk_Tile_Async(*uplo, *trans, *alpha, A, *beta, C, sequence, request); }
#endif

//void MORSE_SSYTRD_TILE_ASYNC(MORSE_enum *jobz, MORSE_enum *uplo, MORSE_desc_t *A, float *D, float *E, MORSE_desc_t *T, float *Q, int *LDQ, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
//{ *info = MORSE_ssytrd_Tile_Async(*jobz, *uplo, A, D, E, T, Q, *LDQ, sequence, request); }

void MORSE_SLACPY_TILE_ASYNC(MORSE_enum *uplo, MORSE_desc_t *A, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_slacpy_Tile_Async(*uplo, A, B, sequence, request); }

void MORSE_SLANGE_TILE_ASYNC(MORSE_enum *norm, MORSE_desc_t *A, float *value, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_slange_Tile_Async(*norm, A, value, sequence, request); }

#ifdef COMPLEX
void MORSE_SLANSY_TILE_ASYNC(MORSE_enum *norm, MORSE_enum *uplo, MORSE_desc_t *A, float *value, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_slansy_Tile_Async(*norm, *uplo, A, value, sequence, request); }
#endif

void MORSE_SLANSY_TILE_ASYNC(MORSE_enum *norm, MORSE_enum *uplo, MORSE_desc_t *A, float *value, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_slansy_Tile_Async(*norm, *uplo, A, value, sequence, request); }

void MORSE_SLANTR_TILE_ASYNC(MORSE_enum *norm, MORSE_enum *uplo, MORSE_enum *diag, MORSE_desc_t *A, float *value, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_slantr_Tile_Async(*norm, *uplo, *diag, A, value, sequence, request); }

void MORSE_SLASET_TILE_ASYNC(MORSE_enum *uplo, float *alpha, float *beta, MORSE_desc_t *A, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_slaset_Tile_Async(*uplo, *alpha, *beta, A, sequence, request); }

//void MORSE_SLASWP_TILE_ASYNC(MORSE_desc_t *A, int *K1, int *K2, int *IPIV, int *INCX, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
//{ *info = MORSE_slaswp_Tile_Async(A, *K1, *K2, IPIV, *INCX, sequence, request); }
//
//void MORSE_SLASWPC_TILE_ASYNC(MORSE_desc_t *A, int *K1, int *K2, int *IPIV, int *INCX, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
//{ *info = MORSE_slaswpc_Tile_Async(A, *K1, *K2, IPIV, *INCX, sequence, request); }

void MORSE_SLAUUM_TILE_ASYNC(MORSE_enum *uplo, MORSE_desc_t *A, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_slauum_Tile_Async(*uplo, A, sequence, request); }

#ifdef COMPLEX
void MORSE_SPLGSY_TILE_ASYNC(float *bump, MORSE_desc_t *A, unsigned long long int *seed, MORSE_sequence_t *sequence, MORSE_request_t * *request, int *info)
{ *info = MORSE_splgsy_Tile_Async(*bump, A, *seed, sequence, *request); }
#endif

void MORSE_SPLGSY_TILE_ASYNC(float *bump, MORSE_desc_t *A, unsigned long long int *seed, MORSE_sequence_t *sequence, MORSE_request_t * *request, int *info)
{ *info = MORSE_splgsy_Tile_Async(*bump, A, *seed, sequence, *request); }

void MORSE_SPLRNT_TILE_ASYNC(MORSE_desc_t *A, unsigned long long int *seed, MORSE_sequence_t *sequence, MORSE_request_t * *request, int *info)
{ *info = MORSE_splrnt_Tile_Async(A, *seed, sequence, *request); }

void MORSE_SPOSV_TILE_ASYNC(MORSE_enum *uplo, MORSE_desc_t *A, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_sposv_Tile_Async(*uplo, A, B, sequence, request); }

void MORSE_SPOTRF_TILE_ASYNC(MORSE_enum *uplo, MORSE_desc_t *A, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_spotrf_Tile_Async(*uplo, A, sequence, request); }

void MORSE_SPOTRI_TILE_ASYNC(MORSE_enum *uplo, MORSE_desc_t *A, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_spotri_Tile_Async(*uplo, A, sequence, request); }

void MORSE_SPOTRS_TILE_ASYNC(MORSE_enum *uplo, MORSE_desc_t *A, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_spotrs_Tile_Async(*uplo, A, B, sequence, request); }

#if defined (PRECISION_c) || defined(PRECISION_z)
void MORSE_SSYSV_TILE_ASYNC(MORSE_enum *uplo, MORSE_desc_t *A, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_ssysv_Tile_Async(*uplo, A, B, sequence, request); }

void MORSE_SSYTRF_TILE_ASYNC(MORSE_enum *uplo, MORSE_desc_t *A, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_ssytrf_Tile_Async(*uplo, A, sequence, request); }

void MORSE_SSYTRS_TILE_ASYNC(MORSE_enum *uplo, MORSE_desc_t *A, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_ssytrs_Tile_Async(*uplo, A, B, sequence, request); }
#endif

void MORSE_SSYMM_TILE_ASYNC(MORSE_enum *side, MORSE_enum *uplo, float *alpha, MORSE_desc_t *A, MORSE_desc_t *B, float *beta, MORSE_desc_t *C, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_ssymm_Tile_Async(*side, *uplo, *alpha, A, B, *beta, C, sequence, request); }

void MORSE_SSYR2K_TILE_ASYNC(MORSE_enum *uplo, MORSE_enum *trans, float *alpha, MORSE_desc_t *A, MORSE_desc_t *B, float *beta, MORSE_desc_t *C, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_ssyr2k_Tile_Async(*uplo, *trans, *alpha, A, B, *beta, C, sequence, request); }

void MORSE_SSYRK_TILE_ASYNC(MORSE_enum *uplo, MORSE_enum *trans, float *alpha, MORSE_desc_t *A, float *beta, MORSE_desc_t *C, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_ssyrk_Tile_Async(*uplo, *trans, *alpha, A, *beta, C, sequence, request); }

void MORSE_STRMM_TILE_ASYNC(MORSE_enum *side, MORSE_enum *uplo, MORSE_enum *transA, MORSE_enum *diag, float *alpha, MORSE_desc_t *A, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_strmm_Tile_Async(*side, *uplo, *transA, *diag, *alpha, A, B, sequence, request); }

void MORSE_STRSM_TILE_ASYNC(MORSE_enum *side, MORSE_enum *uplo, MORSE_enum *transA, MORSE_enum *diag, float *alpha, MORSE_desc_t *A, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_strsm_Tile_Async(*side, *uplo, *transA, *diag, *alpha, A, B, sequence, request); }

void MORSE_STRSMPL_TILE_ASYNC(MORSE_desc_t *A, MORSE_desc_t *L, int *IPIV, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_strsmpl_Tile_Async(A, L, IPIV, B, sequence, request); }

//void MORSE_STRSMRV_TILE_ASYNC(MORSE_enum *side, MORSE_enum *uplo, MORSE_enum *transA, MORSE_enum *diag, float *alpha, MORSE_desc_t *A, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
//{ *info = MORSE_strsmrv_Tile_Async(*side, *uplo, *transA, *diag, *alpha, A, B, sequence, request); }

void MORSE_STRTRI_TILE_ASYNC(MORSE_enum *uplo, MORSE_enum *diag, MORSE_desc_t *A, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_strtri_Tile_Async(*uplo, *diag, A, sequence, request); }

void MORSE_SORGLQ_TILE_ASYNC(MORSE_desc_t *A, MORSE_desc_t *T, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_sorglq_Tile_Async(A, T, B, sequence, request); }

void MORSE_SORGQR_TILE_ASYNC(MORSE_desc_t *A, MORSE_desc_t *T, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_sorgqr_Tile_Async(A, T, B, sequence, request); }

void MORSE_SORMLQ_TILE_ASYNC(MORSE_enum *side, MORSE_enum *trans, MORSE_desc_t *A, MORSE_desc_t *T, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_sormlq_Tile_Async(*side, *trans, A, T, B, sequence, request); }

void MORSE_SORMQR_TILE_ASYNC(MORSE_enum *side, MORSE_enum *trans, MORSE_desc_t *A, MORSE_desc_t *T, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_sormqr_Tile_Async(*side, *trans, A, T, B, sequence, request); }


/***************************************************************************//**
 *  FORTRAN API - workspace allocation
 **/
//void MORSE_ALLOC_WORKSPACE_SGEBRD(int *M, int *N, MORSE_desc_t **descT, int *info)
//{ *info = MORSE_Alloc_Workspace_sgebrd(*M, *N, descT); }
//
//void MORSE_ALLOC_WORKSPACE_SGEEV(int *N, MORSE_desc_t **descT, int *info)
//{ *info = MORSE_Alloc_Workspace_sgeev(*N, descT); }
//
//void MORSE_ALLOC_WORKSPACE_SGEHRD(int *N, MORSE_desc_t **descT, int *info)
//{ *info = MORSE_Alloc_Workspace_sgehrd(*N, descT); }

void MORSE_ALLOC_WORKSPACE_SGELQF(int *M, int *N, MORSE_desc_t **T, int *info)
{ *info = MORSE_Alloc_Workspace_sgelqf(*M, *N, T); }

void MORSE_ALLOC_WORKSPACE_SGELQF_TILE(int *M, int *N, MORSE_desc_t **descT, int *info)
{ *info = MORSE_Alloc_Workspace_sgelqf_Tile(*M, *N, descT); }

void MORSE_ALLOC_WORKSPACE_SGELS(int *M, int *N, MORSE_desc_t **T, int *info)
{ *info = MORSE_Alloc_Workspace_sgels(*M, *N, T); }

void MORSE_ALLOC_WORKSPACE_SGELS_TILE(int *M, int *N, MORSE_desc_t **descT, int *info)
{ *info = MORSE_Alloc_Workspace_sgels_Tile(*M, *N, descT); }

void MORSE_ALLOC_WORKSPACE_SGEQRF(int *M, int *N, MORSE_desc_t **T, int *info)
{ *info = MORSE_Alloc_Workspace_sgeqrf(*M, *N, T); }

void MORSE_ALLOC_WORKSPACE_SGEQRF_TILE(int *M, int *N, MORSE_desc_t **descT, int *info)
{ *info = MORSE_Alloc_Workspace_sgeqrf_Tile(*M, *N, descT); }

void MORSE_ALLOC_WORKSPACE_SGESV_INCPIV(int *N, MORSE_desc_t **descL, int **IPIV, int *info)
{ *info = MORSE_Alloc_Workspace_sgesv_incpiv(*N, descL, IPIV); }

void MORSE_ALLOC_WORKSPACE_SGESV_INCPIV_TILE (int *N, MORSE_desc_t **descL, int **IPIV, int *info)
{ *info = MORSE_Alloc_Workspace_sgesv_incpiv_Tile (*N, descL, IPIV); }

//void MORSE_ALLOC_WORKSPACE_SGESVD(int *M, int *N, MORSE_desc_t **descT, int *info)
//{ *info = MORSE_Alloc_Workspace_sgesvd(*M, *N, descT); }

void MORSE_ALLOC_WORKSPACE_SGETRF_INCPIV(int *M, int *N, MORSE_desc_t **descL, int **IPIV, int *info)
{ *info = MORSE_Alloc_Workspace_sgetrf_incpiv(*M, *N, descL, IPIV); }

void MORSE_ALLOC_WORKSPACE_SGETRF_INCPIV_TILE(int *N, MORSE_desc_t **descL, int **IPIV, int *info)
{ *info = MORSE_Alloc_Workspace_sgetrf_incpiv_Tile(*N, descL, IPIV); }

//void MORSE_ALLOC_WORKSPACE_SGETRI_TILE_ASYNC(MORSE_desc_t *A, MORSE_desc_t *W, int *info)
//{ *info = MORSE_Alloc_Workspace_sgetri_Tile_Async(A, W); }

//void MORSE_ALLOC_WORKSPACE_SSYEV(int *M, int *N, MORSE_desc_t **descT, int *info)
//{ *info = MORSE_Alloc_Workspace_ssyev(*M, *N, descT); }
//
//void MORSE_ALLOC_WORKSPACE_SSYEVD(int *M, int *N, MORSE_desc_t **descT, int *info)
//{ *info = MORSE_Alloc_Workspace_ssyevd(*M, *N, descT); }
//
//void MORSE_ALLOC_WORKSPACE_ZHEGV(int *M, int *N, MORSE_desc_t **descT, int *info)
//{ *info = MORSE_Alloc_Workspace_shegv(*M, *N, descT); }
//
//void MORSE_ALLOC_WORKSPACE_SSYGVD(int *M, int *N, MORSE_desc_t **descT, int *info)
//{ *info = MORSE_Alloc_Workspace_ssygvd(*M, *N, descT); }
//
//void MORSE_ALLOC_WORKSPACE_SSYTRD(int *M, int *N, MORSE_desc_t **descT, int *info)
//{ *info = MORSE_Alloc_Workspace_ssytrd(*M, *N, descT); }



