/**
 *
 * @copyright (c) 2009-2014 The University of Tennessee and The University
 *                          of Tennessee Research Foundation.
 *                          All rights reserved.
 * @copyright (c) 2012-2014 Inria. All rights reserved.
 * @copyright (c) 2012-2014 Bordeaux INP, CNRS (LaBRI UMR 5800), Inria, Univ. Bordeaux. All rights reserved.
 *
 **/

/**
 *
 * @file morse_cf77.c
 *
 *  MORSE computational routines
 *  MORSE is a software package provided by Univ. of Tennessee,
 *  Univ. of California Berkeley and Univ. of Colorado Denver
 *  This file is automatically generated by tools/genf77interface.pl
 *
 * @version 2.5.0
 * @comment This file has been automatically generated
 *          from Plasma 2.5.0 for MORSE 1.0.0
 * @author Bilel Hadri
 * @author Mathieu Faverge
 * @author Emmanuel Agullo
 * @author Cedric Castagnede
 * @date 2010-11-15
 * @generated c Tue Sep 26 20:43:09 2017
 *
 **/
#include <stdlib.h>
#include "control/common.h"
#undef REAL
#define COMPLEX


/***************************************************************************//**
 *  FORTRAN API - math functions (simple interface)
 **/
#define MORSE_CLAPACK_TO_TILE MORSE_FNAME(clapack_to_tile, CLAPACK_TO_TILE)
#define MORSE_CLAPACK_TO_TILE_ASYNC MORSE_FNAME(clapack_to_tile_async, CLAPACK_TO_TILE_ASYNC)
#define MORSE_CTILE_TO_LAPACK MORSE_FNAME(ctile_to_lapack, CTILE_TO_LAPACK)
#define MORSE_CTILE_TO_LAPACK_ASYNC MORSE_FNAME(ctile_to_lapack_async, CTILE_TO_LAPACK_ASYNC)
//#define MORSE_CGEBRD          MORSE_FNAME(cgebrd       , CGEBRD       )
//#define MORSE_CGECFI          MORSE_FNAME(cgecfi       , ZGECFI       )
//#define MORSE_CGECFI_ASYNC    MORSE_FNAME(cgecfi_async , ZGECFI_ASYNC )
#define MORSE_CGELQF          MORSE_FNAME(cgelqf       , CGELQF       )
#define MORSE_CGELQS          MORSE_FNAME(cgelqs       , CGELQS       )
#define MORSE_CGELS           MORSE_FNAME(cgels        , CGELS        )
#define MORSE_CGEMM           MORSE_FNAME(cgemm        , CGEMM        )
#define MORSE_CGEQRF          MORSE_FNAME(cgeqrf       , CGEQRF       )
#define MORSE_CGEQRS          MORSE_FNAME(cgeqrs       , CGEQRS       )
//#define MORSE_CGESV           MORSE_FNAME(cgesv        , CGESV        )
#define MORSE_CGESV_INCPIV    MORSE_FNAME(cgesv_incpiv , CGESV_INCPIV )
#define MORSE_CGESV_NOPIV     MORSE_FNAME(cgesv_nopiv  , CGESV_NOPIV )
//#define MORSE_CGESVD          MORSE_FNAME(cgesvd       , CGESVD       )
//#define MORSE_CGETMI          MORSE_FNAME(cgetmi       , ZGETMI       )
//#define MORSE_CGETMI_ASYNC    MORSE_FNAME(cgetmi_async , ZGETMI_ASYNC )
//#define MORSE_CGETRF          MORSE_FNAME(cgetrf       , CGETRF       )
#define MORSE_CGETRF_INCPIV   MORSE_FNAME(cgetrf_incpiv, CGETRF_INCPIV)
#define MORSE_CGETRF_NOPIV    MORSE_FNAME(cgetrf_nopiv , CGETRF_NOPIV)
//#define MORSE_CGETRI          MORSE_FNAME(cgetri       , CGETRI       )
//#define MORSE_CGETRS          MORSE_FNAME(cgetrs       , CGETRS       )
#define MORSE_CGETRS_INCPIV   MORSE_FNAME(cgetrs_incpiv, CGETRS_INCPIV)
#define MORSE_CGETRS_NOPIV    MORSE_FNAME(cgetrs_nopiv , CGETRS_NOPIV)
//#define MORSE_CHEEV           MORSE_FNAME(cheev        , CHEEV        )
//#define MORSE_CHEEVD          MORSE_FNAME(cheevd       , CHEEVD       )
//#define MORSE_CHEGST          MORSE_FNAME(chegst       , CHEGST       )
//#define MORSE_CHEGV           MORSE_FNAME(chegv        , ZHEGV        )
//#define MORSE_CHEGVD          MORSE_FNAME(chegvd       , CHEGVD       )
#ifdef COMPLEX
#define MORSE_CHEMM           MORSE_FNAME(chemm        , CHEMM        )
#endif
#ifdef COMPLEX
#define MORSE_CHER2K          MORSE_FNAME(cher2k       , CHER2K       )
#endif
#ifdef COMPLEX
#define MORSE_CHERK           MORSE_FNAME(cherk        , CHERK        )
#endif
//#define MORSE_CHETRD          MORSE_FNAME(chetrd       , CHETRD       )
#define MORSE_CLACPY          MORSE_FNAME(clacpy       , CLACPY       )
#define MORSE_CLANGE          MORSE_FNAME(clange       , CLANGE       )
#ifdef COMPLEX
#define MORSE_CLANHE          MORSE_FNAME(clanhe       , CLANHE       )
#endif
#define MORSE_CLANSY          MORSE_FNAME(clansy       , CLANSY       )
#define MORSE_CLANTR          MORSE_FNAME(clantr       , CLANTR       )
#define MORSE_CLASET          MORSE_FNAME(claset       , CLASET       )
//#define MORSE_CLASWP          MORSE_FNAME(claswp       , CLASWP       )
//#define MORSE_CLASWPC         MORSE_FNAME(claswpc      , CLASWPC      )
#define MORSE_CLAUUM          MORSE_FNAME(clauum       , CLAUUM       )
#ifdef COMPLEX
#define MORSE_CPLGHE          MORSE_FNAME(cplghe       , CPLGHE       )
#endif
#define MORSE_CPLGSY          MORSE_FNAME(cplgsy       , ZPLGSY       )
#define MORSE_CPLRNT          MORSE_FNAME(cplrnt       , ZPLRNT       )
#define MORSE_CPOSV           MORSE_FNAME(cposv        , CPOSV        )
#define MORSE_CPOTRF          MORSE_FNAME(cpotrf       , CPOTRF       )
#define MORSE_CPOTRI          MORSE_FNAME(cpotri       , CPOTRI       )
#define MORSE_CPOTRS          MORSE_FNAME(cpotrs       , CPOTRS       )
#if defined (PRECISION_c) || defined(PRECISION_z)
#define MORSE_CSYSV           MORSE_FNAME(csysv        , CSYSV        )
#define MORSE_CSYTRF          MORSE_FNAME(csytrf       , CSYTRF       )
#define MORSE_CSYTRS          MORSE_FNAME(csytrs       , CSYTRS       )
#endif
#define MORSE_CSYMM           MORSE_FNAME(csymm        , CSYMM        )
#define MORSE_CSYR2K          MORSE_FNAME(csyr2k       , CSYR2K       )
#define MORSE_CSYRK           MORSE_FNAME(csyrk        , CSYRK        )
#define MORSE_CTRMM           MORSE_FNAME(ctrmm        , CTRMM        )
#define MORSE_CTRSM           MORSE_FNAME(ctrsm        , CTRSM        )
#define MORSE_CTRSMPL         MORSE_FNAME(ctrsmpl      , CTRSMPL      )
//#define MORSE_CTRSMRV         MORSE_FNAME(ctrsmrv      , CTRSMRV      )
#define MORSE_CTRTRI          MORSE_FNAME(ctrtri       , CTRTRI       )
#define MORSE_CUNGLQ          MORSE_FNAME(cunglq       , CUNGLQ       )
#define MORSE_CUNGQR          MORSE_FNAME(cungqr       , CUNGQR       )
#define MORSE_CUNMLQ          MORSE_FNAME(cunmlq       , CUNMLQ       )
#define MORSE_CUNMQR          MORSE_FNAME(cunmqr       , CUNMQR       )

/***************************************************************************//**
 *  FORTRAN API - math functions (native interface)
 **/
//#define MORSE_CGEBRD_TILE          MORSE_TILE_FNAME(cgebrd       , CGEBRD       )
#define MORSE_CGELQF_TILE          MORSE_TILE_FNAME(cgelqf       , CGELQF       )
#define MORSE_CGELQS_TILE          MORSE_TILE_FNAME(cgelqs       , CGELQS       )
#define MORSE_CGELS_TILE           MORSE_TILE_FNAME(cgels        , CGELS        )
#define MORSE_CGEMM_TILE           MORSE_TILE_FNAME(cgemm        , CGEMM        )
#define MORSE_CGEQRF_TILE          MORSE_TILE_FNAME(cgeqrf       , CGEQRF       )
#define MORSE_CGEQRS_TILE          MORSE_TILE_FNAME(cgeqrs       , CGEQRS       )
//#define MORSE_CGESV_TILE           MORSE_TILE_FNAME(cgesv        , CGESV        )
#define MORSE_CGESV_INCPIV_TILE    MORSE_TILE_FNAME(cgesv_incpiv , CGESV_INCPIV )
#define MORSE_CGESV_NOPIV_TILE     MORSE_TILE_FNAME(cgesv_nopiv  , CGESV_NOPIV  )
//#define MORSE_CGESVD_TILE          MORSE_TILE_FNAME(cgesvd       , CGESVD       )
//#define MORSE_CGETRF_TILE          MORSE_TILE_FNAME(cgetrf       , CGETRF       )
#define MORSE_CGETRF_INCPIV_TILE   MORSE_TILE_FNAME(cgetrf_incpiv, CGETRF_INCPIV)
#define MORSE_CGETRF_NOPIV_TILE    MORSE_TILE_FNAME(cgetrf_nopiv , CGETRF_NOPIV )
//#define MORSE_CGETRI_TILE          MORSE_TILE_FNAME(cgetri       , CGETRI       )
//#define MORSE_CGETRS_TILE          MORSE_TILE_FNAME(cgetrs       , CGETRS       )
#define MORSE_CGETRS_INCPIV_TILE   MORSE_TILE_FNAME(cgetrs_incpiv, CGETRS_INCPIV)
#define MORSE_CGETRS_NOPIV_TILE    MORSE_TILE_FNAME(cgetrs_nopiv , CGETRS_NOPIV )
//#define MORSE_CHEEV_TILE           MORSE_TILE_FNAME(cheev        , CHEEV        )
//#define MORSE_CHEEVD_TILE          MORSE_TILE_FNAME(cheevd       , CHEEVD       )
//#define MORSE_CHEGST_TILE          MORSE_TILE_FNAME(chegst       , CHEGST       )
//#define MORSE_CHEGV_TILE           MORSE_TILE_FNAME(chegv        , ZHEGV        )
//#define MORSE_CHEGVD_TILE          MORSE_TILE_FNAME(chegvd       , CHEGVD       )
#ifdef COMPLEX
#define MORSE_CHEMM_TILE           MORSE_TILE_FNAME(chemm        , CHEMM        )
#endif
#ifdef COMPLEX
#define MORSE_CHER2K_TILE          MORSE_TILE_FNAME(cher2k       , CHER2K       )
#endif
#ifdef COMPLEX
#define MORSE_CHERK_TILE           MORSE_TILE_FNAME(cherk        , CHERK        )
#endif
//#define MORSE_CHETRD_TILE          MORSE_TILE_FNAME(chetrd       , CHETRD       )
#define MORSE_CLACPY_TILE          MORSE_TILE_FNAME(clacpy       , CLACPY       )
#define MORSE_CLANGE_TILE          MORSE_TILE_FNAME(clange       , CLANGE       )
#ifdef COMPLEX
#define MORSE_CLANHE_TILE          MORSE_TILE_FNAME(clanhe       , CLANHE       )
#endif
#define MORSE_CLANSY_TILE          MORSE_TILE_FNAME(clansy       , CLANSY       )
#define MORSE_CLASET_TILE          MORSE_TILE_FNAME(claset       , CLASET       )
//#define MORSE_CLASWP_TILE          MORSE_TILE_FNAME(claswp       , CLASWP       )
//#define MORSE_CLASWPC_TILE         MORSE_TILE_FNAME(claswpc      , CLASWPC      )
#define MORSE_CLAUUM_TILE          MORSE_TILE_FNAME(clauum       , CLAUUM       )
#ifdef COMPLEX
#define MORSE_CPLGHE_TILE          MORSE_TILE_FNAME(cplghe       , CPLGHE       )
#endif
#define MORSE_CPLGSY_TILE          MORSE_TILE_FNAME(cplgsy       , ZPLGSY       )
#define MORSE_CPLRNT_TILE          MORSE_TILE_FNAME(cplrnt       , ZPLRNT       )
#define MORSE_CPOSV_TILE           MORSE_TILE_FNAME(cposv        , CPOSV        )
#define MORSE_CPOTRF_TILE          MORSE_TILE_FNAME(cpotrf       , CPOTRF       )
#define MORSE_CPOTRI_TILE          MORSE_TILE_FNAME(cpotri       , CPOTRI       )
#define MORSE_CPOTRS_TILE          MORSE_TILE_FNAME(cpotrs       , CPOTRS       )
#if defined (PRECISION_c) || defined(PRECISION_z)
#define MORSE_CSYSV_TILE           MORSE_TILE_FNAME(csysv        , CSYSV        )
#define MORSE_CSYTRF_TILE          MORSE_TILE_FNAME(csytrf       , CSYTRF       )
#define MORSE_CSYTRS_TILE          MORSE_TILE_FNAME(csytrs       , CSYTRS       )
#endif
#define MORSE_CSYMM_TILE           MORSE_TILE_FNAME(csymm        , CSYMM        )
#define MORSE_CSYR2K_TILE          MORSE_TILE_FNAME(csyr2k       , CSYR2K       )
#define MORSE_CSYRK_TILE           MORSE_TILE_FNAME(csyrk        , CSYRK        )
#define MORSE_CTRMM_TILE           MORSE_TILE_FNAME(ctrmm        , CTRMM        )
#define MORSE_CTRSM_TILE           MORSE_TILE_FNAME(ctrsm        , CTRSM        )
#define MORSE_CTRSMPL_TILE         MORSE_TILE_FNAME(ctrsmpl      , CTRSMPL      )
//#define MORSE_CTRSMRV_TILE         MORSE_TILE_FNAME(ctrsmrv      , CTRSMRV      )
#define MORSE_CTRTRI_TILE          MORSE_TILE_FNAME(ctrtri       , CTRTRI       )
#define MORSE_CUNGLQ_TILE          MORSE_TILE_FNAME(cunglq       , CUNGLQ       )
#define MORSE_CUNGQR_TILE          MORSE_TILE_FNAME(cungqr       , CUNGQR       )
#define MORSE_CUNMLQ_TILE          MORSE_TILE_FNAME(cunmlq       , CUNMLQ       )
#define MORSE_CUNMQR_TILE          MORSE_TILE_FNAME(cunmqr       , CUNMQR       )

/***************************************************************************//**
 *  FORTRAN API - math functions (asynchronous interface)
 **/
//#define MORSE_CGEBRD_TILE_ASYNC          MORSE_ASYNC_FNAME(cgebrd       , CGEBRD       )
#define MORSE_CGELQF_TILE_ASYNC          MORSE_ASYNC_FNAME(cgelqf       , CGELQF       )
#define MORSE_CGELQS_TILE_ASYNC          MORSE_ASYNC_FNAME(cgelqs       , CGELQS       )
#define MORSE_CGELS_TILE_ASYNC           MORSE_ASYNC_FNAME(cgels        , CGELS        )
#define MORSE_CGEMM_TILE_ASYNC           MORSE_ASYNC_FNAME(cgemm        , CGEMM        )
#define MORSE_CGEQRF_TILE_ASYNC          MORSE_ASYNC_FNAME(cgeqrf       , CGEQRF       )
#define MORSE_CGEQRS_TILE_ASYNC          MORSE_ASYNC_FNAME(cgeqrs       , CGEQRS       )
//#define MORSE_CGESV_TILE_ASYNC           MORSE_ASYNC_FNAME(cgesv        , CGESV        )
#define MORSE_CGESV_INCPIV_TILE_ASYNC    MORSE_ASYNC_FNAME(cgesv_incpiv , CGESV_INCPIV )
#define MORSE_CGESV_NOPIV_TILE_ASYNC     MORSE_ASYNC_FNAME(cgesv_nopiv  , CGESV_NOPIV  )
//#define MORSE_CGESVD_TILE_ASYNC          MORSE_ASYNC_FNAME(cgesvd       , CGESVD       )
//#define MORSE_CGETRF_TILE_ASYNC          MORSE_ASYNC_FNAME(cgetrf       , CGETRF       )
#define MORSE_CGETRF_INCPIV_TILE_ASYNC   MORSE_ASYNC_FNAME(cgetrf_incpiv, CGETRF_INCPIV)
#define MORSE_CGETRF_NOPIV_TILE_ASYNC    MORSE_ASYNC_FNAME(cgetrf_nopiv , CGETRF_NOPIV )
//#define MORSE_CGETRI_TILE_ASYNC          MORSE_ASYNC_FNAME(cgetri       , CGETRI       )
//#define MORSE_CGETRS_TILE_ASYNC          MORSE_ASYNC_FNAME(cgetrs       , CGETRS       )
#define MORSE_CGETRS_INCPIV_TILE_ASYNC   MORSE_ASYNC_FNAME(cgetrs_incpiv, CGETRS_INCPIV)
#define MORSE_CGETRS_NOPIV_TILE_ASYNC    MORSE_ASYNC_FNAME(cgetrs_nopiv , CGETRS_NOPIV )
//#define MORSE_CHEEV_TILE_ASYNC           MORSE_ASYNC_FNAME(cheev        , CHEEV        )
//#define MORSE_CHEEVD_TILE_ASYNC          MORSE_ASYNC_FNAME(cheevd       , CHEEVD       )
//#define MORSE_CHEGST_TILE_ASYNC          MORSE_ASYNC_FNAME(chegst       , CHEGST       )
//#define MORSE_CHEGV_TILE_ASYNC           MORSE_ASYNC_FNAME(chegv        , ZHEGV        )
//#define MORSE_CHEGVD_TILE_ASYNC          MORSE_ASYNC_FNAME(chegvd       , CHEGVD       )
#ifdef COMPLEX
#define MORSE_CHEMM_TILE_ASYNC           MORSE_ASYNC_FNAME(chemm        , CHEMM        )
#define MORSE_CHER2K_TILE_ASYNC          MORSE_ASYNC_FNAME(cher2k       , CHER2K       )
#define MORSE_CHERK_TILE_ASYNC           MORSE_ASYNC_FNAME(cherk        , CHERK        )
#endif
//#define MORSE_CHETRD_TILE_ASYNC          MORSE_ASYNC_FNAME(chetrd       , CHETRD       )
#define MORSE_CLACPY_TILE_ASYNC          MORSE_ASYNC_FNAME(clacpy       , CLACPY       )
#define MORSE_CLANGE_TILE_ASYNC          MORSE_ASYNC_FNAME(clange       , CLANGE       )
#ifdef COMPLEX
#define MORSE_CLANHE_TILE_ASYNC          MORSE_ASYNC_FNAME(clanhe       , CLANHE       )
#endif
#define MORSE_CLANSY_TILE_ASYNC          MORSE_ASYNC_FNAME(clansy       , CLANSY       )
#define MORSE_CLANTR_TILE_ASYNC          MORSE_ASYNC_FNAME(clantr       , CLANTR       )
#define MORSE_CLASET_TILE_ASYNC          MORSE_ASYNC_FNAME(claset       , CLASET       )
//#define MORSE_CLASWP_TILE_ASYNC          MORSE_ASYNC_FNAME(claswp       , CLASWP       )
//#define MORSE_CLASWPC_TILE_ASYNC         MORSE_ASYNC_FNAME(claswpc      , CLASWPC      )
#define MORSE_CLAUUM_TILE_ASYNC          MORSE_ASYNC_FNAME(clauum       , CLAUUM       )
#ifdef COMPLEX
#define MORSE_CPLGHE_TILE_ASYNC          MORSE_ASYNC_FNAME(cplghe       , CPLGHE       )
#endif
#define MORSE_CPLGSY_TILE_ASYNC          MORSE_ASYNC_FNAME(cplgsy       , ZPLGSY       )
#define MORSE_CPLRNT_TILE_ASYNC          MORSE_ASYNC_FNAME(cplrnt       , ZPLRNT       )
#define MORSE_CPOSV_TILE_ASYNC           MORSE_ASYNC_FNAME(cposv        , CPOSV        )
#define MORSE_CPOTRF_TILE_ASYNC          MORSE_ASYNC_FNAME(cpotrf       , CPOTRF       )
#define MORSE_CPOTRI_TILE_ASYNC          MORSE_ASYNC_FNAME(cpotri       , CPOTRI       )
#define MORSE_CPOTRS_TILE_ASYNC          MORSE_ASYNC_FNAME(cpotrs       , CPOTRS       )
#if defined (PRECISION_c) || defined(PRECISION_z)
#define MORSE_CSYSV_TILE_ASYNC           MORSE_ASYNC_FNAME(csysv        , CSYSV        )
#define MORSE_CSYTRF_TILE_ASYNC          MORSE_ASYNC_FNAME(csytrf       , CSYTRF       )
#define MORSE_CSYTRS_TILE_ASYNC          MORSE_ASYNC_FNAME(csytrs       , CSYTRS       )
#endif
#define MORSE_CSYMM_TILE_ASYNC           MORSE_ASYNC_FNAME(csymm        , CSYMM        )
#define MORSE_CSYR2K_TILE_ASYNC          MORSE_ASYNC_FNAME(csyr2k       , CSYR2K       )
#define MORSE_CSYRK_TILE_ASYNC           MORSE_ASYNC_FNAME(csyrk        , CSYRK        )
#define MORSE_CTRMM_TILE_ASYNC           MORSE_ASYNC_FNAME(ctrmm        , CTRMM        )
#define MORSE_CTRSM_TILE_ASYNC           MORSE_ASYNC_FNAME(ctrsm        , CTRSM        )
#define MORSE_CTRSMPL_TILE_ASYNC         MORSE_ASYNC_FNAME(ctrsmpl      , CTRSMPL      )
//#define MORSE_CTRSMRV_TILE_ASYNC         MORSE_ASYNC_FNAME(ctrsmrv      , CTRSMRV      )
#define MORSE_CTRTRI_TILE_ASYNC          MORSE_ASYNC_FNAME(ctrtri       , CTRTRI       )
#define MORSE_CUNGLQ_TILE_ASYNC          MORSE_ASYNC_FNAME(cunglq       , CUNGLQ       )
#define MORSE_CUNGQR_TILE_ASYNC          MORSE_ASYNC_FNAME(cungqr       , CUNGQR       )
#define MORSE_CUNMLQ_TILE_ASYNC          MORSE_ASYNC_FNAME(cunmlq       , CUNMLQ       )
#define MORSE_CUNMQR_TILE_ASYNC          MORSE_ASYNC_FNAME(cunmqr       , CUNMQR       )

/***************************************************************************//**
 *  FORTRAN API - workspace allocation
 **/
//#define MORSE_ALLOC_WORKSPACE_CGEBRD              MORSE_WS_FNAME(cgebrd            , CGEBRD            )
//#define MORSE_ALLOC_WORKSPACE_CGEEV               MORSE_WS_FNAME(cgeev             , CGEEV             )
//#define MORSE_ALLOC_WORKSPACE_CGEHRD              MORSE_WS_FNAME(cgehrd            , CGEHRD            )
#define MORSE_ALLOC_WORKSPACE_CGELQF              MORSE_WS_FNAME(cgelqf            , CGELQF            )
#define MORSE_ALLOC_WORKSPACE_CGELQF_TILE         MORSE_WS_FNAME(cgelqf_tile       , CGELQF_TILE       )
#define MORSE_ALLOC_WORKSPACE_CGELS               MORSE_WS_FNAME(cgels             , CGELS             )
#define MORSE_ALLOC_WORKSPACE_CGELS_TILE          MORSE_WS_FNAME(cgels_tile        , CGELS_TILE        )
#define MORSE_ALLOC_WORKSPACE_CGEQRF              MORSE_WS_FNAME(cgeqrf            , CGEQRF            )
#define MORSE_ALLOC_WORKSPACE_CGEQRF_TILE         MORSE_WS_FNAME(cgeqrf_tile       , CGEQRF_TILE       )
#define MORSE_ALLOC_WORKSPACE_CGESV_INCPIV        MORSE_WS_FNAME(cgesv_incpiv      , CGESV_INCPIV      )
#define MORSE_ALLOC_WORKSPACE_CGESV_INCPIV_TILE   MORSE_WS_FNAME(cgesv_incpiv_tile , CGESV_INCPIV_TILE )
//#define MORSE_ALLOC_WORKSPACE_CGESVD              MORSE_WS_FNAME(cgesvd            , CGESVD            )
#define MORSE_ALLOC_WORKSPACE_CGETRF_INCPIV       MORSE_WS_FNAME(cgetrf_incpiv     , CGETRF_INCPIV     )
#define MORSE_ALLOC_WORKSPACE_CGETRF_INCPIV_TILE  MORSE_WS_FNAME(cgetrf_incpiv_tile, CGETRF_INCPIV_TILE)
//#define MORSE_ALLOC_WORKSPACE_CGETRI_TILE_ASYNC   MORSE_WS_FNAME(cgetri_tile_async , CGETRI_TILE_ASYNC )
//#define MORSE_ALLOC_WORKSPACE_CHEEV               MORSE_WS_FNAME(cheev             , CHEEV             )
//#define MORSE_ALLOC_WORKSPACE_CHEEVD              MORSE_WS_FNAME(cheevd            , CHEEVD            )
//#define MORSE_ALLOC_WORKSPACE_ZHEGV               MORSE_WS_FNAME(chegv             , ZHEGV             )
//#define MORSE_ALLOC_WORKSPACE_CHEGVD              MORSE_WS_FNAME(chegvd            , CHEGVD            )
//#define MORSE_ALLOC_WORKSPACE_CHETRD              MORSE_WS_FNAME(chetrd            , CHETRD            )



/***************************************************************************//**
 *  FORTRAN API - math functions (simple interface)
 **/
void MORSE_CLAPACK_TO_TILE(MORSE_Complex32_t *Af77, int *LDA, MORSE_desc_t *A, int *info)
{ *info = MORSE_cLapack_to_Tile(Af77, *LDA, A); }

void MORSE_CLAPACK_TO_TILE_ASYNC(MORSE_Complex32_t *Af77, int *LDA, MORSE_desc_t *A, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_cLapack_to_Tile_Async(Af77, *LDA, A, sequence, request); }

void MORSE_CTILE_TO_LAPACK(MORSE_desc_t *A, MORSE_Complex32_t *Af77, int *LDA, int *info)
{ *info = MORSE_cTile_to_Lapack(A, Af77, *LDA); }

void MORSE_CTILE_TO_LAPACK_ASYNC(MORSE_desc_t *A, MORSE_Complex32_t *Af77, int *LDA, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_cTile_to_Lapack_Async(A, Af77, *LDA, sequence, request); }

//void MORSE_CGEBRD(int *M, int *N, MORSE_Complex32_t *A, int *LDA, float *D, float *E, MORSE_desc_t **descT, int *info)
//{ *info = MORSE_cgebrd(*M, *N, A, *LDA, D, E, *descT); }
//
//void MORSE_CGECFI(int *m, int *n, MORSE_Complex32_t *A, MORSE_enum *fin, int *imb, int *inb, MORSE_enum *fout, int *omb, int *onb, int *info)
//{ *info = MORSE_cgecfi(*m, *n, A, *fin, *imb, *inb, *fout, *omb, *onb); }
//
//void MORSE_CGECFI_ASYNC(int *m, int *n, MORSE_Complex32_t *A, MORSE_enum *f_in, int *imb, int *inb, MORSE_enum *f_out, int *omb, int *onb, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
//{ *info = MORSE_cgecfi_Async(*m, *n, A, *f_in, *imb, *inb, *f_out, *omb, *onb, sequence, request); }

void MORSE_CGELQF(int *M, int *N, MORSE_Complex32_t *A, int *LDA, MORSE_desc_t **descT, int *info)
{ *info = MORSE_cgelqf(*M, *N, A, *LDA, *descT); }

void MORSE_CGELQS(int *M, int *N, int *NRHS, MORSE_Complex32_t *A, int *LDA, MORSE_desc_t **descT, MORSE_Complex32_t *B, int *LDB, int *info)
{ *info = MORSE_cgelqs(*M, *N, *NRHS, A, *LDA, *descT, B, *LDB); }

void MORSE_CGELS(MORSE_enum *trans, int *M, int *N, int *NRHS, MORSE_Complex32_t *A, int *LDA, MORSE_desc_t **descT, MORSE_Complex32_t *B, int *LDB, int *info)
{ *info = MORSE_cgels(*trans, *M, *N, *NRHS, A, *LDA, *descT, B, *LDB); }

void MORSE_CGEMM(MORSE_enum *transA, MORSE_enum *transB, int *M, int *N, int *K, MORSE_Complex32_t *alpha, MORSE_Complex32_t *A, int *LDA, MORSE_Complex32_t *B, int *LDB, MORSE_Complex32_t *beta, MORSE_Complex32_t *C, int *LDC, int *info)
{ *info = MORSE_cgemm(*transA, *transB, *M, *N, *K, *alpha, A, *LDA, B, *LDB, *beta, C, *LDC); }

void MORSE_CGEQRF(int *M, int *N, MORSE_Complex32_t *A, int *LDA, MORSE_desc_t **descT, int *info)
{ *info = MORSE_cgeqrf(*M, *N, A, *LDA, *descT); }

void MORSE_CGEQRS(int *M, int *N, int *NRHS, MORSE_Complex32_t *A, int *LDA, MORSE_desc_t **descT, MORSE_Complex32_t *B, int *LDB, int *info)
{ *info = MORSE_cgeqrs(*M, *N, *NRHS, A, *LDA, *descT, B, *LDB); }

//void MORSE_CGESV(int *N, int *NRHS, MORSE_Complex32_t *A, int *LDA, int *IPIV, MORSE_Complex32_t *B, int *LDB, int *info)
//{ *info = MORSE_cgesv(*N, *NRHS, A, *LDA, IPIV, B, *LDB); }

void MORSE_CGESV_INCPIV(int *N, int *NRHS, MORSE_Complex32_t *A, int *LDA, MORSE_desc_t **descL, int *IPIV, MORSE_Complex32_t *B, int *LDB, int *info)
{ *info = MORSE_cgesv_incpiv(*N, *NRHS, A, *LDA, *descL, IPIV, B, *LDB); }

void MORSE_CGESV_NOPIV(int *N, int *NRHS, MORSE_Complex32_t *A, int *LDA, MORSE_Complex32_t *B, int *LDB, int *info)
{ *info = MORSE_cgesv_nopiv(*N, *NRHS, A, *LDA, B, *LDB); }

//void MORSE_CGESVD(MORSE_enum *jobu, MORSE_enum *jobvt, int *M, int *N, MORSE_Complex32_t *A, int *LDA, float *S, MORSE_Complex32_t *U, int *LDU, MORSE_Complex32_t *VT, int *LDVT, MORSE_desc_t **descT, int *info)
//{ *info = MORSE_cgesvd(*jobu, *jobvt, *M, *N, A, *LDA, S, U, *LDU, VT, *LDVT, *descT); }

//void MORSE_CGETMI(int *m, int *n, MORSE_Complex32_t *A, MORSE_enum *fin, int *mb, int *nb, int *info)
//{ *info = MORSE_cgetmi(*m, *n, A, *fin, *mb, *nb); }
//
//void MORSE_CGETMI_ASYNC(int *m, int *n, MORSE_Complex32_t *A, MORSE_enum *f_in, int *mb, int *inb, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
//{ *info = MORSE_cgetmi_Async(*m, *n, A, *f_in, *mb, *inb, sequence, request); }
//
//void MORSE_CGETRF(int *M, int *N, MORSE_Complex32_t *A, int *LDA, int *IPIV, int *info)
//{ *info = MORSE_cgetrf(*M, *N, A, *LDA, IPIV); }

void MORSE_CGETRF_INCPIV(int *M, int *N, MORSE_Complex32_t *A, int *LDA, MORSE_desc_t **descL, int *IPIV, int *info)
{ *info = MORSE_cgetrf_incpiv(*M, *N, A, *LDA, *descL, IPIV); }

void MORSE_CGETRF_NOPIV(int *M, int *N, MORSE_Complex32_t *A, int *LDA, int *info)
{ *info = MORSE_cgetrf_nopiv(*M, *N, A, *LDA); }

//void MORSE_CGETRI(int *N, MORSE_Complex32_t *A, int *LDA, int *IPIV, int *info)
//{ *info = MORSE_cgetri(*N, A, *LDA, IPIV); }
//
//void MORSE_CGETRS(MORSE_enum *trans, int *N, int *NRHS, MORSE_Complex32_t *A, int *LDA, int *IPIV, MORSE_Complex32_t *B, int *LDB, int *info)
//{ *info = MORSE_cgetrs(*trans, *N, *NRHS, A, *LDA, IPIV, B, *LDB); }

void MORSE_CGETRS_INCPIV(MORSE_enum *trans, int *N, int *NRHS, MORSE_Complex32_t *A, int *LDA, MORSE_desc_t **descL, int *IPIV, MORSE_Complex32_t *B, int *LDB, int *info)
{ *info = MORSE_cgetrs_incpiv(*trans, *N, *NRHS, A, *LDA, *descL, IPIV, B, *LDB); }

void MORSE_CGETRS_NOPIV(MORSE_enum *trans, int *N, int *NRHS, MORSE_Complex32_t *A, int *LDA, MORSE_Complex32_t *B, int *LDB, int *info)
{ *info = MORSE_cgetrs_nopiv(*trans, *N, *NRHS, A, *LDA, B, *LDB); }

//void MORSE_CHEEV(MORSE_enum *jobz, MORSE_enum *uplo, int *N, MORSE_Complex32_t *A, int *LDA, float *W, MORSE_desc_t **descT, MORSE_Complex32_t *Q, int *LDQ, int *info)
//{ *info = MORSE_cheev(*jobz, *uplo, *N, A, *LDA, W, *descT, Q, *LDQ); }
//
//void MORSE_CHEEVD(MORSE_enum *jobz, MORSE_enum *uplo, int *N, MORSE_Complex32_t *A, int *LDA, float *W, MORSE_desc_t **descT, MORSE_Complex32_t *Q, int *LDQ, int *info)
//{ *info = MORSE_cheevd(*jobz, *uplo, *N, A, *LDA, W, *descT, Q, *LDQ); }
//
//void MORSE_CHEGST(MORSE_enum *itype, MORSE_enum *uplo, int *N, MORSE_Complex32_t *A, int *LDA, MORSE_Complex32_t *B, int *LDB, int *info)
//{ *info = MORSE_chegst(*itype, *uplo, *N, A, *LDA, B, *LDB); }
//
//void MORSE_CHEGV(MORSE_enum *itype, MORSE_enum *jobz, MORSE_enum *uplo, int *N, MORSE_Complex32_t *A, int *LDA, MORSE_Complex32_t *B, int *LDB, float *W, MORSE_desc_t **descT, MORSE_Complex32_t *Q, int *LDQ, int *info)
//{ *info = MORSE_chegv(*itype, *jobz, *uplo, *N, A, *LDA, B, *LDB, W, *descT, Q, *LDQ); }
//
//void MORSE_CHEGVD(MORSE_enum *itype, MORSE_enum *jobz, MORSE_enum *uplo, int *N, MORSE_Complex32_t *A, int *LDA, MORSE_Complex32_t *B, int *LDB, float *W, MORSE_desc_t **descT, MORSE_Complex32_t *Q, int *LDQ, int *info)
//{ *info = MORSE_chegvd(*itype, *jobz, *uplo, *N, A, *LDA, B, *LDB, W, *descT, Q, *LDQ); }

#ifdef COMPLEX
void MORSE_CHEMM(MORSE_enum *side, MORSE_enum *uplo, int *M, int *N, MORSE_Complex32_t *alpha, MORSE_Complex32_t *A, int *LDA, MORSE_Complex32_t *B, int *LDB, MORSE_Complex32_t *beta, MORSE_Complex32_t *C, int *LDC, int *info)
{ *info = MORSE_chemm(*side, *uplo, *M, *N, *alpha, A, *LDA, B, *LDB, *beta, C, *LDC); }
#endif

#ifdef COMPLEX
void MORSE_CHER2K(MORSE_enum *uplo, MORSE_enum *trans, int *N, int *K, MORSE_Complex32_t *alpha, MORSE_Complex32_t *A, int *LDA, MORSE_Complex32_t *B, int *LDB, float *beta, MORSE_Complex32_t *C, int *LDC, int *info)
{ *info = MORSE_cher2k(*uplo, *trans, *N, *K, *alpha, A, *LDA, B, *LDB, *beta, C, *LDC); }
#endif

#ifdef COMPLEX
void MORSE_CHERK(MORSE_enum *uplo, MORSE_enum *trans, int *N, int *K, float *alpha, MORSE_Complex32_t *A, int *LDA, float *beta, MORSE_Complex32_t *C, int *LDC, int *info)
{ *info = MORSE_cherk(*uplo, *trans, *N, *K, *alpha, A, *LDA, *beta, C, *LDC); }
#endif

//void MORSE_CHETRD(MORSE_enum *jobz, MORSE_enum *uplo, int *N, MORSE_Complex32_t *A, int *LDA, float *D, float *E, MORSE_desc_t **descT, MORSE_Complex32_t *Q, int *LDQ, int *info)
//{ *info = MORSE_chetrd(*jobz, *uplo, *N, A, *LDA, D, E, *descT, Q, *LDQ); }

void MORSE_CLACPY(MORSE_enum *uplo, int *M, int *N, MORSE_Complex32_t *A, int *LDA, MORSE_Complex32_t *B, int *LDB, int *info)
{ *info = MORSE_clacpy(*uplo, *M, *N, A, *LDA, B, *LDB); }

void MORSE_CLANGE(MORSE_enum *norm, int *M, int *N, MORSE_Complex32_t *A, int *LDA, float *result)
{ *result = MORSE_clange(*norm, *M, *N, A, *LDA); }

#ifdef COMPLEX
void MORSE_CLANHE(MORSE_enum *norm, MORSE_enum *uplo, int *N, MORSE_Complex32_t *A, int *LDA, float *result)
{ *result = MORSE_clanhe(*norm, *uplo, *N, A, *LDA); }
#endif

void MORSE_CLANSY(MORSE_enum *norm, MORSE_enum *uplo, int *N, MORSE_Complex32_t *A, int *LDA, float *result)
{ *result = MORSE_clansy(*norm, *uplo, *N, A, *LDA); }

void MORSE_CLANTR(MORSE_enum *norm, MORSE_enum *uplo, MORSE_enum *diag, int *M, int *N, MORSE_Complex32_t *A, int *LDA, float *result)
{ *result = MORSE_clantr(*norm, *uplo, *diag, *M, *N, A, *LDA); }

void MORSE_CLASET(MORSE_enum *uplo, int *M, int *N, MORSE_Complex32_t *alpha, MORSE_Complex32_t *beta, MORSE_Complex32_t *A, int *LDA, int *info)
{ *info = MORSE_claset(*uplo, *M, *N, *alpha, *beta, A, *LDA); }

//void MORSE_CLASWP(int *N, MORSE_Complex32_t *A, int *LDA, int *K1, int *K2, int *IPIV, int *INCX, int *info)
//{ *info = MORSE_claswp(*N, A, *LDA, *K1, *K2, IPIV, *INCX); }
//
//void MORSE_CLASWPC(int *N, MORSE_Complex32_t *A, int *LDA, int *K1, int *K2, int *IPIV, int *INCX, int *info)
//{ *info = MORSE_claswpc(*N, A, *LDA, *K1, *K2, IPIV, *INCX); }

void MORSE_CLAUUM(MORSE_enum *uplo, int *N, MORSE_Complex32_t *A, int *LDA, int *info)
{ *info = MORSE_clauum(*uplo, *N, A, *LDA); }

#ifdef COMPLEX
void MORSE_CPLGHE(float *bump, int *N, MORSE_Complex32_t *A, int *LDA, unsigned long long int  *seed, int *info)
{ *info = MORSE_cplghe(*bump, *N, A, *LDA, *seed); }
#endif

void MORSE_CPLGSY(MORSE_Complex32_t *bump, int *N, MORSE_Complex32_t *A, int *LDA, unsigned long long int  *seed, int *info)
{ *info = MORSE_cplgsy(*bump, *N, A, *LDA, *seed); }

void MORSE_CPLRNT(int *M, int *N, MORSE_Complex32_t *A, int *LDA, unsigned long long int  *seed, int *info)
{ *info = MORSE_cplrnt(*M, *N, A, *LDA, *seed); }

void MORSE_CPOSV(MORSE_enum *uplo, int *N, int *NRHS, MORSE_Complex32_t *A, int *LDA, MORSE_Complex32_t *B, int *LDB, int *info)
{ *info = MORSE_cposv(*uplo, *N, *NRHS, A, *LDA, B, *LDB); }

void MORSE_CPOTRF(MORSE_enum *uplo, int *N, MORSE_Complex32_t *A, int *LDA, int *info)
{ *info = MORSE_cpotrf(*uplo, *N, A, *LDA); }

void MORSE_CPOTRI(MORSE_enum *uplo, int *N, MORSE_Complex32_t *A, int *LDA, int *info)
{ *info = MORSE_cpotri(*uplo, *N, A, *LDA); }

void MORSE_CPOTRS(MORSE_enum *uplo, int *N, int *NRHS, MORSE_Complex32_t *A, int *LDA, MORSE_Complex32_t *B, int *LDB, int *info)
{ *info = MORSE_cpotrs(*uplo, *N, *NRHS, A, *LDA, B, *LDB); }

#if defined (PRECISION_c) || defined(PRECISION_z)
void MORSE_CSYSV(MORSE_enum *uplo, int *N, int *NRHS, MORSE_Complex32_t *A, int *LDA, MORSE_Complex32_t *B, int *LDB, int *info)
{ *info = MORSE_csysv(*uplo, *N, *NRHS, A, *LDA, B, *LDB); }

void MORSE_CSYTRF(MORSE_enum *uplo, int *N, MORSE_Complex32_t *A, int *LDA, int *info)
{ *info = MORSE_csytrf(*uplo, *N, A, *LDA); }

void MORSE_CSYTRS(MORSE_enum *uplo, int *N, int *NRHS, MORSE_Complex32_t *A, int *LDA, MORSE_Complex32_t *B, int *LDB, int *info)
{ *info = MORSE_csytrs(*uplo, *N, *NRHS, A, *LDA, B, *LDB); }
#endif

void MORSE_CSYMM(MORSE_enum *side, MORSE_enum *uplo, int *M, int *N, MORSE_Complex32_t *alpha, MORSE_Complex32_t *A, int *LDA, MORSE_Complex32_t *B, int *LDB, MORSE_Complex32_t *beta, MORSE_Complex32_t *C, int *LDC, int *info)
{ *info = MORSE_csymm(*side, *uplo, *M, *N, *alpha, A, *LDA, B, *LDB, *beta, C, *LDC); }

void MORSE_CSYR2K(MORSE_enum *uplo, MORSE_enum *trans, int *N, int *K, MORSE_Complex32_t *alpha, MORSE_Complex32_t *A, int *LDA, MORSE_Complex32_t *B, int *LDB, MORSE_Complex32_t *beta, MORSE_Complex32_t *C, int *LDC, int *info)
{ *info = MORSE_csyr2k(*uplo, *trans, *N, *K, *alpha, A, *LDA, B, *LDB, *beta, C, *LDC); }

void MORSE_CSYRK(MORSE_enum *uplo, MORSE_enum *trans, int *N, int *K, MORSE_Complex32_t *alpha, MORSE_Complex32_t *A, int *LDA, MORSE_Complex32_t *beta, MORSE_Complex32_t *C, int *LDC, int *info)
{ *info = MORSE_csyrk(*uplo, *trans, *N, *K, *alpha, A, *LDA, *beta, C, *LDC); }

void MORSE_CTRMM(MORSE_enum *side, MORSE_enum *uplo, MORSE_enum *transA, MORSE_enum *diag, int *N, int *NRHS, MORSE_Complex32_t *alpha, MORSE_Complex32_t *A, int *LDA, MORSE_Complex32_t *B, int *LDB, int *info)
{ *info = MORSE_ctrmm(*side, *uplo, *transA, *diag, *N, *NRHS, *alpha, A, *LDA, B, *LDB); }

void MORSE_CTRSM(MORSE_enum *side, MORSE_enum *uplo, MORSE_enum *transA, MORSE_enum *diag, int *N, int *NRHS, MORSE_Complex32_t *alpha, MORSE_Complex32_t *A, int *LDA, MORSE_Complex32_t *B, int *LDB, int *info)
{ *info = MORSE_ctrsm(*side, *uplo, *transA, *diag, *N, *NRHS, *alpha, A, *LDA, B, *LDB); }

void MORSE_CTRSMPL(int *N, int *NRHS, MORSE_Complex32_t *A, int *LDA, MORSE_desc_t **descL, int *IPIV, MORSE_Complex32_t *B, int *LDB, int *info)
{ *info = MORSE_ctrsmpl(*N, *NRHS, A, *LDA, *descL, IPIV, B, *LDB); }

//void MORSE_CTRSMRV(MORSE_enum *side, MORSE_enum *uplo, MORSE_enum *transA, MORSE_enum *diag, int *N, int *NRHS, MORSE_Complex32_t *alpha, MORSE_Complex32_t *A, int *LDA, MORSE_Complex32_t *B, int *LDB, int *info)
//{ *info = MORSE_ctrsmrv(*side, *uplo, *transA, *diag, *N, *NRHS, *alpha, A, *LDA, B, *LDB); }

void MORSE_CTRTRI(MORSE_enum *uplo, MORSE_enum *diag, int *N, MORSE_Complex32_t *A, int *LDA, int *info)
{ *info = MORSE_ctrtri(*uplo, *diag, *N, A, *LDA); }

void MORSE_CUNGLQ(int *M, int *N, int *K, MORSE_Complex32_t *A, int *LDA, MORSE_desc_t **descT, MORSE_Complex32_t *B, int *LDB, int *info)
{ *info = MORSE_cunglq(*M, *N, *K, A, *LDA, *descT, B, *LDB); }

void MORSE_CUNGQR(int *M, int *N, int *K, MORSE_Complex32_t *A, int *LDA, MORSE_desc_t **descT, MORSE_Complex32_t *B, int *LDB, int *info)
{ *info = MORSE_cungqr(*M, *N, *K, A, *LDA, *descT, B, *LDB); }

void MORSE_CUNMLQ(MORSE_enum *side, MORSE_enum *trans, int *M, int *N, int *K, MORSE_Complex32_t *A, int *LDA, MORSE_desc_t **descT, MORSE_Complex32_t *B, int *LDB, int *info)
{ *info = MORSE_cunmlq(*side, *trans, *M, *N, *K, A, *LDA, *descT, B, *LDB); }

void MORSE_CUNMQR(MORSE_enum *side, MORSE_enum *trans, int *M, int *N, int *K, MORSE_Complex32_t *A, int *LDA, MORSE_desc_t **descT, MORSE_Complex32_t *B, int *LDB, int *info)
{ *info = MORSE_cunmqr(*side, *trans, *M, *N, *K, A, *LDA, *descT, B, *LDB); }


/***************************************************************************//**
 *  FORTRAN API - math functions (native interface)
 **/
//void MORSE_CGEBRD_TILE(MORSE_desc_t *A, float *D, float *E, MORSE_desc_t *T, int *info)
//{ *info = MORSE_cgebrd_Tile(A, D, E, T); }

void MORSE_CGELQF_TILE(MORSE_desc_t *A, MORSE_desc_t *T, int *info)
{ *info = MORSE_cgelqf_Tile(A, T); }

void MORSE_CGELQS_TILE(MORSE_desc_t *A, MORSE_desc_t *T, MORSE_desc_t *B, int *info)
{ *info = MORSE_cgelqs_Tile(A, T, B); }

void MORSE_CGELS_TILE(MORSE_enum *trans, MORSE_desc_t *A, MORSE_desc_t *T, MORSE_desc_t *B, int *info)
{ *info = MORSE_cgels_Tile(*trans, A, T, B); }

void MORSE_CGEMM_TILE(MORSE_enum *transA, MORSE_enum *transB, MORSE_Complex32_t *alpha, MORSE_desc_t *A, MORSE_desc_t *B, MORSE_Complex32_t *beta, MORSE_desc_t *C, int *info)
{ *info = MORSE_cgemm_Tile(*transA, *transB, *alpha, A, B, *beta, C); }

void MORSE_CGEQRF_TILE(MORSE_desc_t *A, MORSE_desc_t *T, int *info)
{ *info = MORSE_cgeqrf_Tile(A, T); }

void MORSE_CGEQRS_TILE(MORSE_desc_t *A, MORSE_desc_t *T, MORSE_desc_t *B, int *info)
{ *info = MORSE_cgeqrs_Tile(A, T, B); }

//void MORSE_CGESV_TILE(MORSE_desc_t *A, int *IPIV, MORSE_desc_t *B, int *info)
//{ *info = MORSE_cgesv_Tile(A, IPIV, B); }

void MORSE_CGESV_INCPIV_TILE(MORSE_desc_t *A, MORSE_desc_t *L, int *IPIV, MORSE_desc_t *B, int *info)
{ *info = MORSE_cgesv_incpiv_Tile(A, L, IPIV, B); }

void MORSE_CGESV_NOPIV_TILE(MORSE_desc_t *A, MORSE_desc_t *B, int *info)
{ *info = MORSE_cgesv_nopiv_Tile(A, B); }

//void MORSE_CGESVD_TILE(MORSE_enum *jobu, MORSE_enum *jobvt, MORSE_desc_t *A, float *S, MORSE_desc_t *U, MORSE_desc_t *VT, MORSE_desc_t *T, int *info)
//{ *info = MORSE_cgesvd_Tile(*jobu, *jobvt, A, S, U, VT, T); }

//void MORSE_CGETRF_TILE(MORSE_desc_t *A, int *IPIV, int *info)
//{ *info = MORSE_cgetrf_Tile(A, IPIV); }

void MORSE_CGETRF_INCPIV_TILE(MORSE_desc_t *A, MORSE_desc_t *L, int *IPIV, int *info)
{ *info = MORSE_cgetrf_incpiv_Tile(A, L, IPIV); }

void MORSE_CGETRF_NOPIV_TILE(MORSE_desc_t *A, int *info)
{ *info = MORSE_cgetrf_nopiv_Tile(A); }

//void MORSE_CGETRI_TILE(MORSE_desc_t *A, int *IPIV, int *info)
//{ *info = MORSE_cgetri_Tile(A, IPIV); }
//
//void MORSE_CGETRS_TILE(MORSE_enum *trans, MORSE_desc_t *A, int *IPIV, MORSE_desc_t *B, int *info)
//{ *info = MORSE_cgetrs_Tile(*trans, A, IPIV, B); }

void MORSE_CGETRS_INCPIV_TILE(MORSE_desc_t *A, MORSE_desc_t *L, int *IPIV, MORSE_desc_t *B, int *info)
{ *info = MORSE_cgetrs_incpiv_Tile(A, L, IPIV, B); }

void MORSE_CGETRS_NOPIV_TILE(MORSE_desc_t *A, MORSE_desc_t *B, int *info)
{ *info = MORSE_cgetrs_nopiv_Tile(A, B); }

//void MORSE_CHEEV_TILE(MORSE_enum *jobz, MORSE_enum *uplo, MORSE_desc_t *A, float *W, MORSE_desc_t *T, MORSE_Complex32_t *Q, int *LDQ, int *info)
//{ *info = MORSE_cheev_Tile(*jobz, *uplo, A, W, T, Q, *LDQ); }
//
//void MORSE_CHEEVD_TILE(MORSE_enum *jobz, MORSE_enum *uplo, MORSE_desc_t *A, float *W, MORSE_desc_t *T, MORSE_Complex32_t *Q, int *LDQ, int *info)
//{ *info = MORSE_cheevd_Tile(*jobz, *uplo, A, W, T, Q, *LDQ); }
//
//void MORSE_CHEGST_TILE(MORSE_enum *itype, MORSE_enum *uplo, MORSE_desc_t *A, MORSE_desc_t *B, int *info)
//{ *info = MORSE_chegst_Tile(*itype, *uplo, A, B); }
//
//void MORSE_CHEGV_TILE(MORSE_enum *itype, MORSE_enum *jobz, MORSE_enum *uplo, MORSE_desc_t *A, MORSE_desc_t *B, float *W, MORSE_desc_t *T, MORSE_desc_t *Q, int *info)
//{ *info = MORSE_chegv_Tile(*itype, *jobz, *uplo, A, B, W, T, Q); }
//
//void MORSE_CHEGVD_TILE(MORSE_enum *itype, MORSE_enum *jobz, MORSE_enum *uplo, MORSE_desc_t *A, MORSE_desc_t *B, float *W, MORSE_desc_t *T, MORSE_desc_t *Q, int *info)
//{ *info = MORSE_chegvd_Tile(*itype, *jobz, *uplo, A, B, W, T, Q); }

#ifdef COMPLEX
void MORSE_CHEMM_TILE(MORSE_enum *side, MORSE_enum *uplo, MORSE_Complex32_t *alpha, MORSE_desc_t *A, MORSE_desc_t *B, MORSE_Complex32_t *beta, MORSE_desc_t *C, int *info)
{ *info = MORSE_chemm_Tile(*side, *uplo, *alpha, A, B, *beta, C); }
#endif

#ifdef COMPLEX
void MORSE_CHER2K_TILE(MORSE_enum *uplo, MORSE_enum *trans, MORSE_Complex32_t *alpha, MORSE_desc_t *A, MORSE_desc_t *B, float *beta, MORSE_desc_t *C, int *info)
{ *info = MORSE_cher2k_Tile(*uplo, *trans, *alpha, A, B, *beta, C); }
#endif

#ifdef COMPLEX
void MORSE_CHERK_TILE(MORSE_enum *uplo, MORSE_enum *trans, float *alpha, MORSE_desc_t *A, float *beta, MORSE_desc_t *C, int *info)
{ *info = MORSE_cherk_Tile(*uplo, *trans, *alpha, A, *beta, C); }
#endif

//void MORSE_CHETRD_TILE(MORSE_enum *jobz, MORSE_enum *uplo, MORSE_desc_t *A, float *D, float *E, MORSE_desc_t *T, MORSE_Complex32_t *Q, int *LDQ, int *info)
//{ *info = MORSE_chetrd_Tile(*jobz, *uplo, A, D, E, T, Q, *LDQ); }

void MORSE_CLACPY_TILE(MORSE_enum *uplo, MORSE_desc_t *A, MORSE_desc_t *B, int *info)
{ *info = MORSE_clacpy_Tile(*uplo, A, B); }

void MORSE_CLANGE_TILE(MORSE_enum *norm, MORSE_desc_t *A, float *result)
{ *result = MORSE_clange_Tile(*norm, A); }

#ifdef COMPLEX
void MORSE_CLANHE_TILE(MORSE_enum *norm, MORSE_enum *uplo, MORSE_desc_t *A, float *result)
{ *result = MORSE_clanhe_Tile(*norm, *uplo, A); }
#endif

void MORSE_CLANSY_TILE(MORSE_enum *norm, MORSE_enum *uplo, MORSE_desc_t *A, float *result)
{ *result = MORSE_clansy_Tile(*norm, *uplo, A); }

void MORSE_CLANTR_TILE(MORSE_enum *norm, MORSE_enum *uplo, MORSE_enum *diag, MORSE_desc_t *A, float *result)
{ *result = MORSE_clantr_Tile(*norm, *uplo, *diag, A); }

void MORSE_CLASET_TILE(MORSE_enum *uplo, MORSE_Complex32_t *alpha, MORSE_Complex32_t *beta, MORSE_desc_t *A, int *info)
{ *info = MORSE_claset_Tile(*uplo, *alpha, *beta, A); }

//void MORSE_CLASWP_TILE(MORSE_desc_t *A, int *K1, int *K2, int *IPIV, int *INCX, int *info)
//{ *info = MORSE_claswp_Tile(A, *K1, *K2, IPIV, *INCX); }
//
//void MORSE_CLASWPC_TILE(MORSE_desc_t *A, int *K1, int *K2, int *IPIV, int *INCX, int *info)
//{ *info = MORSE_claswpc_Tile(A, *K1, *K2, IPIV, *INCX); }

void MORSE_CLAUUM_TILE(MORSE_enum *uplo, MORSE_desc_t *A, int *info)
{ *info = MORSE_clauum_Tile(*uplo, A); }

#ifdef COMPLEX
void MORSE_CPLGHE_TILE(float *bump, MORSE_desc_t *A, unsigned long long int  *seed, int *info)
{ *info = MORSE_cplghe_Tile(*bump, A, *seed); }
#endif

void MORSE_CPLGSY_TILE(MORSE_Complex32_t *bump, MORSE_desc_t *A, unsigned long long int  *seed, int *info)
{ *info = MORSE_cplgsy_Tile(*bump, A, *seed); }

void MORSE_CPLRNT_TILE(MORSE_desc_t *A, unsigned long long int  *seed, int *info)
{ *info = MORSE_cplrnt_Tile(A, *seed); }

void MORSE_CPOSV_TILE(MORSE_enum *uplo, MORSE_desc_t *A, MORSE_desc_t *B, int *info)
{ *info = MORSE_cposv_Tile(*uplo, A, B); }

void MORSE_CPOTRF_TILE(MORSE_enum *uplo, MORSE_desc_t *A, int *info)
{ *info = MORSE_cpotrf_Tile(*uplo, A); }

void MORSE_CPOTRI_TILE(MORSE_enum *uplo, MORSE_desc_t *A, int *info)
{ *info = MORSE_cpotri_Tile(*uplo, A); }

void MORSE_CPOTRS_TILE(MORSE_enum *uplo, MORSE_desc_t *A, MORSE_desc_t *B, int *info)
{ *info = MORSE_cpotrs_Tile(*uplo, A, B); }

#if defined (PRECISION_c) || defined(PRECISION_z)
void MORSE_CSYSV_TILE(MORSE_enum *uplo, MORSE_desc_t *A, MORSE_desc_t *B, int *info)
{ *info = MORSE_csysv_Tile(*uplo, A, B); }

void MORSE_CSYTRF_TILE(MORSE_enum *uplo, MORSE_desc_t *A, int *info)
{ *info = MORSE_csytrf_Tile(*uplo, A); }

void MORSE_CSYTRS_TILE(MORSE_enum *uplo, MORSE_desc_t *A, MORSE_desc_t *B, int *info)
{ *info = MORSE_csytrs_Tile(*uplo, A, B); }
#endif

void MORSE_CSYMM_TILE(MORSE_enum *side, MORSE_enum *uplo, MORSE_Complex32_t *alpha, MORSE_desc_t *A, MORSE_desc_t *B, MORSE_Complex32_t *beta, MORSE_desc_t *C, int *info)
{ *info = MORSE_csymm_Tile(*side, *uplo, *alpha, A, B, *beta, C); }

void MORSE_CSYR2K_TILE(MORSE_enum *uplo, MORSE_enum *trans, MORSE_Complex32_t *alpha, MORSE_desc_t *A, MORSE_desc_t *B, MORSE_Complex32_t *beta, MORSE_desc_t *C, int *info)
{ *info = MORSE_csyr2k_Tile(*uplo, *trans, *alpha, A, B, *beta, C); }

void MORSE_CSYRK_TILE(MORSE_enum *uplo, MORSE_enum *trans, MORSE_Complex32_t *alpha, MORSE_desc_t *A, MORSE_Complex32_t *beta, MORSE_desc_t *C, int *info)
{ *info = MORSE_csyrk_Tile(*uplo, *trans, *alpha, A, *beta, C); }

void MORSE_CTRMM_TILE(MORSE_enum *side, MORSE_enum *uplo, MORSE_enum *transA, MORSE_enum *diag, MORSE_Complex32_t *alpha, MORSE_desc_t *A, MORSE_desc_t *B, int *info)
{ *info = MORSE_ctrmm_Tile(*side, *uplo, *transA, *diag, *alpha, A, B); }

void MORSE_CTRSM_TILE(MORSE_enum *side, MORSE_enum *uplo, MORSE_enum *transA, MORSE_enum *diag, MORSE_Complex32_t *alpha, MORSE_desc_t *A, MORSE_desc_t *B, int *info)
{ *info = MORSE_ctrsm_Tile(*side, *uplo, *transA, *diag, *alpha, A, B); }

void MORSE_CTRSMPL_TILE(MORSE_desc_t *A, MORSE_desc_t *L, int *IPIV, MORSE_desc_t *B, int *info)
{ *info = MORSE_ctrsmpl_Tile(A, L, IPIV, B); }

//void MORSE_CTRSMRV_TILE(MORSE_enum *side, MORSE_enum *uplo, MORSE_enum *transA, MORSE_enum *diag, MORSE_Complex32_t *alpha, MORSE_desc_t *A, MORSE_desc_t *B, int *info)
//{ *info = MORSE_ctrsmrv_Tile(*side, *uplo, *transA, *diag, *alpha, A, B); }

void MORSE_CTRTRI_TILE(MORSE_enum *uplo, MORSE_enum *diag, MORSE_desc_t *A, int *info)
{ *info = MORSE_ctrtri_Tile(*uplo, *diag, A); }

void MORSE_CUNGLQ_TILE(MORSE_desc_t *A, MORSE_desc_t *T, MORSE_desc_t *B, int *info)
{ *info = MORSE_cunglq_Tile(A, T, B); }

void MORSE_CUNGQR_TILE(MORSE_desc_t *A, MORSE_desc_t *T, MORSE_desc_t *B, int *info)
{ *info = MORSE_cungqr_Tile(A, T, B); }

void MORSE_CUNMLQ_TILE(MORSE_enum *side, MORSE_enum *trans, MORSE_desc_t *A, MORSE_desc_t *T, MORSE_desc_t *B, int *info)
{ *info = MORSE_cunmlq_Tile(*side, *trans, A, T, B); }

void MORSE_CUNMQR_TILE(MORSE_enum *side, MORSE_enum *trans, MORSE_desc_t *A, MORSE_desc_t *T, MORSE_desc_t *B, int *info)
{ *info = MORSE_cunmqr_Tile(*side, *trans, A, T, B); }


/***************************************************************************//**
 *  FORTRAN API - math functions (asynchronous interface)
 **/
//void MORSE_CGEBRD_TILE_ASYNC(MORSE_desc_t *A, float *D, float *E, MORSE_desc_t *T, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
//{ *info = MORSE_cgebrd_Tile_Async(A, D, E, T, sequence, request); }

void MORSE_CGELQF_TILE_ASYNC(MORSE_desc_t *A, MORSE_desc_t *T, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_cgelqf_Tile_Async(A, T, sequence, request); }

void MORSE_CGELQS_TILE_ASYNC(MORSE_desc_t *A, MORSE_desc_t *T, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_cgelqs_Tile_Async(A, T, B, sequence, request); }

void MORSE_CGELS_TILE_ASYNC(MORSE_enum *trans, MORSE_desc_t *A, MORSE_desc_t *T, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_cgels_Tile_Async(*trans, A, T, B, sequence, request); }

void MORSE_CGEMM_TILE_ASYNC(MORSE_enum *transA, MORSE_enum *transB, MORSE_Complex32_t *alpha, MORSE_desc_t *A, MORSE_desc_t *B, MORSE_Complex32_t *beta, MORSE_desc_t *C, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_cgemm_Tile_Async(*transA, *transB, *alpha, A, B, *beta, C, sequence, request); }

void MORSE_CGEQRF_TILE_ASYNC(MORSE_desc_t *A, MORSE_desc_t *T, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_cgeqrf_Tile_Async(A, T, sequence, request); }

void MORSE_CGEQRS_TILE_ASYNC(MORSE_desc_t *A, MORSE_desc_t *T, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_cgeqrs_Tile_Async(A, T, B, sequence, request); }

//void MORSE_CGESV_TILE_ASYNC(MORSE_desc_t *A, int *IPIV, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
//{ *info = MORSE_cgesv_Tile_Async(A, IPIV, B, sequence, request); }

void MORSE_CGESV_INCPIV_TILE_ASYNC(MORSE_desc_t *A, MORSE_desc_t *L, int *IPIV, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_cgesv_incpiv_Tile_Async(A, L, IPIV, B, sequence, request); }

//void MORSE_CGESV_NOPIV_TILE_ASYNC(MORSE_desc_t *A, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
//{ *info = MORSE_cgesv_nopiv_Tile_Async(A, B, sequence, request); }
//
//void MORSE_CGESVD_TILE_ASYNC(MORSE_enum *jobu, MORSE_enum *jobvt, MORSE_desc_t *A, float *S, MORSE_desc_t *U, MORSE_desc_t *VT, MORSE_desc_t *T, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
//{ *info = MORSE_cgesvd_Tile_Async(*jobu, *jobvt, A, S, U, VT, T, sequence, request); }

//void MORSE_CGETRF_TILE_ASYNC(MORSE_desc_t *A, int *IPIV, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
//{ *info = MORSE_cgetrf_Tile_Async(A, IPIV, sequence, request); }

void MORSE_CGETRF_INCPIV_TILE_ASYNC(MORSE_desc_t *A, MORSE_desc_t *L, int *IPIV, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_cgetrf_incpiv_Tile_Async(A, L, IPIV, sequence, request); }

void MORSE_CGETRF_NOPIV_TILE_ASYNC(MORSE_desc_t *A, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_cgetrf_nopiv_Tile_Async(A, sequence, request); }

//void MORSE_CGETRI_TILE_ASYNC(MORSE_desc_t *A, int *IPIV, MORSE_desc_t *W, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
//{ *info = MORSE_cgetri_Tile_Async(A, IPIV, W, sequence, request); }
//
//void MORSE_CGETRS_TILE_ASYNC(MORSE_enum *trans, MORSE_desc_t *A, int *IPIV, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
//{ *info = MORSE_cgetrs_Tile_Async(*trans, A, IPIV, B, sequence, request); }

void MORSE_CGETRS_INCPIV_TILE_ASYNC(MORSE_desc_t *A, MORSE_desc_t *L, int *IPIV, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_cgetrs_incpiv_Tile_Async(A, L, IPIV, B, sequence, request); }

void MORSE_CGETRS_NOPIV_TILE_ASYNC(MORSE_desc_t *A, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_cgetrs_nopiv_Tile_Async(A, B, sequence, request); }

//void MORSE_CHEEV_TILE_ASYNC(MORSE_enum *jobz, MORSE_enum *uplo, MORSE_desc_t *A, float *W, MORSE_desc_t *T, MORSE_Complex32_t *Q, int *LDQ, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
//{ *info = MORSE_cheev_Tile_Async(*jobz, *uplo, A, W, T, Q, *LDQ, sequence, request); }
//
//void MORSE_CHEEVD_TILE_ASYNC(MORSE_enum *jobz, MORSE_enum *uplo, MORSE_desc_t *A, float *W, MORSE_desc_t *T, MORSE_Complex32_t *Q, int *LDQ, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
//{ *info = MORSE_cheevd_Tile_Async(*jobz, *uplo, A, W, T, Q, *LDQ, sequence, request); }
//
//void MORSE_CHEGST_TILE_ASYNC(MORSE_enum *itype, MORSE_enum *uplo, MORSE_desc_t *A, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
//{ *info = MORSE_chegst_Tile_Async(*itype, *uplo, A, B, sequence, request); }
//
//void MORSE_CHEGV_TILE_ASYNC(MORSE_enum *itype, MORSE_enum *jobz, MORSE_enum *uplo, MORSE_desc_t *A, MORSE_desc_t *B, float *W, MORSE_desc_t *T, MORSE_desc_t *Q, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
//{ *info = MORSE_chegv_Tile_Async(*itype, *jobz, *uplo, A, B, W, T, Q, sequence, request); }
//
//void MORSE_CHEGVD_TILE_ASYNC(MORSE_enum *itype, MORSE_enum *jobz, MORSE_enum *uplo, MORSE_desc_t *A, MORSE_desc_t *B, float *W, MORSE_desc_t *T, MORSE_desc_t *Q, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
//{ *info = MORSE_chegvd_Tile_Async(*itype, *jobz, *uplo, A, B, W, T, Q, sequence, request); }

#ifdef COMPLEX
void MORSE_CHEMM_TILE_ASYNC(MORSE_enum *side, MORSE_enum *uplo, MORSE_Complex32_t *alpha, MORSE_desc_t *A, MORSE_desc_t *B, MORSE_Complex32_t *beta, MORSE_desc_t *C, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_chemm_Tile_Async(*side, *uplo, *alpha, A, B, *beta, C, sequence, request); }
#endif

#ifdef COMPLEX
void MORSE_CHER2K_TILE_ASYNC(MORSE_enum *uplo, MORSE_enum *trans, MORSE_Complex32_t *alpha, MORSE_desc_t *A, MORSE_desc_t *B, float *beta, MORSE_desc_t *C, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_cher2k_Tile_Async(*uplo, *trans, *alpha, A, B, *beta, C, sequence, request); }
#endif

#ifdef COMPLEX
void MORSE_CHERK_TILE_ASYNC(MORSE_enum *uplo, MORSE_enum *trans, float *alpha, MORSE_desc_t *A, float *beta, MORSE_desc_t *C, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_cherk_Tile_Async(*uplo, *trans, *alpha, A, *beta, C, sequence, request); }
#endif

//void MORSE_CHETRD_TILE_ASYNC(MORSE_enum *jobz, MORSE_enum *uplo, MORSE_desc_t *A, float *D, float *E, MORSE_desc_t *T, MORSE_Complex32_t *Q, int *LDQ, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
//{ *info = MORSE_chetrd_Tile_Async(*jobz, *uplo, A, D, E, T, Q, *LDQ, sequence, request); }

void MORSE_CLACPY_TILE_ASYNC(MORSE_enum *uplo, MORSE_desc_t *A, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_clacpy_Tile_Async(*uplo, A, B, sequence, request); }

void MORSE_CLANGE_TILE_ASYNC(MORSE_enum *norm, MORSE_desc_t *A, float *value, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_clange_Tile_Async(*norm, A, value, sequence, request); }

#ifdef COMPLEX
void MORSE_CLANHE_TILE_ASYNC(MORSE_enum *norm, MORSE_enum *uplo, MORSE_desc_t *A, float *value, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_clanhe_Tile_Async(*norm, *uplo, A, value, sequence, request); }
#endif

void MORSE_CLANSY_TILE_ASYNC(MORSE_enum *norm, MORSE_enum *uplo, MORSE_desc_t *A, float *value, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_clansy_Tile_Async(*norm, *uplo, A, value, sequence, request); }

void MORSE_CLANTR_TILE_ASYNC(MORSE_enum *norm, MORSE_enum *uplo, MORSE_enum *diag, MORSE_desc_t *A, float *value, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_clantr_Tile_Async(*norm, *uplo, *diag, A, value, sequence, request); }

void MORSE_CLASET_TILE_ASYNC(MORSE_enum *uplo, MORSE_Complex32_t *alpha, MORSE_Complex32_t *beta, MORSE_desc_t *A, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_claset_Tile_Async(*uplo, *alpha, *beta, A, sequence, request); }

//void MORSE_CLASWP_TILE_ASYNC(MORSE_desc_t *A, int *K1, int *K2, int *IPIV, int *INCX, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
//{ *info = MORSE_claswp_Tile_Async(A, *K1, *K2, IPIV, *INCX, sequence, request); }
//
//void MORSE_CLASWPC_TILE_ASYNC(MORSE_desc_t *A, int *K1, int *K2, int *IPIV, int *INCX, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
//{ *info = MORSE_claswpc_Tile_Async(A, *K1, *K2, IPIV, *INCX, sequence, request); }

void MORSE_CLAUUM_TILE_ASYNC(MORSE_enum *uplo, MORSE_desc_t *A, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_clauum_Tile_Async(*uplo, A, sequence, request); }

#ifdef COMPLEX
void MORSE_CPLGHE_TILE_ASYNC(float *bump, MORSE_desc_t *A, unsigned long long int *seed, MORSE_sequence_t *sequence, MORSE_request_t * *request, int *info)
{ *info = MORSE_cplghe_Tile_Async(*bump, A, *seed, sequence, *request); }
#endif

void MORSE_CPLGSY_TILE_ASYNC(MORSE_Complex32_t *bump, MORSE_desc_t *A, unsigned long long int *seed, MORSE_sequence_t *sequence, MORSE_request_t * *request, int *info)
{ *info = MORSE_cplgsy_Tile_Async(*bump, A, *seed, sequence, *request); }

void MORSE_CPLRNT_TILE_ASYNC(MORSE_desc_t *A, unsigned long long int *seed, MORSE_sequence_t *sequence, MORSE_request_t * *request, int *info)
{ *info = MORSE_cplrnt_Tile_Async(A, *seed, sequence, *request); }

void MORSE_CPOSV_TILE_ASYNC(MORSE_enum *uplo, MORSE_desc_t *A, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_cposv_Tile_Async(*uplo, A, B, sequence, request); }

void MORSE_CPOTRF_TILE_ASYNC(MORSE_enum *uplo, MORSE_desc_t *A, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_cpotrf_Tile_Async(*uplo, A, sequence, request); }

void MORSE_CPOTRI_TILE_ASYNC(MORSE_enum *uplo, MORSE_desc_t *A, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_cpotri_Tile_Async(*uplo, A, sequence, request); }

void MORSE_CPOTRS_TILE_ASYNC(MORSE_enum *uplo, MORSE_desc_t *A, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_cpotrs_Tile_Async(*uplo, A, B, sequence, request); }

#if defined (PRECISION_c) || defined(PRECISION_z)
void MORSE_CSYSV_TILE_ASYNC(MORSE_enum *uplo, MORSE_desc_t *A, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_csysv_Tile_Async(*uplo, A, B, sequence, request); }

void MORSE_CSYTRF_TILE_ASYNC(MORSE_enum *uplo, MORSE_desc_t *A, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_csytrf_Tile_Async(*uplo, A, sequence, request); }

void MORSE_CSYTRS_TILE_ASYNC(MORSE_enum *uplo, MORSE_desc_t *A, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_csytrs_Tile_Async(*uplo, A, B, sequence, request); }
#endif

void MORSE_CSYMM_TILE_ASYNC(MORSE_enum *side, MORSE_enum *uplo, MORSE_Complex32_t *alpha, MORSE_desc_t *A, MORSE_desc_t *B, MORSE_Complex32_t *beta, MORSE_desc_t *C, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_csymm_Tile_Async(*side, *uplo, *alpha, A, B, *beta, C, sequence, request); }

void MORSE_CSYR2K_TILE_ASYNC(MORSE_enum *uplo, MORSE_enum *trans, MORSE_Complex32_t *alpha, MORSE_desc_t *A, MORSE_desc_t *B, MORSE_Complex32_t *beta, MORSE_desc_t *C, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_csyr2k_Tile_Async(*uplo, *trans, *alpha, A, B, *beta, C, sequence, request); }

void MORSE_CSYRK_TILE_ASYNC(MORSE_enum *uplo, MORSE_enum *trans, MORSE_Complex32_t *alpha, MORSE_desc_t *A, MORSE_Complex32_t *beta, MORSE_desc_t *C, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_csyrk_Tile_Async(*uplo, *trans, *alpha, A, *beta, C, sequence, request); }

void MORSE_CTRMM_TILE_ASYNC(MORSE_enum *side, MORSE_enum *uplo, MORSE_enum *transA, MORSE_enum *diag, MORSE_Complex32_t *alpha, MORSE_desc_t *A, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_ctrmm_Tile_Async(*side, *uplo, *transA, *diag, *alpha, A, B, sequence, request); }

void MORSE_CTRSM_TILE_ASYNC(MORSE_enum *side, MORSE_enum *uplo, MORSE_enum *transA, MORSE_enum *diag, MORSE_Complex32_t *alpha, MORSE_desc_t *A, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_ctrsm_Tile_Async(*side, *uplo, *transA, *diag, *alpha, A, B, sequence, request); }

void MORSE_CTRSMPL_TILE_ASYNC(MORSE_desc_t *A, MORSE_desc_t *L, int *IPIV, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_ctrsmpl_Tile_Async(A, L, IPIV, B, sequence, request); }

//void MORSE_CTRSMRV_TILE_ASYNC(MORSE_enum *side, MORSE_enum *uplo, MORSE_enum *transA, MORSE_enum *diag, MORSE_Complex32_t *alpha, MORSE_desc_t *A, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
//{ *info = MORSE_ctrsmrv_Tile_Async(*side, *uplo, *transA, *diag, *alpha, A, B, sequence, request); }

void MORSE_CTRTRI_TILE_ASYNC(MORSE_enum *uplo, MORSE_enum *diag, MORSE_desc_t *A, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_ctrtri_Tile_Async(*uplo, *diag, A, sequence, request); }

void MORSE_CUNGLQ_TILE_ASYNC(MORSE_desc_t *A, MORSE_desc_t *T, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_cunglq_Tile_Async(A, T, B, sequence, request); }

void MORSE_CUNGQR_TILE_ASYNC(MORSE_desc_t *A, MORSE_desc_t *T, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_cungqr_Tile_Async(A, T, B, sequence, request); }

void MORSE_CUNMLQ_TILE_ASYNC(MORSE_enum *side, MORSE_enum *trans, MORSE_desc_t *A, MORSE_desc_t *T, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_cunmlq_Tile_Async(*side, *trans, A, T, B, sequence, request); }

void MORSE_CUNMQR_TILE_ASYNC(MORSE_enum *side, MORSE_enum *trans, MORSE_desc_t *A, MORSE_desc_t *T, MORSE_desc_t *B, MORSE_sequence_t *sequence, MORSE_request_t *request, int *info)
{ *info = MORSE_cunmqr_Tile_Async(*side, *trans, A, T, B, sequence, request); }


/***************************************************************************//**
 *  FORTRAN API - workspace allocation
 **/
//void MORSE_ALLOC_WORKSPACE_CGEBRD(int *M, int *N, MORSE_desc_t **descT, int *info)
//{ *info = MORSE_Alloc_Workspace_cgebrd(*M, *N, descT); }
//
//void MORSE_ALLOC_WORKSPACE_CGEEV(int *N, MORSE_desc_t **descT, int *info)
//{ *info = MORSE_Alloc_Workspace_cgeev(*N, descT); }
//
//void MORSE_ALLOC_WORKSPACE_CGEHRD(int *N, MORSE_desc_t **descT, int *info)
//{ *info = MORSE_Alloc_Workspace_cgehrd(*N, descT); }

void MORSE_ALLOC_WORKSPACE_CGELQF(int *M, int *N, MORSE_desc_t **T, int *info)
{ *info = MORSE_Alloc_Workspace_cgelqf(*M, *N, T); }

void MORSE_ALLOC_WORKSPACE_CGELQF_TILE(int *M, int *N, MORSE_desc_t **descT, int *info)
{ *info = MORSE_Alloc_Workspace_cgelqf_Tile(*M, *N, descT); }

void MORSE_ALLOC_WORKSPACE_CGELS(int *M, int *N, MORSE_desc_t **T, int *info)
{ *info = MORSE_Alloc_Workspace_cgels(*M, *N, T); }

void MORSE_ALLOC_WORKSPACE_CGELS_TILE(int *M, int *N, MORSE_desc_t **descT, int *info)
{ *info = MORSE_Alloc_Workspace_cgels_Tile(*M, *N, descT); }

void MORSE_ALLOC_WORKSPACE_CGEQRF(int *M, int *N, MORSE_desc_t **T, int *info)
{ *info = MORSE_Alloc_Workspace_cgeqrf(*M, *N, T); }

void MORSE_ALLOC_WORKSPACE_CGEQRF_TILE(int *M, int *N, MORSE_desc_t **descT, int *info)
{ *info = MORSE_Alloc_Workspace_cgeqrf_Tile(*M, *N, descT); }

void MORSE_ALLOC_WORKSPACE_CGESV_INCPIV(int *N, MORSE_desc_t **descL, int **IPIV, int *info)
{ *info = MORSE_Alloc_Workspace_cgesv_incpiv(*N, descL, IPIV); }

void MORSE_ALLOC_WORKSPACE_CGESV_INCPIV_TILE (int *N, MORSE_desc_t **descL, int **IPIV, int *info)
{ *info = MORSE_Alloc_Workspace_cgesv_incpiv_Tile (*N, descL, IPIV); }

//void MORSE_ALLOC_WORKSPACE_CGESVD(int *M, int *N, MORSE_desc_t **descT, int *info)
//{ *info = MORSE_Alloc_Workspace_cgesvd(*M, *N, descT); }

void MORSE_ALLOC_WORKSPACE_CGETRF_INCPIV(int *M, int *N, MORSE_desc_t **descL, int **IPIV, int *info)
{ *info = MORSE_Alloc_Workspace_cgetrf_incpiv(*M, *N, descL, IPIV); }

void MORSE_ALLOC_WORKSPACE_CGETRF_INCPIV_TILE(int *N, MORSE_desc_t **descL, int **IPIV, int *info)
{ *info = MORSE_Alloc_Workspace_cgetrf_incpiv_Tile(*N, descL, IPIV); }

//void MORSE_ALLOC_WORKSPACE_CGETRI_TILE_ASYNC(MORSE_desc_t *A, MORSE_desc_t *W, int *info)
//{ *info = MORSE_Alloc_Workspace_cgetri_Tile_Async(A, W); }

//void MORSE_ALLOC_WORKSPACE_CHEEV(int *M, int *N, MORSE_desc_t **descT, int *info)
//{ *info = MORSE_Alloc_Workspace_cheev(*M, *N, descT); }
//
//void MORSE_ALLOC_WORKSPACE_CHEEVD(int *M, int *N, MORSE_desc_t **descT, int *info)
//{ *info = MORSE_Alloc_Workspace_cheevd(*M, *N, descT); }
//
//void MORSE_ALLOC_WORKSPACE_ZHEGV(int *M, int *N, MORSE_desc_t **descT, int *info)
//{ *info = MORSE_Alloc_Workspace_chegv(*M, *N, descT); }
//
//void MORSE_ALLOC_WORKSPACE_CHEGVD(int *M, int *N, MORSE_desc_t **descT, int *info)
//{ *info = MORSE_Alloc_Workspace_chegvd(*M, *N, descT); }
//
//void MORSE_ALLOC_WORKSPACE_CHETRD(int *M, int *N, MORSE_desc_t **descT, int *info)
//{ *info = MORSE_Alloc_Workspace_chetrd(*M, *N, descT); }



