CHAMELEON: CORE_zparfb
int CORE_zparfb (MORSE_enum side, MORSE_enum trans, MORSE_enum direct, MORSE_enum storev, int M1, int N1, int M2, int N2, int K, int L, MORSE_Complex64_t * A1, int LDA1, MORSE_Complex64_t * A2, int LDA2, const MORSE_Complex64_t * V, int LDV, const MORSE_Complex64_t * T, int LDT, MORSE_Complex64_t * WORK, int LDWORK)
CORE_zparfb applies a complex upper triangular block reflector H or its transpose H' to a complex rectangular matrix formed by coupling two tiles A1 and A2. Matrix V is:
    COLUMNWISE                    ROWWISE
   |     K     |                 |      N2-L     |   L  |
__ _____________ __           __ _________________        __
   |    |      |                 |               | \
   |    |      |                 |               |   \    L
M2-L | | | K |_______________|_____\ __ | | | M2 | | __ |____| | | | K-L \ | | __ |______________________| __ L \ | | __ |______| __ | N2 |
| L | K-L |
Parameters
[in] side
MorseLeft : apply Q or Q**H from the Left;
MorseRight : apply Q or Q**H from the Right.
[in] trans
MorseNoTrans : No transpose, apply Q;
MorseConjTrans : ConjTranspose, apply Q**H.
[in] direct Indicates how H is formed from a product of elementary reflectors
MorseForward : H = H(1) H(2) . . . H(k) (Forward)
MorseBackward : H = H(k) . . . H(2) H(1) (Backward)
[in] storev Indicates how the vectors which define the elementary reflectors are stored:
MorseColumnwise
MorseRowwise
[in] M1 The number of columns of the tile A1. M1 >= 0.
[in] N1 The number of rows of the tile A1. N1 >= 0.
[in] M2 The number of columns of the tile A2. M2 >= 0.
[in] N2 The number of rows of the tile A2. N2 >= 0.
[in] K The order of the matrix T (= the number of elementary reflectors whose product defines the block reflector).
[in] L The size of the triangular part of V
[in,out] A1 On entry, the M1-by-N1 tile A1. On exit, A1 is overwritten by the application of Q.
[in] LDA1 The leading dimension of the array A1. LDA1 >= max(1,N1).
[in,out] A2 On entry, the M2-by-N2 tile A2. On exit, A2 is overwritten by the application of Q.
[in] LDA2 The leading dimension of the tile A2. LDA2 >= max(1,N2).
[in] V (LDV,K) if STOREV = 'C' (LDV,M2) if STOREV = 'R' and SIDE = 'L' (LDV,N2) if STOREV = 'R' and SIDE = 'R' Matrix V.
[in] LDV The leading dimension of the array V. If STOREV = 'C' and SIDE = 'L', LDV >= max(1,M2); if STOREV = 'C' and SIDE = 'R', LDV >= max(1,N2); if STOREV = 'R', LDV >= K.
[out] T The triangular K-by-K matrix T in the representation of the block reflector. T is upper triangular by block (economic storage); The rest of the array is not referenced.
[in] LDT The leading dimension of the array T. LDT >= K.
[in,out] WORK
[in] LDWORK The dimension of the array WORK.
Returns
Return values
MORSE_SUCCESS successful exit
<0 if -i, the i-th argument had an illegal value
Definition at line 147 of file core_zparfb.c.
References CORE_zpamm().
Referenced by CORE_ztsmlq(), CORE_ztsmqr(), CORE_zttlqt(), CORE_zttmlq(), CORE_zttmqr(), and CORE_zttqrt().