CHAMELEON: MORSE_ztrsmpl_Tile_Async
int MORSE_ztrsmpl_Tile_Async (MORSE_desc_t * A, MORSE_desc_t * L, int * IPIV, MORSE_desc_t * B, MORSE_sequence_t * sequence, MORSE_request_t * request)
MORSE_ztrsmpl_Tile - Performs the forward substitution step of solving a system of linear equations after the tile LU factorization of the matrix. Non-blocking equivalent of MORSE_ztrsmpl_Tile(). Returns control to the user thread before worker threads finish the computation to allow for pipelined execution of diferent routines.
Parameters
[in] sequence Identifies the sequence of function calls that this call belongs to (for completion checks and exception handling purposes).
[out] request Identifies this function call (for exception handling purposes).
See also
MORSE_ztrsmpl
MORSE_ztrsmpl_Tile
MORSE_ctrsmpl_Tile_Async
MORSE_dtrsmpl_Tile_Async
MORSE_strsmpl_Tile_Async
MORSE_zgetrf_incpiv_Tile_Async
Definition at line 253 of file ztrsmpl.c.
References morse_pztrsmpl().
Referenced by MORSE_ztrsmpl(), and MORSE_ztrsmpl_Tile().