# CMake generated Testfile for 
# Source directory: /tmp/marcos/spack-stage/spack-stage-fPQgje/chameleon-0.9.1/timing
# Build directory: /tmp/marcos/spack-stage/spack-stage-fPQgje/chameleon-0.9.1/spack-build/timing
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(time_shm_sgels "./time_sgels_tile" "--check" "--nowarmup")
add_test(time_shm_sgemm "./time_sgemm_tile" "--check" "--nowarmup")
add_test(time_shm_sgetrf_incpiv "./time_sgetrf_incpiv_tile" "--check" "--nowarmup")
add_test(time_shm_sgetrf_nopiv "./time_sgetrf_nopiv_tile" "--check" "--nowarmup")
add_test(time_shm_sgeqrf "./time_sgeqrf_tile" "--check" "--nowarmup")
add_test(time_shm_sposv "./time_sposv_tile" "--check" "--nowarmup")
add_test(time_shm_spotrf "./time_spotrf_tile" "--check" "--nowarmup")
add_test(time_shm_spotri "./time_spotri_tile" "--check" "--nowarmup")
add_test(time_shm_dgels "./time_dgels_tile" "--check" "--nowarmup")
add_test(time_shm_dgemm "./time_dgemm_tile" "--check" "--nowarmup")
add_test(time_shm_dgetrf_incpiv "./time_dgetrf_incpiv_tile" "--check" "--nowarmup")
add_test(time_shm_dgetrf_nopiv "./time_dgetrf_nopiv_tile" "--check" "--nowarmup")
add_test(time_shm_dgeqrf "./time_dgeqrf_tile" "--check" "--nowarmup")
add_test(time_shm_dposv "./time_dposv_tile" "--check" "--nowarmup")
add_test(time_shm_dpotrf "./time_dpotrf_tile" "--check" "--nowarmup")
add_test(time_shm_dpotri "./time_dpotri_tile" "--check" "--nowarmup")
add_test(time_shm_cgels "./time_cgels_tile" "--check" "--nowarmup")
add_test(time_shm_cgemm "./time_cgemm_tile" "--check" "--nowarmup")
add_test(time_shm_cgetrf_incpiv "./time_cgetrf_incpiv_tile" "--check" "--nowarmup")
add_test(time_shm_cgetrf_nopiv "./time_cgetrf_nopiv_tile" "--check" "--nowarmup")
add_test(time_shm_cgeqrf "./time_cgeqrf_tile" "--check" "--nowarmup")
add_test(time_shm_cposv "./time_cposv_tile" "--check" "--nowarmup")
add_test(time_shm_cpotrf "./time_cpotrf_tile" "--check" "--nowarmup")
add_test(time_shm_cpotri "./time_cpotri_tile" "--check" "--nowarmup")
add_test(time_shm_zgels "./time_zgels_tile" "--check" "--nowarmup")
add_test(time_shm_zgemm "./time_zgemm_tile" "--check" "--nowarmup")
add_test(time_shm_zgetrf_incpiv "./time_zgetrf_incpiv_tile" "--check" "--nowarmup")
add_test(time_shm_zgetrf_nopiv "./time_zgetrf_nopiv_tile" "--check" "--nowarmup")
add_test(time_shm_zgeqrf "./time_zgeqrf_tile" "--check" "--nowarmup")
add_test(time_shm_zposv "./time_zposv_tile" "--check" "--nowarmup")
add_test(time_shm_zpotrf "./time_zpotrf_tile" "--check" "--nowarmup")
add_test(time_shm_zpotri "./time_zpotri_tile" "--check" "--nowarmup")
add_test(time_shm_csytrf "./time_csytrf_tile" "--check" "--nowarmup")
add_test(time_shm_zsytrf "./time_zsytrf_tile" "--check" "--nowarmup")
add_test(time_mpi_spotrf "mpirun" "-np" "4" "./time_spotrf_tile" "--p=2 --n_range=20000:20000:1 --nb=320" "--check" "--nowarmup")
add_test(time_mpi_dpotrf "mpirun" "-np" "4" "./time_dpotrf_tile" "--p=2 --n_range=20000:20000:1 --nb=320" "--check" "--nowarmup")
add_test(time_mpi_cpotrf "mpirun" "-np" "4" "./time_cpotrf_tile" "--p=2 --n_range=20000:20000:1 --nb=320" "--check" "--nowarmup")
add_test(time_mpi_zpotrf "mpirun" "-np" "4" "./time_zpotrf_tile" "--p=2 --n_range=20000:20000:1 --nb=320" "--check" "--nowarmup")
